/**
 * Action Library — reusable, emotionally-safe action TYPES.
 *
 * Each card describes one ActionType. The selection layer recommends which
 * TYPES fit a moment; the LLM writes the final, personalised wording. Keeping
 * actions as types (not fixed scripts) lets readings stay specific without ever
 * sounding canned — and keeps every action inside safe, non-clinical bounds.
 */

import type { KnowledgeCard } from "./types.ts";

export const actionLibraryCards: KnowledgeCard[] = [
  {
    id: "action.journal_prompt",
    system: "action",
    key: "journal_prompt",
    title: "Journal prompt",
    plainMeaning: "A single, open question that helps the person notice what they actually feel or want, without pressure to fix anything.",
    strengths: ["Builds self-awareness", "Low effort, high insight", "Safe for almost any mood"],
    growthEdges: ["Keep it to one question — a wall of prompts overwhelms"],
    supportiveActions: ["journal_prompt"],
    avoidSaying: ["Write about everything that's wrong", "Analyse why you're like this"],
    synthesisTags: ["self_worth", "learning_growth", "decision_clarity"],
    confidenceNotes: ["A reflection tool, not therapy."],
    safetyNotes: ["If journaling surfaces crisis-level distress, route to real support."],
  },
  {
    id: "action.boundary_script",
    system: "action",
    key: "boundary_script",
    title: "Boundary script",
    plainMeaning: "A short, kind sentence the person can say to protect their time, energy, or values — clear without being combative.",
    strengths: ["Turns a feeling into a doable next step", "Protects energy", "Reduces resentment"],
    growthEdges: ["A boundary is about your own limit, not controlling the other person"],
    supportiveActions: ["boundary_script"],
    avoidSaying: ["Tell them they're toxic", "Cut them off immediately"],
    synthesisTags: ["boundaries", "self_worth", "communication"],
    confidenceNotes: ["Offer wording the person can adapt, not an ultimatum."],
    safetyNotes: ["For safety-threatening situations, prioritise real-world support over a script."],
  },
  {
    id: "action.relationship_repair",
    system: "action",
    key: "relationship_repair",
    title: "Relationship repair script",
    plainMeaning: "A warm opener that names a feeling and invites reconnection, used when there's tension worth tending rather than ending.",
    strengths: ["Replaces blame with curiosity", "Re-opens closed conversations", "Models accountability"],
    growthEdges: ["Repair is an invitation; the other person still gets to choose their response"],
    supportiveActions: ["relationship_repair"],
    avoidSaying: ["Make them apologise first", "They'll never change"],
    synthesisTags: ["connection_love", "communication", "boundaries"],
    confidenceNotes: ["Repair language assumes a basically safe relationship."],
    safetyNotes: ["Never push repair where there is abuse or coercion; prioritise the user's safety."],
  },
  {
    id: "action.decision_clarity",
    system: "action",
    key: "decision_clarity",
    title: "Decision clarity exercise",
    plainMeaning: "A small structured step — like naming the real options or sleeping on it — that helps the person hear their own answer.",
    strengths: ["Slows reactivity", "Separates fear from preference", "Respects their own authority"],
    growthEdges: ["The goal is their clarity, not a verdict handed down from outside"],
    supportiveActions: ["decision_clarity"],
    avoidSaying: ["You should definitely do X", "The cards say leave/quit/buy"],
    synthesisTags: ["decision_clarity", "timing_patience", "self_worth"],
    confidenceNotes: ["Soluna supports the decision; it doesn't make it."],
    safetyNotes: ["No medical, legal, or financial directives — surface considerations only."],
  },
  {
    id: "action.focus_exercise",
    system: "action",
    key: "focus_exercise",
    title: "Work / school focus exercise",
    plainMeaning: "A tiny, concrete starting move — one task, one timer, one page — that lowers the bar to begin.",
    strengths: ["Beats overwhelm with smallness", "Creates momentum", "Kind to tired brains"],
    growthEdges: ["Start smaller than feels impressive; momentum compounds"],
    supportiveActions: ["focus_exercise", "next_step_plan"],
    avoidSaying: ["Just push through", "Discipline is all you need"],
    synthesisTags: ["work_focus", "action_initiative", "planning_structure"],
    confidenceNotes: ["A productivity nudge, not a performance demand."],
    safetyNotes: [],
  },
  {
    id: "action.nervous_system_reset",
    system: "action",
    key: "nervous_system_reset",
    title: "Nervous-system reset",
    plainMeaning: "A brief, gentle body-based pause — a slow exhale, a stretch, stepping outside — to take the edge off activation.",
    strengths: ["Works in under a minute", "Accessible anywhere", "Settles before deciding"],
    growthEdges: ["Regulation first, problem-solving second"],
    supportiveActions: ["nervous_system_reset"],
    avoidSaying: ["Calm down", "Hold ice / snap a band / use pain to cope"],
    synthesisTags: ["stress_regulation", "rest_recovery"],
    confidenceNotes: ["A grounding practice, not a medical treatment."],
    safetyNotes: ["Never suggest pain, cold-shock, or other self-punishing 'coping'; those reinforce harm."],
  },
  {
    id: "action.values_check",
    system: "action",
    key: "values_check",
    title: "Values check",
    plainMeaning: "A prompt to name what matters most here, so a choice or conflict can be measured against the person's own compass.",
    strengths: ["Anchors decisions in meaning", "Reduces people-pleasing", "Clarifies trade-offs"],
    growthEdges: ["Values can conflict; the work is choosing which leads today, not erasing the other"],
    supportiveActions: ["values_check", "journal_prompt"],
    avoidSaying: ["Your values are wrong", "A good person would choose X"],
    synthesisTags: ["self_worth", "decision_clarity", "boundaries"],
    confidenceNotes: ["Their values lead; Soluna only helps name them."],
    safetyNotes: [],
  },
  {
    id: "action.gratitude_reframe",
    system: "action",
    key: "gratitude_reframe",
    title: "Gratitude / reframe",
    plainMeaning: "A gentle shift of attention toward something steady or good — never to bypass hard feelings, only to widen the frame.",
    strengths: ["Builds resilience", "Counters all-or-nothing thinking", "Softens a harsh inner voice"],
    growthEdges: ["Reframe alongside hard feelings, not instead of them"],
    supportiveActions: ["gratitude_reframe"],
    avoidSaying: ["Just be positive", "Others have it worse"],
    synthesisTags: ["self_worth", "stress_regulation", "nurture_care"],
    confidenceNotes: ["A reframe honours reality; it doesn't deny it."],
    safetyNotes: ["Do not use gratitude to dismiss grief, anger, or genuine distress."],
  },
  {
    id: "action.next_step_plan",
    system: "action",
    key: "next_step_plan",
    title: "Planning the next step",
    plainMeaning: "Naming the single, doable next action — concrete and time-bound enough to actually happen.",
    strengths: ["Turns insight into motion", "Right-sizes big goals", "Ends a reading with traction"],
    growthEdges: ["One next step is enough; the whole staircase can wait"],
    supportiveActions: ["next_step_plan"],
    avoidSaying: ["Here's your 10-step life plan", "You must do this today or else"],
    synthesisTags: ["planning_structure", "action_initiative", "work_focus"],
    confidenceNotes: ["A suggestion to try, never a command."],
    safetyNotes: [],
  },
];
