import type { KnowledgeCard } from "./types.ts";

/**
 * BaZi / Four Pillars cards — Soluna-owned, original reflective interpretation.
 *
 * These are the FULL-DEPTH Eastern layer and are selected ONLY from real,
 * provider-backed BaZi data (see engines/bazi.ts). They are distinct from the
 * lightweight birth-year Chinese-zodiac cards in eastern-astrology.ts. BaZi here
 * is a reflective lens for self-insight and entertainment — never fixed fate, and
 * never used for wealth, marriage, health, legal, or destiny predictions.
 */
export const baziCards: KnowledgeCard[] = [
{
    id: "bazi.daymaster.yang_wood", system: "bazi", key: "day_master_yang_wood", title: "Yang Wood Day Master",
    plainMeaning: "A tall-tree temperament — upright, growth-seeking, and steady. You tend to stand by your principles and reach toward the light, offering shelter and direction to those around you.",
    strengths: ["Principled and dependable", "Growth-oriented and resilient", "A steadying, sheltering presence"],
    growthEdges: ["Bending with the wind rather than only standing firm", "Letting others share the weight you carry"],
    supportiveActions: ["values_check", "next_step_plan"],
    avoidSaying: ["This guarantees you will succeed in life", "Your fate as a leader is sealed"],
    synthesisTags: ["leadership", "learning_growth"],
    confidenceNotes: ["A reflection on your core temperament, offered as a mirror.", "BaZi is a reflective lens for self-insight, not fixed fate."],
    safetyNotes: [],
  },
  {
    id: "bazi.daymaster.yin_wood", system: "bazi", key: "day_master_yin_wood", title: "Yin Wood Day Master",
    plainMeaning: "A vine-and-flower temperament — adaptable, resourceful, and quietly persistent. You tend to find your way around obstacles and bloom wherever you can take root.",
    strengths: ["Flexible and adaptable", "Quietly persistent and resourceful", "Warm and people-attuned"],
    growthEdges: ["Honoring your own direction, not only adapting to others", "Asking for support before you feel stretched thin"],
    supportiveActions: ["values_check", "boundary_script"],
    avoidSaying: ["You are destined to depend on others", "Your soft nature means you will be taken advantage of"],
    synthesisTags: ["connection_love", "change_release"],
    confidenceNotes: ["A reflection on your adaptable temperament, offered as a mirror.", "BaZi is a reflective lens for self-insight, not fixed fate."],
    safetyNotes: [],
  },
  {
    id: "bazi.daymaster.yang_fire", system: "bazi", key: "day_master_yang_fire", title: "Yang Fire Day Master",
    plainMeaning: "A sunlight temperament — radiant, generous, and warming. You tend to brighten rooms and lift the people in them, sharing your energy openly and without much holding back.",
    strengths: ["Warm and generous with energy", "Naturally encouraging to others", "Open-hearted and expressive"],
    growthEdges: ["Tending your own light so it does not burn low", "Pacing your output across the day"],
    supportiveActions: ["nervous_system_reset", "values_check"],
    avoidSaying: ["You will always be the center of attention", "Your fate is to shine for everyone but yourself"],
    synthesisTags: ["connection_love", "rest_recovery"],
    confidenceNotes: ["A reflection on your radiant temperament, offered as a mirror.", "BaZi is a reflective lens for self-insight, not fixed fate."],
    safetyNotes: [],
  },
  {
    id: "bazi.daymaster.yin_fire", system: "bazi", key: "day_master_yin_fire", title: "Yin Fire Day Master",
    plainMeaning: "A candle-and-lamp temperament — warm, focused, and attentive. You tend to give steady, intimate light, illuminating one thing or one person at a time with real care.",
    strengths: ["Warm and emotionally attentive", "Capable of deep, sustained focus", "Thoughtful and perceptive"],
    growthEdges: ["Protecting your flame from too many drafts at once", "Letting yourself be seen, not only seeing others"],
    supportiveActions: ["focus_exercise", "nervous_system_reset"],
    avoidSaying: ["You are too sensitive to thrive", "Your quiet light means you will be overlooked forever"],
    synthesisTags: ["work_focus", "connection_love"],
    confidenceNotes: ["A reflection on your warm, focused temperament, offered as a mirror.", "BaZi is a reflective lens for self-insight, not fixed fate."],
    safetyNotes: [],
  },
  {
    id: "bazi.daymaster.yang_earth", system: "bazi", key: "day_master_yang_earth", title: "Yang Earth Day Master",
    plainMeaning: "A mountain temperament — steadfast, grounded, and reassuring. You tend to be the stable point others lean on, holding your ground through seasons of change.",
    strengths: ["Reliable and grounding", "Patient and even-keeled", "A trustworthy anchor for others"],
    growthEdges: ["Allowing yourself to move and change, not only to hold", "Sharing your inner world rather than carrying it alone"],
    supportiveActions: ["journal_prompt", "values_check"],
    avoidSaying: ["You are too stubborn to ever change", "Your steadiness means life will pass you by"],
    synthesisTags: ["planning_structure", "boundaries"],
    confidenceNotes: ["A reflection on your steadfast temperament, offered as a mirror.", "BaZi is a reflective lens for self-insight, not fixed fate."],
    safetyNotes: [],
  },
  {
    id: "bazi.daymaster.yin_earth", system: "bazi", key: "day_master_yin_earth", title: "Yin Earth Day Master",
    plainMeaning: "A garden-soil temperament — nurturing, supportive, and quietly fertile. You tend to help things and people grow, offering care that often works behind the scenes.",
    strengths: ["Nurturing and supportive", "Practical and resourceful", "Attentive to what others need to flourish"],
    growthEdges: ["Receiving care as readily as you give it", "Naming your own needs out loud"],
    supportiveActions: ["values_check", "boundary_script"],
    avoidSaying: ["You exist only to serve others", "Your giving nature dooms you to be drained"],
    synthesisTags: ["nurture_care", "self_worth"],
    confidenceNotes: ["A reflection on your nurturing temperament, offered as a mirror.", "BaZi is a reflective lens for self-insight, not fixed fate."],
    safetyNotes: [],
  },
  {
    id: "bazi.daymaster.yang_metal", system: "bazi", key: "day_master_yang_metal", title: "Yang Metal Day Master",
    plainMeaning: "An axe-and-sword temperament — decisive, direct, and clear-edged. You tend to cut through confusion and act with conviction once you know what is right.",
    strengths: ["Decisive and clear-minded", "Direct and honest", "Courageous in taking action"],
    growthEdges: ["Softening your edge when gentleness serves better", "Pausing to feel before you decide"],
    supportiveActions: ["decision_clarity", "nervous_system_reset"],
    avoidSaying: ["You are too harsh to be loved", "Your sharpness guarantees conflict in your life"],
    synthesisTags: ["decision_clarity", "action_initiative"],
    confidenceNotes: ["A reflection on your decisive temperament, offered as a mirror.", "BaZi is a reflective lens for self-insight, not fixed fate."],
    safetyNotes: [],
  },
  {
    id: "bazi.daymaster.yin_metal", system: "bazi", key: "day_master_yin_metal", title: "Yin Metal Day Master",
    plainMeaning: "A fine-jewelry temperament — refined, precise, and quietly elegant. You tend to value quality and detail, polishing things until they shine with care.",
    strengths: ["Refined and detail-aware", "An eye for quality and beauty", "Graceful under pressure"],
    growthEdges: ["Letting good enough be enough sometimes", "Trusting your worth beyond a flawless surface"],
    supportiveActions: ["values_check", "gratitude_reframe"],
    avoidSaying: ["You will never be satisfied with anything", "Your perfectionism is a permanent flaw"],
    synthesisTags: ["creativity", "self_worth"],
    confidenceNotes: ["A reflection on your refined temperament, offered as a mirror.", "BaZi is a reflective lens for self-insight, not fixed fate."],
    safetyNotes: [],
  },
  {
    id: "bazi.daymaster.yang_water", system: "bazi", key: "day_master_yang_water", title: "Yang Water Day Master",
    plainMeaning: "An ocean-and-river temperament — expansive, flowing, and far-reaching. You tend to think big, move with momentum, and carry ideas and people along with you.",
    strengths: ["Expansive and visionary", "Adaptable and resourceful", "Quick to connect ideas and people"],
    growthEdges: ["Finding banks to channel your flow toward depth", "Letting yourself rest in stillness now and then"],
    supportiveActions: ["next_step_plan", "focus_exercise"],
    avoidSaying: ["You are too scattered to ever finish anything", "Your restlessness means you will never settle"],
    synthesisTags: ["creativity", "freedom_independence"],
    confidenceNotes: ["A reflection on your expansive temperament, offered as a mirror.", "BaZi is a reflective lens for self-insight, not fixed fate."],
    safetyNotes: [],
  },
  {
    id: "bazi.daymaster.yin_water", system: "bazi", key: "day_master_yin_water", title: "Yin Water Day Master",
    plainMeaning: "A dew-and-mist temperament — gentle, intuitive, and quietly perceptive. You tend to sense the mood beneath the surface and adapt with a soft, subtle touch.",
    strengths: ["Intuitive and perceptive", "Gentle and adaptable", "Thoughtful and imaginative"],
    growthEdges: ["Letting your insights take clear, spoken shape", "Setting gentle limits so you do not absorb everyone's weather"],
    supportiveActions: ["journal_prompt", "boundary_script"],
    avoidSaying: ["You are too delicate to handle real life", "Your sensitivity is a weakness you cannot change"],
    synthesisTags: ["creativity", "stress_regulation"],
    confidenceNotes: ["A reflection on your gentle, intuitive temperament, offered as a mirror.", "BaZi is a reflective lens for self-insight, not fixed fate."],
    safetyNotes: [],
  },
  {
    id: "bazi.strength.strong", system: "bazi", key: "strength_strong", title: "Strong Day Master",
    plainMeaning: "Your chart leans toward a robust, self-assured energy — you likely feel sturdy in yourself and able to drive things forward. The gentle art here is learning when to yield.",
    strengths: ["Self-assured and self-reliant", "Strong follow-through and drive", "Resilient under pressure"],
    growthEdges: ["Yielding and delegating rather than carrying it all", "Inviting other voices before you decide"],
    supportiveActions: ["values_check", "relationship_repair"],
    avoidSaying: ["A strong chart means you are better than others", "This fixes your personality permanently"],
    synthesisTags: ["leadership", "boundaries"],
    confidenceNotes: ["A reflection on your energy balance, offered as a mirror.", "BaZi is a reflective lens for self-insight, not fixed fate."],
    safetyNotes: [],
  },
  {
    id: "bazi.strength.weak", system: "bazi", key: "strength_weak", title: "Receptive Day Master",
    plainMeaning: "Your chart leans toward a receptive, collaborative energy — you likely thrive with support, partnership, and shared effort. The gentle art here is learning to self-source strength too.",
    strengths: ["Collaborative and team-attuned", "Receptive and open to support", "Sensitive to what a moment needs"],
    growthEdges: ["Drawing on your own inner resources first", "Trusting your judgment without waiting for permission"],
    supportiveActions: ["values_check", "next_step_plan"],
    avoidSaying: ["A weak chart means you are weak as a person", "You will always need someone else to cope"],
    synthesisTags: ["connection_love", "self_worth"],
    confidenceNotes: ["A reflection on your energy balance, offered as a mirror.", "BaZi is a reflective lens for self-insight, not fixed fate."],
    safetyNotes: [],
  },
  {
    id: "bazi.strength.balanced", system: "bazi", key: "strength_balanced", title: "Balanced Day Master",
    plainMeaning: "Your chart leans toward an even, adaptable energy — you can often shift between leading and supporting as the situation asks. The gentle art here is trusting your steadiness.",
    strengths: ["Adaptable and even-keeled", "Comfortable leading or supporting", "A natural sense of proportion"],
    growthEdges: ["Choosing a clear direction when many feel possible", "Letting yourself commit fully, not only stay flexible"],
    supportiveActions: ["decision_clarity", "values_check"],
    avoidSaying: ["A balanced chart means your life is set", "This means nothing will ever challenge you"],
    synthesisTags: ["decision_clarity", "planning_structure"],
    confidenceNotes: ["A reflection on your energy balance, offered as a mirror.", "BaZi is a reflective lens for self-insight, not fixed fate."],
    safetyNotes: [],
  },
  {
    id: "bazi.element.excess_wood", system: "bazi", key: "element_excess_wood", title: "Abundant Wood",
    plainMeaning: "Your chart carries plenty of Wood energy — growth, vision, and the drive to expand. There is a lot of green-shoot momentum here to channel with care.",
    strengths: ["Visionary and growth-driven", "Generous and idealistic", "Full of fresh ideas and initiative"],
    growthEdges: ["Pruning so a few aims can truly flourish", "Resting between seasons of growth"],
    supportiveActions: ["next_step_plan", "focus_exercise"],
    avoidSaying: ["Too much Wood means you are doomed to overdo it", "This predicts a chaotic life"],
    synthesisTags: ["creativity", "planning_structure"],
    confidenceNotes: ["A reflection on the elemental balance in your chart, offered as a mirror.", "BaZi is a reflective lens for self-insight, not fixed fate."],
    safetyNotes: [],
  },
  {
    id: "bazi.element.deficient_wood", system: "bazi", key: "element_deficient_wood", title: "Cultivating Wood",
    plainMeaning: "Your chart is quieter in Wood energy — an invitation to cultivate growth, vision, and gentle assertiveness when you wish to. Wood is a quality you can nurture, not something missing.",
    strengths: ["Open to learning new directions", "Thoughtful before reaching outward", "Appreciative of others' growth"],
    growthEdges: ["Planting small intentions and tending them", "Voicing what you want to grow toward"],
    supportiveActions: ["next_step_plan", "journal_prompt"],
    avoidSaying: ["You are lacking and will struggle because of it", "This means you cannot grow"],
    synthesisTags: ["learning_growth", "action_initiative"],
    confidenceNotes: ["A reflection on the elemental balance in your chart, offered as a mirror.", "BaZi is a reflective lens for self-insight, not fixed fate."],
    safetyNotes: [],
  },
  {
    id: "bazi.element.excess_fire", system: "bazi", key: "element_excess_fire", title: "Abundant Fire",
    plainMeaning: "Your chart carries plenty of Fire energy — warmth, passion, and expressive spark. There is real heat and brightness here to enjoy and to pace.",
    strengths: ["Passionate and inspiring", "Warm and openly expressive", "Quick to energize a room"],
    growthEdges: ["Tending the fire so it warms without burning out", "Cooling down before reacting in the heat"],
    supportiveActions: ["nervous_system_reset", "values_check"],
    avoidSaying: ["Too much Fire means you will burn everything down", "This predicts a volatile fate"],
    synthesisTags: ["stress_regulation", "rest_recovery"],
    confidenceNotes: ["A reflection on the elemental balance in your chart, offered as a mirror.", "BaZi is a reflective lens for self-insight, not fixed fate."],
    safetyNotes: [],
  },
  {
    id: "bazi.element.deficient_fire", system: "bazi", key: "element_deficient_fire", title: "Cultivating Fire",
    plainMeaning: "Your chart is quieter in Fire energy — an invitation to cultivate warmth, joy, and visible expression when it feels right. Fire is a quality you can kindle, not something missing.",
    strengths: ["Calm and measured", "Steady rather than easily swayed", "Appreciative of others' warmth"],
    growthEdges: ["Kindling small joys and sharing them", "Letting your enthusiasm be seen"],
    supportiveActions: ["gratitude_reframe", "journal_prompt"],
    avoidSaying: ["You lack passion and always will", "This means you cannot feel joy"],
    synthesisTags: ["self_worth", "connection_love"],
    confidenceNotes: ["A reflection on the elemental balance in your chart, offered as a mirror.", "BaZi is a reflective lens for self-insight, not fixed fate."],
    safetyNotes: [],
  },
  {
    id: "bazi.element.excess_earth", system: "bazi", key: "element_excess_earth", title: "Abundant Earth",
    plainMeaning: "Your chart carries plenty of Earth energy — stability, care, and groundedness. There is a deep reservoir of steadiness here to lean on and to keep in motion.",
    strengths: ["Grounded and dependable", "Caring and protective", "Patient and practical"],
    growthEdges: ["Letting yourself move and risk, not only hold", "Releasing what you have outgrown"],
    supportiveActions: ["next_step_plan", "values_check"],
    avoidSaying: ["Too much Earth means you are stuck forever", "This predicts a heavy, immovable life"],
    synthesisTags: ["planning_structure", "change_release"],
    confidenceNotes: ["A reflection on the elemental balance in your chart, offered as a mirror.", "BaZi is a reflective lens for self-insight, not fixed fate."],
    safetyNotes: [],
  },
  {
    id: "bazi.element.deficient_earth", system: "bazi", key: "element_deficient_earth", title: "Cultivating Earth",
    plainMeaning: "Your chart is quieter in Earth energy — an invitation to cultivate grounding, routine, and steadiness when you need it. Earth is a quality you can build, not something missing.",
    strengths: ["Flexible and unattached to fixed ways", "Open to new ground", "Light on your feet"],
    growthEdges: ["Building small, steady routines", "Giving yourself a stable home base"],
    supportiveActions: ["next_step_plan", "nervous_system_reset"],
    avoidSaying: ["You lack stability and always will", "This means you can never feel safe"],
    synthesisTags: ["planning_structure", "stress_regulation"],
    confidenceNotes: ["A reflection on the elemental balance in your chart, offered as a mirror.", "BaZi is a reflective lens for self-insight, not fixed fate."],
    safetyNotes: [],
  },
  {
    id: "bazi.element.excess_metal", system: "bazi", key: "element_excess_metal", title: "Abundant Metal",
    plainMeaning: "Your chart carries plenty of Metal energy — clarity, structure, and discernment. There is strong definition and resolve here to wield with care.",
    strengths: ["Clear-minded and discerning", "Principled and structured", "Decisive and precise"],
    growthEdges: ["Softening rigid standards toward flexibility", "Letting feeling sit alongside logic"],
    supportiveActions: ["decision_clarity", "nervous_system_reset"],
    avoidSaying: ["Too much Metal means you will always be cold", "This predicts a rigid, lonely fate"],
    synthesisTags: ["decision_clarity", "boundaries"],
    confidenceNotes: ["A reflection on the elemental balance in your chart, offered as a mirror.", "BaZi is a reflective lens for self-insight, not fixed fate."],
    safetyNotes: [],
  },
  {
    id: "bazi.element.deficient_metal", system: "bazi", key: "element_deficient_metal", title: "Cultivating Metal",
    plainMeaning: "Your chart is quieter in Metal energy — an invitation to cultivate clarity, boundaries, and decisiveness when you wish. Metal is a quality you can sharpen, not something missing.",
    strengths: ["Easygoing and accommodating", "Open to many possibilities", "Comfortable with gray areas"],
    growthEdges: ["Practicing clear yes-and-no boundaries", "Naming your standards and holding them"],
    supportiveActions: ["boundary_script", "decision_clarity"],
    avoidSaying: ["You lack discipline and always will", "This means you can never be decisive"],
    synthesisTags: ["boundaries", "decision_clarity"],
    confidenceNotes: ["A reflection on the elemental balance in your chart, offered as a mirror.", "BaZi is a reflective lens for self-insight, not fixed fate."],
    safetyNotes: [],
  },
  {
    id: "bazi.element.excess_water", system: "bazi", key: "element_excess_water", title: "Abundant Water",
    plainMeaning: "Your chart carries plenty of Water energy — depth, intuition, and flow. There is a wide, moving current of feeling and ideas here to channel with care.",
    strengths: ["Intuitive and perceptive", "Adaptable and imaginative", "Emotionally deep and reflective"],
    growthEdges: ["Giving your flow direction and edges", "Coming up for air when feeling runs deep"],
    supportiveActions: ["focus_exercise", "journal_prompt"],
    avoidSaying: ["Too much Water means you will drown in emotion", "This predicts an unstable fate"],
    synthesisTags: ["creativity", "stress_regulation"],
    confidenceNotes: ["A reflection on the elemental balance in your chart, offered as a mirror.", "BaZi is a reflective lens for self-insight, not fixed fate."],
    safetyNotes: [],
  },
  {
    id: "bazi.element.deficient_water", system: "bazi", key: "element_deficient_water", title: "Cultivating Water",
    plainMeaning: "Your chart is quieter in Water energy — an invitation to cultivate reflection, rest, and intuition when you need it. Water is a quality you can invite in, not something missing.",
    strengths: ["Action-ready and grounded", "Clear and practical", "Steady rather than easily moved"],
    growthEdges: ["Making space to pause and reflect", "Trusting quiet intuition alongside logic"],
    supportiveActions: ["journal_prompt", "nervous_system_reset"],
    avoidSaying: ["You lack depth and always will", "This means you cannot be intuitive"],
    synthesisTags: ["rest_recovery", "learning_growth"],
    confidenceNotes: ["A reflection on the elemental balance in your chart, offered as a mirror.", "BaZi is a reflective lens for self-insight, not fixed fate."],
    safetyNotes: [],
  },
  {
    id: "bazi.tengod.companion", system: "bazi", key: "ten_god_companion", title: "Companion",
    plainMeaning: "A reflective archetype of peerhood and self-reliance — the part of you that stands shoulder to shoulder, values fairness, and trusts your own two feet.",
    strengths: ["Self-reliant and independent", "A loyal, equal-footing friend", "Confident in your own stance"],
    growthEdges: ["Accepting help without feeling lesser", "Letting closeness in past the peer line"],
    supportiveActions: ["relationship_repair", "values_check"],
    avoidSaying: ["This means you will always go it alone", "Your chart dooms you to rivalry"],
    synthesisTags: ["self_worth", "connection_love"],
    confidenceNotes: ["A reflection on a relational pattern you may recognize, offered as a mirror.", "BaZi is a reflective lens for self-insight, not fixed fate."],
    safetyNotes: [],
  },
  {
    id: "bazi.tengod.rob_wealth", system: "bazi", key: "ten_god_rob_wealth", title: "Bold Drive",
    plainMeaning: "A reflective archetype of bold drive and risk — the part of you that goes after what it wants with daring energy and a competitive spark.",
    strengths: ["Courageous and proactive", "Energizing and motivating", "Quick to seize a moment"],
    growthEdges: ["Weighing risk with patience before leaping", "Sharing the spotlight and the spoils"],
    supportiveActions: ["decision_clarity", "values_check"],
    avoidSaying: ["This predicts you will lose what you have", "Your chart guarantees reckless ruin"],
    synthesisTags: ["action_initiative", "decision_clarity"],
    confidenceNotes: ["A reflection on a relational pattern you may recognize, offered as a mirror.", "BaZi is a reflective lens for self-insight, not fixed fate."],
    safetyNotes: [],
  },
  {
    id: "bazi.tengod.eating_god", system: "bazi", key: "ten_god_eating_god", title: "Easy Expression",
    plainMeaning: "A reflective archetype of easy, generous creativity — the part of you that expresses itself with natural flow, enjoys life's pleasures, and creates for the joy of it.",
    strengths: ["Naturally creative and expressive", "Easygoing and life-enjoying", "Generous with talent and warmth"],
    growthEdges: ["Following through past the first burst of inspiration", "Balancing enjoyment with gentle structure"],
    supportiveActions: ["journal_prompt", "next_step_plan"],
    avoidSaying: ["This means you will never be productive", "Your chart predicts a life of indulgence"],
    synthesisTags: ["creativity", "rest_recovery"],
    confidenceNotes: ["A reflection on a relational pattern you may recognize, offered as a mirror.", "BaZi is a reflective lens for self-insight, not fixed fate."],
    safetyNotes: [],
  },
  {
    id: "bazi.tengod.hurting_officer", system: "bazi", key: "ten_god_hurting_officer", title: "Expressive Nonconformity",
    plainMeaning: "A reflective archetype of expressive nonconformity — the part of you that speaks its truth, questions the rules, and dazzles with originality and flair.",
    strengths: ["Original and outspoken", "Talented and performative", "Unafraid to challenge convention"],
    growthEdges: ["Tempering candor with tact when it matters", "Choosing which rules truly need rewriting"],
    supportiveActions: ["boundary_script", "values_check"],
    avoidSaying: ["This means you will always clash with authority", "Your chart predicts trouble you cannot avoid"],
    synthesisTags: ["communication", "creativity"],
    confidenceNotes: ["A reflection on a relational pattern you may recognize, offered as a mirror.", "BaZi is a reflective lens for self-insight, not fixed fate."],
    safetyNotes: [],
  },
  {
    id: "bazi.tengod.direct_wealth", system: "bazi", key: "ten_god_direct_wealth", title: "Steady Stewardship",
    plainMeaning: "A reflective archetype of diligence and steady stewardship — the part of you that values honest effort, tends what it has carefully, and finds meaning in reliable work.",
    strengths: ["Diligent and dependable", "Grounded and practical", "Careful steward of time and effort"],
    growthEdges: ["Letting go of control over every detail", "Valuing yourself beyond what you produce"],
    supportiveActions: ["values_check", "next_step_plan"],
    avoidSaying: ["This predicts how much money you will have", "Your chart guarantees riches or loss"],
    synthesisTags: ["planning_structure", "work_focus"],
    confidenceNotes: ["A reflection on a relational pattern you may recognize, offered as a mirror.", "BaZi is a reflective lens for self-insight, not fixed fate."],
    safetyNotes: [],
  },
  {
    id: "bazi.tengod.indirect_wealth", system: "bazi", key: "ten_god_indirect_wealth", title: "Resourcefulness",
    plainMeaning: "A reflective archetype of opportunistic resourcefulness — the part of you that spots openings, improvises with flair, and turns chance encounters into possibility.",
    strengths: ["Resourceful and quick-thinking", "Generous and sociable", "Good at spotting opportunity"],
    growthEdges: ["Following through on what you start", "Grounding big ideas in steady steps"],
    supportiveActions: ["next_step_plan", "decision_clarity"],
    avoidSaying: ["This predicts windfalls or financial loss", "Your chart guarantees fortune in money"],
    synthesisTags: ["action_initiative", "creativity"],
    confidenceNotes: ["A reflection on a relational pattern you may recognize, offered as a mirror.", "BaZi is a reflective lens for self-insight, not fixed fate."],
    safetyNotes: [],
  },
  {
    id: "bazi.tengod.direct_officer", system: "bazi", key: "ten_god_direct_officer", title: "Structure and Responsibility",
    plainMeaning: "A reflective archetype of structure and responsibility — the part of you that honors commitments, respects fair order, and takes its duties seriously.",
    strengths: ["Responsible and trustworthy", "Fair-minded and principled", "Reliable under commitment"],
    growthEdges: ["Easing self-imposed pressure to be perfect", "Letting flexibility sit beside the rules"],
    supportiveActions: ["values_check", "nervous_system_reset"],
    avoidSaying: ["This predicts status or its loss", "Your chart fixes your rank in life"],
    synthesisTags: ["planning_structure", "leadership"],
    confidenceNotes: ["A reflection on a relational pattern you may recognize, offered as a mirror.", "BaZi is a reflective lens for self-insight, not fixed fate."],
    safetyNotes: [],
  },
  {
    id: "bazi.tengod.seven_killings", system: "bazi", key: "ten_god_seven_killings", title: "Courage Under Pressure",
    plainMeaning: "A reflective archetype of intensity and courage under pressure — the part of you that rises when stakes are high, acts boldly, and thrives on a meaningful challenge.",
    strengths: ["Courageous and decisive", "Resilient under pressure", "A natural in high-stakes moments"],
    growthEdges: ["Resting between challenges, not only powering through", "Channeling intensity with patience"],
    supportiveActions: ["nervous_system_reset", "decision_clarity"],
    avoidSaying: ["This predicts conflict or harm in your life", "Your chart dooms you to struggle"],
    synthesisTags: ["action_initiative", "stress_regulation"],
    confidenceNotes: ["A reflection on a relational pattern you may recognize, offered as a mirror.", "BaZi is a reflective lens for self-insight, not fixed fate."],
    safetyNotes: ["If intensity feels overwhelming, slowing down and reaching out is a strength, not a failing."],
  },
  {
    id: "bazi.tengod.direct_resource", system: "bazi", key: "ten_god_direct_resource", title: "Nurture and Learning",
    plainMeaning: "A reflective archetype of nurture and learning received — the part of you that draws strength from support, study, and the care of others, and learns gladly.",
    strengths: ["Open to learning and guidance", "Thoughtful and reflective", "Grateful for support received"],
    growthEdges: ["Acting on what you learn, not only gathering it", "Trusting yourself beyond outside reassurance"],
    supportiveActions: ["journal_prompt", "next_step_plan"],
    avoidSaying: ["This predicts dependence you cannot escape", "Your chart fixes who must care for you"],
    synthesisTags: ["learning_growth", "nurture_care"],
    confidenceNotes: ["A reflection on a relational pattern you may recognize, offered as a mirror.", "BaZi is a reflective lens for self-insight, not fixed fate."],
    safetyNotes: [],
  },
  {
    id: "bazi.tengod.indirect_resource", system: "bazi", key: "ten_god_indirect_resource", title: "Unconventional Insight",
    plainMeaning: "A reflective archetype of unconventional insight and intuition — the part of you that learns in its own way, senses what is unspoken, and finds wisdom off the beaten path.",
    strengths: ["Intuitive and original", "Self-directed in learning", "Perceptive about hidden things"],
    growthEdges: ["Grounding insight so others can share it", "Staying connected rather than retreating inward"],
    supportiveActions: ["journal_prompt", "values_check"],
    avoidSaying: ["This predicts isolation as your fate", "Your chart guarantees you will be misunderstood"],
    synthesisTags: ["learning_growth", "creativity"],
    confidenceNotes: ["A reflection on a relational pattern you may recognize, offered as a mirror.", "BaZi is a reflective lens for self-insight, not fixed fate."],
    safetyNotes: [],
  },
  {
    id: "bazi.pillar.year", system: "bazi", key: "pillar_year", title: "Year Pillar — Roots and Outer Self",
    plainMeaning: "The Year Pillar reflects your roots, early environment, and the social self the world first meets. It is a window into where you come from, not a verdict on where you go.",
    strengths: ["Aware of your origins and heritage", "Attuned to your wider community", "Carries early lessons forward"],
    growthEdges: ["Keeping what nourishes from your roots, releasing the rest", "Letting your present self grow past first impressions"],
    supportiveActions: ["journal_prompt", "values_check"],
    avoidSaying: ["Your origins determine your whole fate", "This predicts your standing in the world"],
    synthesisTags: ["learning_growth", "connection_love"],
    confidenceNotes: ["A reflection on a life theme this pillar points to, offered as a mirror.", "BaZi is a reflective lens for self-insight, not fixed fate."],
    safetyNotes: [],
  },
  {
    id: "bazi.pillar.month", system: "bazi", key: "pillar_month", title: "Month Pillar — Growth and Work",
    plainMeaning: "The Month Pillar reflects your growing years, your drive in work and craft, and your relationship with mentors and parents. It is a window into how you build, not a fixed forecast.",
    strengths: ["Motivated to develop your craft", "Attuned to mentors and growth", "Engaged with meaningful work"],
    growthEdges: ["Letting work be one part of you, not all of you", "Defining success by your own values"],
    supportiveActions: ["values_check", "next_step_plan"],
    avoidSaying: ["This predicts your career outcome", "Your work fate is sealed by your chart"],
    synthesisTags: ["work_focus", "learning_growth"],
    confidenceNotes: ["A reflection on a life theme this pillar points to, offered as a mirror.", "BaZi is a reflective lens for self-insight, not fixed fate."],
    safetyNotes: [],
  },
  {
    id: "bazi.pillar.day", system: "bazi", key: "pillar_day", title: "Day Pillar — Core Self and Closeness",
    plainMeaning: "The Day Pillar reflects your core self and your way of being close to others. It is the heart of the chart — a mirror for who you are, not a script for your relationships.",
    strengths: ["In touch with your core self", "Capable of real closeness", "Authentic in intimate moments"],
    growthEdges: ["Showing your true self before you feel fully ready", "Balancing closeness with healthy space"],
    supportiveActions: ["relationship_repair", "journal_prompt"],
    avoidSaying: ["This predicts your marriage or partner", "Your chart decides who you will love"],
    synthesisTags: ["connection_love", "self_worth"],
    confidenceNotes: ["A reflection on a life theme this pillar points to, offered as a mirror.", "BaZi is a reflective lens for self-insight, not fixed fate."],
    safetyNotes: [],
  },
  {
    id: "bazi.pillar.hour", system: "bazi", key: "pillar_hour", title: "Hour Pillar — Inner World and Becoming",
    plainMeaning: "The Hour Pillar reflects your inner world, your creativity, and what you are quietly growing toward. It is a window into your becoming, not a forecast of later life.",
    strengths: ["Connected to your inner world", "Creative and forward-looking", "Aware of what you are growing toward"],
    growthEdges: ["Bringing private dreams into the daylight", "Trusting that becoming is a slow, kind process"],
    supportiveActions: ["journal_prompt", "next_step_plan"],
    avoidSaying: ["This predicts your later years", "Your future is fixed by this pillar"],
    synthesisTags: ["creativity", "learning_growth"],
    confidenceNotes: ["A reflection on a life theme this pillar points to, offered as a mirror.", "BaZi is a reflective lens for self-insight, not fixed fate."],
    safetyNotes: [],
  },
  {
    id: "bazi.favorable.wood", system: "bazi", key: "favorable_wood", title: "Favorable Wood — Lean Into Growth",
    plainMeaning: "Wood is a supportive theme for your chart's balance — an invitation to lean into growth, fresh starts, and gentle expansion. Think learning, planting new intentions, and reaching toward light.",
    strengths: ["Energized by growth and learning", "Open to new beginnings", "Uplifted by green, living spaces"],
    growthEdges: ["Letting new growth take root before adding more", "Pairing big visions with small first steps"],
    supportiveActions: ["next_step_plan", "values_check"],
    avoidSaying: ["This element guarantees good fortune", "Without this you are destined to struggle"],
    synthesisTags: ["learning_growth", "action_initiative"],
    confidenceNotes: ["A reflection on a supportive theme to lean into, offered as a mirror.", "BaZi is a reflective lens for self-insight, not fixed fate."],
    safetyNotes: [],
  },
  {
    id: "bazi.favorable.fire", system: "bazi", key: "favorable_fire", title: "Favorable Fire — Lean Into Warmth",
    plainMeaning: "Fire is a supportive theme for your chart's balance — an invitation to lean into warmth, joy, and visible expression. Think connection, creativity, and letting your light be seen.",
    strengths: ["Brightened by warmth and connection", "Energized by creative expression", "Uplifted by light and play"],
    growthEdges: ["Sharing your warmth without burning out", "Letting joy be a practice, not a reward"],
    supportiveActions: ["gratitude_reframe", "values_check"],
    avoidSaying: ["This element guarantees happiness forever", "Without this you are doomed to dullness"],
    synthesisTags: ["connection_love", "creativity"],
    confidenceNotes: ["A reflection on a supportive theme to lean into, offered as a mirror.", "BaZi is a reflective lens for self-insight, not fixed fate."],
    safetyNotes: [],
  },
  {
    id: "bazi.favorable.earth", system: "bazi", key: "favorable_earth", title: "Favorable Earth — Lean Into Grounding",
    plainMeaning: "Earth is a supportive theme for your chart's balance — an invitation to lean into grounding, routine, and steadiness. Think nourishing rhythms, a settled home base, and patient care.",
    strengths: ["Steadied by routine and rhythm", "Grounded by a settled space", "Nourished by patient, practical care"],
    growthEdges: ["Letting structure support you, not confine you", "Staying open to change within steadiness"],
    supportiveActions: ["next_step_plan", "nervous_system_reset"],
    avoidSaying: ["This element guarantees security in life", "Without this you are destined to feel lost"],
    synthesisTags: ["planning_structure", "stress_regulation"],
    confidenceNotes: ["A reflection on a supportive theme to lean into, offered as a mirror.", "BaZi is a reflective lens for self-insight, not fixed fate."],
    safetyNotes: [],
  },
  {
    id: "bazi.favorable.metal", system: "bazi", key: "favorable_metal", title: "Favorable Metal — Lean Into Clarity",
    plainMeaning: "Metal is a supportive theme for your chart's balance — an invitation to lean into clarity, boundaries, and refinement. Think clean decisions, simplifying, and honoring your standards.",
    strengths: ["Helped by clear decisions", "Steadied by healthy boundaries", "Uplifted by simplicity and order"],
    growthEdges: ["Letting clarity stay kind, not rigid", "Refining without chasing perfection"],
    supportiveActions: ["decision_clarity", "boundary_script"],
    avoidSaying: ["This element guarantees success in life", "Without this you are destined for chaos"],
    synthesisTags: ["decision_clarity", "boundaries"],
    confidenceNotes: ["A reflection on a supportive theme to lean into, offered as a mirror.", "BaZi is a reflective lens for self-insight, not fixed fate."],
    safetyNotes: [],
  },
  {
    id: "bazi.favorable.water", system: "bazi", key: "favorable_water", title: "Favorable Water — Lean Into Flow",
    plainMeaning: "Water is a supportive theme for your chart's balance — an invitation to lean into flow, rest, and reflection. Think gentle pacing, intuition, and making space to feel and recharge.",
    strengths: ["Restored by rest and reflection", "Guided by gentle intuition", "Eased by going with the flow"],
    growthEdges: ["Letting rest be allowed, not earned", "Trusting quiet knowing alongside logic"],
    supportiveActions: ["nervous_system_reset", "journal_prompt"],
    avoidSaying: ["This element guarantees peace forever", "Without this you are destined to suffer"],
    synthesisTags: ["rest_recovery", "stress_regulation"],
    confidenceNotes: ["A reflection on a supportive theme to lean into, offered as a mirror.", "BaZi is a reflective lens for self-insight, not fixed fate."],
    safetyNotes: [],
  },
  {
    id: "bazi.luck.pillar_core", system: "bazi", key: "luck_pillar_core", title: "Luck Pillars — Seasons of Life",
    plainMeaning: "Your luck pillars (Da Yun) describe changing seasons across the decades — a gentle rhythm of themes to work with. Each season invites different qualities; none is good or bad, only different.",
    strengths: ["Aware that life moves in seasons", "Able to adapt as themes shift", "Patient with timing and change"],
    growthEdges: ["Meeting each season for what it offers", "Releasing the urge to rush the next chapter"],
    supportiveActions: ["values_check", "next_step_plan"],
    avoidSaying: ["This decade will bring you fortune or misfortune", "Your luck is fixed and out of your hands"],
    synthesisTags: ["timing_patience", "change_release"],
    confidenceNotes: ["A reflection on life's changing rhythms, offered as a mirror.", "BaZi is a reflective lens for self-insight, not fixed fate."],
    safetyNotes: [],
  },
  {
    id: "bazi.core.overview", system: "bazi", key: "bazi_core", title: "Your BaZi Chart — A Reflective Map",
    plainMeaning: "In Soluna, your BaZi chart is a reflective map of elemental energies drawn from your birth date, time, and place. It is a mirror for self-insight and gentle reflection, never fixed fate.",
    strengths: ["A gentle language for self-reflection", "A way to notice patterns kindly", "A starting point for growth"],
    growthEdges: ["Holding the chart lightly, as one lens of many", "Letting your lived experience lead the way"],
    supportiveActions: ["journal_prompt", "values_check"],
    avoidSaying: ["Your chart determines your destiny", "This can predict your future for certain"],
    synthesisTags: ["learning_growth", "self_worth"],
    confidenceNotes: ["An overview of what your chart is and is not, offered as a mirror.", "BaZi is a reflective lens for self-insight, not fixed fate."],
    safetyNotes: ["This is for reflection and entertainment, not advice about health, relationships, money, or major life decisions."],
  },
];
