import type { KnowledgeCard } from "./types.ts";

/**
 * Eastern (Chinese) astrology cards — Soluna-owned, original reflective
 * interpretation. The app only knows the user's birth-year animal, element, and
 * yin/yang polarity, so every card stays high-level and non-deterministic. These
 * are gentle mirrors, not a full Eastern chart and never a fixed fate.
 */
export const easternAstrologyCards: KnowledgeCard[] = [
  // ─── 12 Zodiac Animals ──────────────────────────────────────────
  {
    id: "ea.animal.rat",
    system: "eastern_astrology",
    key: "animal_rat",
    title: "Year of the Rat",
    plainMeaning:
      "The Rat archetype is quick, observant, and resourceful — a mind that notices opportunity early and adapts fast. You tend to think a few steps ahead and find clever ways through problems. At your best you pair curiosity with warmth and a knack for making things work.",
    strengths: ["Quick-thinking and adaptable", "Resourceful problem-solver", "Socially perceptive"],
    growthEdges: ["Can overthink or worry about scarcity", "May spread attention too thin"],
    supportiveActions: ["decision_clarity", "focus_exercise"],
    avoidSaying: ["Rats are sneaky or untrustworthy", "You're destined to scheme to get ahead"],
    synthesisTags: ["decision_clarity", "learning_growth"],
    confidenceNotes: ["Based on birth year only; a reflective lens, not a full Eastern chart."],
    safetyNotes: [],
  },
  {
    id: "ea.animal.ox",
    system: "eastern_astrology",
    key: "animal_ox",
    title: "Year of the Ox",
    plainMeaning:
      "The Ox archetype is steady, patient, and dependable — someone who builds slowly and finishes what they start. You value honest effort and tend to be the calm, reliable anchor others lean on. Your power is in consistency rather than flash.",
    strengths: ["Patient and persistent", "Reliable and grounded", "Strong work ethic"],
    growthEdges: ["Can be stubborn or resist change", "May overwork and forget rest"],
    supportiveActions: ["next_step_plan", "nervous_system_reset"],
    avoidSaying: ["Oxen are boring or inflexible", "You'll never be able to change your mind"],
    synthesisTags: ["work_focus", "planning_structure"],
    confidenceNotes: ["Based on birth year only; a reflective lens, not a full Eastern chart."],
    safetyNotes: [],
  },
  {
    id: "ea.animal.tiger",
    system: "eastern_astrology",
    key: "animal_tiger",
    title: "Year of the Tiger",
    plainMeaning:
      "The Tiger archetype is bold, passionate, and courageous — a spark of brave energy that wants to lead and protect. You feel things strongly and aren't afraid to take a stand. At your best you channel that fire into causes and people you love.",
    strengths: ["Brave and decisive", "Magnetic and passionate", "Natural protector"],
    growthEdges: ["Can act impulsively", "May struggle to pause before reacting"],
    supportiveActions: ["decision_clarity", "nervous_system_reset"],
    avoidSaying: ["Tigers are reckless or aggressive by nature", "You can't help losing your temper"],
    synthesisTags: ["action_initiative", "leadership"],
    confidenceNotes: ["Based on birth year only; a reflective lens, not a full Eastern chart."],
    safetyNotes: [],
  },
  {
    id: "ea.animal.rabbit",
    system: "eastern_astrology",
    key: "animal_rabbit",
    title: "Year of the Rabbit",
    plainMeaning:
      "The Rabbit archetype is gentle, gracious, and peace-loving — attuned to harmony and the comfort of others. You tend to read a room with care and value calm over conflict. Your gift is creating safe, kind spaces where people can soften.",
    strengths: ["Gentle and considerate", "Diplomatic peacemaker", "Aesthetic and soothing presence"],
    growthEdges: ["Can avoid needed conflict", "May neglect your own needs to keep peace"],
    supportiveActions: ["boundary_script", "values_check"],
    avoidSaying: ["Rabbits are weak or passive", "Avoiding conflict means you're a pushover"],
    synthesisTags: ["rest_recovery", "connection_love"],
    confidenceNotes: ["Based on birth year only; a reflective lens, not a full Eastern chart."],
    safetyNotes: [],
  },
  {
    id: "ea.animal.dragon",
    system: "eastern_astrology",
    key: "animal_dragon",
    title: "Year of the Dragon",
    plainMeaning:
      "The Dragon archetype is visionary, confident, and charismatic — drawn to big ideas and bold beginnings. You carry a natural shine that inspires others to dream bigger. At your best you lead with generosity and turn vision into momentum.",
    strengths: ["Visionary and inspiring", "Confident and charismatic", "Generous with energy"],
    growthEdges: ["Can chase the next big thing and skip follow-through", "May expect a lot of self and others"],
    supportiveActions: ["next_step_plan", "values_check"],
    avoidSaying: ["Dragons are arrogant", "You always have to be the center of attention"],
    synthesisTags: ["action_initiative", "leadership"],
    confidenceNotes: ["Based on birth year only; a reflective lens, not a full Eastern chart."],
    safetyNotes: [],
  },
  {
    id: "ea.animal.snake",
    system: "eastern_astrology",
    key: "animal_snake",
    title: "Year of the Snake",
    plainMeaning:
      "The Snake archetype is wise, intuitive, and reflective — a quiet observer who senses what lies beneath the surface. You think deeply before you move and value depth over noise. Your gift is discernment: knowing when to shed what no longer fits.",
    strengths: ["Insightful and intuitive", "Calm and self-contained", "Discerning decision-maker"],
    growthEdges: ["Can become guarded or secretive", "May overanalyze before acting"],
    supportiveActions: ["journal_prompt", "decision_clarity"],
    avoidSaying: ["Snakes are cold or manipulative", "Being private means you're hiding something"],
    synthesisTags: ["change_release", "decision_clarity"],
    confidenceNotes: ["Based on birth year only; a reflective lens, not a full Eastern chart."],
    safetyNotes: [],
  },
  {
    id: "ea.animal.horse",
    system: "eastern_astrology",
    key: "animal_horse",
    title: "Year of the Horse",
    plainMeaning:
      "The Horse archetype is free-spirited, energetic, and adventurous — happiest in motion and open spaces. You crave independence and fresh horizons, and your enthusiasm is contagious. At your best you bring warmth and momentum wherever you roam.",
    strengths: ["Energetic and enthusiastic", "Independent and adventurous", "Warm and sociable"],
    growthEdges: ["Can struggle with restlessness", "May resist commitment or routine"],
    supportiveActions: ["focus_exercise", "next_step_plan"],
    avoidSaying: ["Horses are flaky or unreliable", "You'll never be able to settle down"],
    synthesisTags: ["freedom_independence", "action_initiative"],
    confidenceNotes: ["Based on birth year only; a reflective lens, not a full Eastern chart."],
    safetyNotes: [],
  },
  {
    id: "ea.animal.goat",
    system: "eastern_astrology",
    key: "animal_goat",
    title: "Year of the Goat",
    plainMeaning:
      "The Goat archetype is tender, creative, and compassionate — guided by feeling and a love of beauty. You nurture people and ideas gently and notice what others overlook. Your gift is a soft, artistic heart that brings comfort and care.",
    strengths: ["Compassionate and nurturing", "Creative and imaginative", "Gentle and supportive"],
    growthEdges: ["Can be sensitive to criticism", "May lean on others for reassurance"],
    supportiveActions: ["gratitude_reframe", "journal_prompt"],
    avoidSaying: ["Goats are overly needy or fragile", "Being sensitive is a weakness"],
    synthesisTags: ["nurture_care", "creativity"],
    confidenceNotes: ["Based on birth year only; a reflective lens, not a full Eastern chart."],
    safetyNotes: [],
  },
  {
    id: "ea.animal.monkey",
    system: "eastern_astrology",
    key: "animal_monkey",
    title: "Year of the Monkey",
    plainMeaning:
      "The Monkey archetype is clever, playful, and inventive — a curious mind that loves to experiment and improvise. You learn quickly, find humor easily, and solve problems in surprising ways. At your best you bring lightness and ingenuity to any room.",
    strengths: ["Clever and inventive", "Playful and quick-witted", "Curious and adaptable"],
    growthEdges: ["Can get restless or easily bored", "May avoid going deep when distracted"],
    supportiveActions: ["focus_exercise", "next_step_plan"],
    avoidSaying: ["Monkeys are unserious or can't be trusted", "You're just a show-off"],
    synthesisTags: ["creativity", "learning_growth"],
    confidenceNotes: ["Based on birth year only; a reflective lens, not a full Eastern chart."],
    safetyNotes: [],
  },
  {
    id: "ea.animal.rooster",
    system: "eastern_astrology",
    key: "animal_rooster",
    title: "Year of the Rooster",
    plainMeaning:
      "The Rooster archetype is observant, honest, and orderly — someone who notices details and takes pride in doing things well. You speak directly and value clarity and competence. Your gift is bringing structure, precision, and a refreshing candor.",
    strengths: ["Detail-oriented and organized", "Honest and direct", "Diligent and capable"],
    growthEdges: ["Can be critical or perfectionistic", "May be hard on yourself"],
    supportiveActions: ["values_check", "gratitude_reframe"],
    avoidSaying: ["Roosters are vain or bossy", "Your standards make you impossible to please"],
    synthesisTags: ["planning_structure", "communication"],
    confidenceNotes: ["Based on birth year only; a reflective lens, not a full Eastern chart."],
    safetyNotes: [],
  },
  {
    id: "ea.animal.dog",
    system: "eastern_astrology",
    key: "animal_dog",
    title: "Year of the Dog",
    plainMeaning:
      "The Dog archetype is loyal, honest, and protective — a steadfast friend with a strong sense of fairness. You show up for the people you love and care deeply about doing right. Your gift is trustworthiness and a warm, dependable heart.",
    strengths: ["Loyal and trustworthy", "Fair and principled", "Protective of loved ones"],
    growthEdges: ["Can worry or expect the worst", "May struggle to trust easily at first"],
    supportiveActions: ["relationship_repair", "nervous_system_reset"],
    avoidSaying: ["Dogs are anxious or pessimistic by nature", "You're too suspicious of everyone"],
    synthesisTags: ["connection_love", "boundaries"],
    confidenceNotes: ["Based on birth year only; a reflective lens, not a full Eastern chart."],
    safetyNotes: [],
  },
  {
    id: "ea.animal.pig",
    system: "eastern_astrology",
    key: "animal_pig",
    title: "Year of the Pig",
    plainMeaning:
      "The Pig archetype is warm, sincere, and generous — open-hearted and easy to be around. You enjoy life's comforts and share them freely, and your kindness puts people at ease. Your gift is genuine goodwill and a steady, welcoming presence.",
    strengths: ["Warm and generous", "Sincere and easygoing", "Loyal and accepting"],
    growthEdges: ["Can be too trusting or give too much", "May indulge or avoid hard truths"],
    supportiveActions: ["boundary_script", "values_check"],
    avoidSaying: ["Pigs are naive or lazy", "Being kind means people will always take advantage of you"],
    synthesisTags: ["connection_love", "nurture_care"],
    confidenceNotes: ["Based on birth year only; a reflective lens, not a full Eastern chart."],
    safetyNotes: [],
  },

  // ─── 5 Elements ─────────────────────────────────────────────────
  {
    id: "ea.element.wood",
    system: "eastern_astrology",
    key: "element_wood",
    title: "Wood Element",
    plainMeaning:
      "Wood energy is growth-oriented and expansive — like a tree reaching upward. It carries vision, idealism, and the drive to begin and build. When Wood flavors your year, it can feel like a season of stretching toward something new and putting down roots.",
    strengths: ["Growth-minded and visionary", "Generous and collaborative", "Resilient and adaptable"],
    growthEdges: ["Can overextend or take on too much", "May get rigid when blocked"],
    supportiveActions: ["next_step_plan", "values_check"],
    avoidSaying: ["Wood people are pushy", "You must always be producing to matter"],
    synthesisTags: ["learning_growth", "creativity"],
    confidenceNotes: ["Based on birth year only; an energetic flavor, not a full Eastern chart."],
    safetyNotes: [],
  },
  {
    id: "ea.element.fire",
    system: "eastern_astrology",
    key: "element_fire",
    title: "Fire Element",
    plainMeaning:
      "Fire energy is bright, passionate, and expressive — warmth that draws people in. It carries enthusiasm, charisma, and the spark to inspire. When Fire flavors your year, it can feel like a season of connection, visibility, and emotional intensity.",
    strengths: ["Passionate and expressive", "Charismatic and warm", "Inspiring to others"],
    growthEdges: ["Can burn hot then burn out", "May ride emotional highs and lows"],
    supportiveActions: ["nervous_system_reset", "focus_exercise"],
    avoidSaying: ["Fire people are dramatic", "Strong feelings make you too much"],
    synthesisTags: ["action_initiative", "stress_regulation"],
    confidenceNotes: ["Based on birth year only; an energetic flavor, not a full Eastern chart."],
    safetyNotes: [],
  },
  {
    id: "ea.element.earth",
    system: "eastern_astrology",
    key: "element_earth",
    title: "Earth Element",
    plainMeaning:
      "Earth energy is grounded, nurturing, and steady — the stable center that holds things together. It carries patience, care, and a gift for creating security. When Earth flavors your year, it can feel like a season of tending, settling, and supporting.",
    strengths: ["Grounded and dependable", "Nurturing and supportive", "Patient and practical"],
    growthEdges: ["Can over-give or carry others' loads", "May resist change for comfort's sake"],
    supportiveActions: ["boundary_script", "nervous_system_reset"],
    avoidSaying: ["Earth people are stuck or dull", "Your worth comes from taking care of everyone"],
    synthesisTags: ["nurture_care", "planning_structure"],
    confidenceNotes: ["Based on birth year only; an energetic flavor, not a full Eastern chart."],
    safetyNotes: [],
  },
  {
    id: "ea.element.metal",
    system: "eastern_astrology",
    key: "element_metal",
    title: "Metal Element",
    plainMeaning:
      "Metal energy is clear, disciplined, and refined — focused like a well-honed edge. It carries structure, integrity, and a love of quality and order. When Metal flavors your year, it can feel like a season of refining, simplifying, and standing by your values.",
    strengths: ["Disciplined and focused", "Principled and clear", "Refined sense of quality"],
    growthEdges: ["Can become rigid or perfectionistic", "May hold others to strict standards"],
    supportiveActions: ["decision_clarity", "values_check"],
    avoidSaying: ["Metal people are cold", "High standards make you unlovable"],
    synthesisTags: ["planning_structure", "decision_clarity"],
    confidenceNotes: ["Based on birth year only; an energetic flavor, not a full Eastern chart."],
    safetyNotes: [],
  },
  {
    id: "ea.element.water",
    system: "eastern_astrology",
    key: "element_water",
    title: "Water Element",
    plainMeaning:
      "Water energy is fluid, intuitive, and deep — flowing around obstacles and finding the quiet path. It carries adaptability, empathy, and reflective wisdom. When Water flavors your year, it can feel like a season of flow, feeling, and listening inward.",
    strengths: ["Intuitive and reflective", "Adaptable and resourceful", "Empathetic and perceptive"],
    growthEdges: ["Can absorb others' moods", "May drift without a clear shore"],
    supportiveActions: ["journal_prompt", "nervous_system_reset"],
    avoidSaying: ["Water people are wishy-washy", "Feeling deeply means you're unstable"],
    synthesisTags: ["change_release", "stress_regulation"],
    confidenceNotes: ["Based on birth year only; an energetic flavor, not a full Eastern chart."],
    safetyNotes: [],
  },

  // ─── Yin / Yang Polarities ──────────────────────────────────────
  {
    id: "ea.polarity.yin",
    system: "eastern_astrology",
    key: "polarity_yin",
    title: "Yin Polarity",
    plainMeaning:
      "Yin is the receptive, inward, restful current — the energy of listening, gathering, and softening. It is not weakness; it is the wisdom of pausing, receiving, and replenishing. A yin season invites you to slow down, feel, and let things unfold rather than force them.",
    strengths: ["Reflective and receptive", "Calming and nurturing", "Attuned to subtle cues"],
    growthEdges: ["Can hold back when action is needed", "May give until depleted"],
    supportiveActions: ["nervous_system_reset", "journal_prompt"],
    avoidSaying: ["Yin means you're passive or lazy", "Resting is a failure to try harder"],
    synthesisTags: ["rest_recovery", "nurture_care"],
    confidenceNotes: ["Based on birth year only; a reflective lens, not a full Eastern chart."],
    safetyNotes: [],
  },
  {
    id: "ea.polarity.yang",
    system: "eastern_astrology",
    key: "polarity_yang",
    title: "Yang Polarity",
    plainMeaning:
      "Yang is the active, outward, expressive current — the energy of doing, initiating, and moving forward. It is not aggression; it is the spark that starts things and brings ideas into the world. A yang season invites you to step up, take action, and make your mark.",
    strengths: ["Driven and decisive", "Energizing and expressive", "Comfortable taking initiative"],
    growthEdges: ["Can push past your own limits", "May forget to pause and receive"],
    supportiveActions: ["focus_exercise", "nervous_system_reset"],
    avoidSaying: ["Yang means you must always be productive", "Slowing down means you're failing"],
    synthesisTags: ["action_initiative"],
    confidenceNotes: ["Based on birth year only; a reflective lens, not a full Eastern chart."],
    safetyNotes: [],
  },

  // ─── Compatibility Patterns ─────────────────────────────────────
  {
    id: "ea.compat.core",
    system: "eastern_astrology",
    key: "compat_core",
    title: "Compatibility & Rhythms",
    plainMeaning:
      "Eastern tradition groups the animals into harmony sets (trines) that tend to share an easy rhythm, and notes pairs whose styles differ. Treat this gently: some bonds feel naturally in sync, others ask for translation. Different rhythms are not doom — they are simply different paces to honor.",
    strengths: ["Names natural ease between some pairings", "Invites curiosity about another's pace", "Frames friction as difference, not fate"],
    growthEdges: ["Can be misused to judge a relationship before it begins", "May tempt over-reliance on a single signal"],
    supportiveActions: ["relationship_repair", "journal_prompt"],
    avoidSaying: ["You two are incompatible and shouldn't try", "Certain signs are doomed together"],
    synthesisTags: ["connection_love", "communication"],
    confidenceNotes: [
      "Based on birth year only; a reflective lens, not a full Eastern chart.",
      "Compatibility groupings are high-level and never deterministic — real relationships depend on the people, not the labels.",
    ],
    safetyNotes: [],
  },
];
