import type { KnowledgeCard } from "./types.ts";

export const numerologyCards: KnowledgeCard[] = [
  {
    id: "num.lifepath.1",
    system: "numerology",
    key: "life_path_1",
    title: "Life Path 1",
    plainMeaning:
      "A theme of self-leadership and starting things — learning to trust your own direction and act on it rather than wait for permission.",
    strengths: ["Initiative and drive", "Independent thinking", "Courage to go first"],
    growthEdges: ["Softening into help from others", "Letting progress be imperfect"],
    supportiveActions: ["next_step_plan", "decision_clarity"],
    avoidSaying: ["You must always lead or you'll fail", "Needing others is weakness"],
    synthesisTags: ["leadership", "action_initiative", "decision_clarity"],
    confidenceNotes: ["Numerology is a reflective lens, not a prediction."],
    safetyNotes: [],
  },
  {
    id: "num.lifepath.2",
    system: "numerology",
    key: "life_path_2",
    title: "Life Path 2",
    plainMeaning:
      "A theme of connection, partnership and sensitivity — your gift is attunement, and your work is honoring your own needs alongside others'.",
    strengths: ["Deep empathy", "Diplomacy and tact", "Patience in relationships"],
    growthEdges: ["Naming your own preferences", "Not over-merging with others"],
    supportiveActions: ["boundary_script", "values_check"],
    avoidSaying: ["You exist to keep the peace", "Your needs come last"],
    synthesisTags: ["connection_love", "communication", "boundaries"],
    confidenceNotes: ["A reflective theme, not a fixed personality verdict."],
    safetyNotes: [],
  },
  {
    id: "num.lifepath.3",
    system: "numerology",
    key: "life_path_3",
    title: "Life Path 3",
    plainMeaning:
      "A theme of expression and joy — finding your voice through creativity, words and play, and learning to follow through on what you start.",
    strengths: ["Natural creativity", "Warmth and humor", "Expressive communication"],
    growthEdges: ["Focusing scattered energy", "Staying with the harder middle of projects"],
    supportiveActions: ["focus_exercise", "next_step_plan"],
    avoidSaying: ["You're flaky and never finish", "Lightness means you're not serious"],
    synthesisTags: ["creativity", "communication", "work_focus"],
    confidenceNotes: ["Numerology offers reflection, not a measure of your worth."],
    safetyNotes: [],
  },
  {
    id: "num.lifepath.4",
    system: "numerology",
    key: "life_path_4",
    title: "Life Path 4",
    plainMeaning:
      "A theme of building and reliability — creating stable foundations through steady effort, and learning to bend without feeling like you're breaking.",
    strengths: ["Discipline and follow-through", "Practical problem-solving", "Loyalty"],
    growthEdges: ["Allowing rest and flexibility", "Not equating rigidity with safety"],
    supportiveActions: ["next_step_plan", "nervous_system_reset"],
    avoidSaying: ["Slowing down means you're falling behind", "You're rigid"],
    synthesisTags: ["planning_structure", "work_focus", "rest_recovery"],
    confidenceNotes: ["A theme to reflect on, not a rule to obey."],
    safetyNotes: [],
  },
  {
    id: "num.lifepath.5",
    system: "numerology",
    key: "life_path_5",
    title: "Life Path 5",
    plainMeaning:
      "A theme of freedom, change and experience — you grow through variety and curiosity, and steady most when you choose commitments that still leave room to breathe.",
    strengths: ["Adaptability", "Curiosity and adventurousness", "Quick learning"],
    growthEdges: ["Choosing depth over constant novelty", "Following through on commitments"],
    supportiveActions: ["decision_clarity", "values_check"],
    avoidSaying: ["You can never commit", "Wanting freedom means you're unreliable"],
    synthesisTags: ["freedom_independence", "change_release", "learning_growth"],
    confidenceNotes: ["Numerology is a mirror for reflection, not a forecast."],
    safetyNotes: [],
  },
  {
    id: "num.lifepath.6",
    system: "numerology",
    key: "life_path_6",
    title: "Life Path 6",
    plainMeaning:
      "A theme of care, responsibility and home — your gift is nurturing others, and your growth is including yourself in the circle of care.",
    strengths: ["Devotion to loved ones", "A natural sense of responsibility", "Creating harmony"],
    growthEdges: ["Releasing perfectionism", "Caring for yourself, not only others"],
    supportiveActions: ["boundary_script", "values_check", "gratitude_reframe"],
    avoidSaying: ["You must fix everyone", "Your care should be unconditional even at your own cost"],
    synthesisTags: ["nurture_care", "connection_love", "boundaries"],
    confidenceNotes: ["A reflective theme, never a duty assigned to you."],
    safetyNotes: [],
  },
  {
    id: "num.lifepath.7",
    system: "numerology",
    key: "life_path_7",
    title: "Life Path 7",
    plainMeaning:
      "A theme of depth, inquiry and inner truth — you grow through reflection and solitude, and connect best when you let trusted people past the quiet.",
    strengths: ["Analytical insight", "Comfort with solitude", "Spiritual or intellectual depth"],
    growthEdges: ["Opening up to closeness", "Trusting feeling as well as analysis"],
    supportiveActions: ["journal_prompt", "nervous_system_reset"],
    avoidSaying: ["Needing alone time means you're cold", "You overthink everything"],
    synthesisTags: ["rest_recovery", "learning_growth", "timing_patience"],
    confidenceNotes: ["Numerology is a reflective lens, not a prediction."],
    safetyNotes: [],
  },
  {
    id: "num.lifepath.8",
    system: "numerology",
    key: "life_path_8",
    title: "Life Path 8",
    plainMeaning:
      "A theme of power, capability and material mastery — learning to hold ambition and integrity together, and to measure success by more than outcomes.",
    strengths: ["Strategic vision", "Resilience under pressure", "Capacity to manifest results"],
    growthEdges: ["Defining success on your own terms", "Letting people in past the strong front"],
    supportiveActions: ["values_check", "decision_clarity", "next_step_plan"],
    avoidSaying: ["Your worth equals your achievements", "Vulnerability is weakness"],
    synthesisTags: ["leadership", "work_focus", "self_worth"],
    confidenceNotes: ["A theme for reflection, not a verdict on your future."],
    safetyNotes: [],
  },
  {
    id: "num.lifepath.9",
    system: "numerology",
    key: "life_path_9",
    title: "Life Path 9",
    plainMeaning:
      "A theme of compassion, completion and the bigger picture — a wide heart that cares for the whole, learning to also tend the small and personal.",
    strengths: ["Generosity and idealism", "Wisdom from lived experience", "A global, inclusive heart"],
    growthEdges: ["Letting go of what's complete", "Receiving, not only giving"],
    supportiveActions: ["gratitude_reframe", "values_check", "journal_prompt"],
    avoidSaying: ["You must save everyone", "Letting go means you failed"],
    synthesisTags: ["change_release", "nurture_care", "grief_processing"],
    confidenceNotes: ["Numerology is a reflective frame, not certainty."],
    safetyNotes: [],
  },
  {
    id: "num.lifepath.11",
    system: "numerology",
    key: "life_path_11",
    title: "Life Path 11",
    plainMeaning:
      "A heightened version of the 2 — intuition, sensitivity and inspiration run strong. The invitation is to ground big feelings into everyday life.",
    strengths: ["Strong intuition", "Inspiring presence", "Emotional sensitivity"],
    growthEdges: ["Grounding ideals into action", "Protecting your energy from overwhelm"],
    supportiveActions: ["nervous_system_reset", "journal_prompt", "boundary_script"],
    avoidSaying: ["You should always feel special or chosen", "Sensitivity is a burden"],
    synthesisTags: ["connection_love", "creativity", "stress_regulation"],
    confidenceNotes: ["'Master number' is a tradition, not a ranking of people."],
    safetyNotes: [],
  },
  {
    id: "num.lifepath.22",
    system: "numerology",
    key: "life_path_22",
    title: "Life Path 22",
    plainMeaning:
      "A heightened version of the 4 — the 'master builder,' pairing big vision with practical capacity. The work is pacing yourself for the long build.",
    strengths: ["Visionary yet practical", "Capacity for large undertakings", "Disciplined effort"],
    growthEdges: ["Pacing instead of overloading", "Trusting collaborators with the load"],
    supportiveActions: ["next_step_plan", "nervous_system_reset"],
    avoidSaying: ["You must achieve something monumental to matter", "Resting is failing the vision"],
    synthesisTags: ["planning_structure", "leadership", "work_focus"],
    confidenceNotes: ["A reflective theme; it does not predict outcomes."],
    safetyNotes: [],
  },
  {
    id: "num.lifepath.33",
    system: "numerology",
    key: "life_path_33",
    title: "Life Path 33",
    plainMeaning:
      "A heightened version of the 6 — the 'master teacher,' centered on devoted, loving service. The growth is caring widely without abandoning yourself.",
    strengths: ["Deep compassion", "Capacity to uplift others", "Sense of higher purpose"],
    growthEdges: ["Setting limits on giving", "Receiving care in return"],
    supportiveActions: ["boundary_script", "values_check", "gratitude_reframe"],
    avoidSaying: ["Your role is to sacrifice for everyone", "Self-care is selfish"],
    synthesisTags: ["nurture_care", "connection_love", "boundaries"],
    confidenceNotes: ["A reflective tradition, not a measure of how good a person is."],
    safetyNotes: [],
  },
  {
    id: "num.expression.core",
    system: "numerology",
    key: "expression_core",
    title: "Expression / Destiny Number",
    plainMeaning:
      "Drawn from the letters of your full birth name, this number reflects your natural talents and how you tend to show up in the world.",
    strengths: ["Highlights innate talents", "Names how you naturally express yourself"],
    growthEdges: ["Growing into talents you haven't fully used yet", "Not confusing a tendency with a limit"],
    supportiveActions: ["journal_prompt", "values_check"],
    avoidSaying: ["This is the fixed sum of who you are", "You can't develop beyond this"],
    synthesisTags: ["self_worth", "creativity", "learning_growth"],
    confidenceNotes: ["A reflective framing of tendencies, not a fixed identity."],
    safetyNotes: [],
  },
  {
    id: "num.soulurge.core",
    system: "numerology",
    key: "soul_urge_core",
    title: "Soul Urge Number",
    plainMeaning:
      "Drawn from the vowels in your name, this number points to your inner motivations — what your heart quietly longs for beneath outward goals.",
    strengths: ["Surfaces deep motivations", "Connects choices to inner values"],
    growthEdges: ["Honoring desires you've set aside", "Listening inward amid outside expectations"],
    supportiveActions: ["journal_prompt", "values_check", "decision_clarity"],
    avoidSaying: ["This is your hidden destiny you must obey", "Your real self is fixed and unchangeable"],
    synthesisTags: ["self_worth", "connection_love", "learning_growth"],
    confidenceNotes: ["A reflective prompt for self-inquiry, not a prediction."],
    safetyNotes: [],
  },
  {
    id: "num.cycle.personal_year",
    system: "numerology",
    key: "personal_year",
    title: "Personal Year",
    plainMeaning:
      "A 1-9 cycle, reset each year by your birthday and the calendar, offering a reflective theme for the season of life you're moving through.",
    strengths: ["Gives a yearly theme to reflect on", "Helps frame timing and seasons"],
    growthEdges: ["Holding the theme loosely, not as a rule", "Letting your real life override the label"],
    supportiveActions: ["next_step_plan", "values_check", "journal_prompt"],
    avoidSaying: ["This year will definitely bring X", "You can't change what the year holds"],
    synthesisTags: ["timing_patience", "planning_structure", "change_release"],
    confidenceNotes: ["A reflective rhythm, not a forecast of events."],
    safetyNotes: [],
  },
  {
    id: "num.cycle.personal_day",
    system: "numerology",
    key: "personal_day",
    title: "Personal Day",
    plainMeaning:
      "A 1-9 daily rhythm offering a light theme for the day's energy — a gentle suggestion of what may flow easily, not a script for what will happen.",
    strengths: ["Offers a small daily focus", "Easy, low-stakes reflection"],
    growthEdges: ["Treating it as a nudge, not a command", "Trusting your own read of the day"],
    supportiveActions: ["journal_prompt", "next_step_plan"],
    avoidSaying: ["Today must go this way", "Ignore how you actually feel and follow the number"],
    synthesisTags: ["timing_patience", "decision_clarity"],
    confidenceNotes: ["A daily reflective prompt, not a prediction."],
    safetyNotes: [],
  },
  {
    id: "num.personalday.1",
    system: "numerology",
    key: "personal_day_1",
    title: "Personal Day 1",
    plainMeaning: "A fresh-start energy — a good day to begin, decide, or take a first small step toward something new.",
    strengths: ["Momentum for beginnings", "Clarity of intention"],
    growthEdges: ["Starting small rather than overhauling everything"],
    supportiveActions: ["next_step_plan"],
    avoidSaying: ["You must launch something big today"],
    synthesisTags: ["action_initiative"],
    confidenceNotes: ["A reflective daily theme, not a prediction."],
    safetyNotes: [],
  },
  {
    id: "num.personalday.2",
    system: "numerology",
    key: "personal_day_2",
    title: "Personal Day 2",
    plainMeaning: "A cooperation energy — a day that tends to favor patience, listening, and tending to relationships.",
    strengths: ["Openness to others", "Patience and tact"],
    growthEdges: ["Including your own needs in the give and take"],
    supportiveActions: ["relationship_repair", "journal_prompt"],
    avoidSaying: ["You should only focus on others today"],
    synthesisTags: ["connection_love", "communication"],
    confidenceNotes: ["A gentle daily prompt, not a forecast."],
    safetyNotes: [],
  },
  {
    id: "num.personalday.3",
    system: "numerology",
    key: "personal_day_3",
    title: "Personal Day 3",
    plainMeaning: "An expressive energy — a day that tends to support creativity, conversation, and lightness.",
    strengths: ["Creative flow", "Ease in connecting and sharing"],
    growthEdges: ["Channeling scattered energy toward one thing"],
    supportiveActions: ["journal_prompt", "gratitude_reframe"],
    avoidSaying: ["If you're not productive and creative you've wasted the day"],
    synthesisTags: ["creativity", "communication"],
    confidenceNotes: ["A reflective daily theme, not certainty."],
    safetyNotes: [],
  },
  {
    id: "num.personalday.4",
    system: "numerology",
    key: "personal_day_4",
    title: "Personal Day 4",
    plainMeaning: "A structure energy — a day that tends to favor focus, organizing, and steady practical work.",
    strengths: ["Focus and follow-through", "Order and planning"],
    growthEdges: ["Building in small breaks within the effort"],
    supportiveActions: ["next_step_plan", "focus_exercise"],
    avoidSaying: ["You must grind nonstop to honor this day"],
    synthesisTags: ["planning_structure", "work_focus"],
    confidenceNotes: ["A reflective daily prompt, not a prediction."],
    safetyNotes: [],
  },
  {
    id: "num.personalday.5",
    system: "numerology",
    key: "personal_day_5",
    title: "Personal Day 5",
    plainMeaning: "A change energy — a day that tends to favor flexibility, variety, and staying open to the unexpected.",
    strengths: ["Adaptability", "Openness to new experiences"],
    growthEdges: ["Staying grounded amid the movement"],
    supportiveActions: ["decision_clarity", "nervous_system_reset"],
    avoidSaying: ["You have to shake everything up today"],
    synthesisTags: ["change_release", "freedom_independence"],
    confidenceNotes: ["A gentle daily theme, not a forecast."],
    safetyNotes: [],
  },
  {
    id: "num.personalday.6",
    system: "numerology",
    key: "personal_day_6",
    title: "Personal Day 6",
    plainMeaning: "A care energy — a day that tends to favor home, loved ones, and tending what matters to you.",
    strengths: ["Warmth toward others", "Attention to home and relationships"],
    growthEdges: ["Including yourself in the care you give"],
    supportiveActions: ["relationship_repair", "gratitude_reframe"],
    avoidSaying: ["You must take care of everyone else first today"],
    synthesisTags: ["nurture_care", "connection_love"],
    confidenceNotes: ["A reflective daily prompt, not a prediction."],
    safetyNotes: [],
  },
  {
    id: "num.personalday.7",
    system: "numerology",
    key: "personal_day_7",
    title: "Personal Day 7",
    plainMeaning: "A rest-and-reflection energy — a day that tends to favor slowing down, quiet, and inner processing.",
    strengths: ["Capacity for reflection", "Comfort in slowing down"],
    growthEdges: ["Letting rest be productive enough on its own"],
    supportiveActions: ["nervous_system_reset", "journal_prompt"],
    avoidSaying: ["Resting today means you're being lazy"],
    synthesisTags: ["rest_recovery", "timing_patience"],
    confidenceNotes: ["A reflective daily theme, not a forecast."],
    safetyNotes: [],
  },
  {
    id: "num.personalday.8",
    system: "numerology",
    key: "personal_day_8",
    title: "Personal Day 8",
    plainMeaning: "A capability energy — a day that tends to favor practical goals, decisions, and getting things handled.",
    strengths: ["Drive toward results", "Confidence in decisions"],
    growthEdges: ["Measuring the day by more than output"],
    supportiveActions: ["decision_clarity", "next_step_plan"],
    avoidSaying: ["Your value today depends on what you produce"],
    synthesisTags: ["work_focus", "decision_clarity"],
    confidenceNotes: ["A reflective daily prompt, not a prediction."],
    safetyNotes: [],
  },
  {
    id: "num.personalday.9",
    system: "numerology",
    key: "personal_day_9",
    title: "Personal Day 9",
    plainMeaning: "A completion energy — a day that tends to favor wrapping up, releasing, and making space for what's next.",
    strengths: ["Readiness to finish and let go", "A wider, generous perspective"],
    growthEdges: ["Honoring feelings that come with endings"],
    supportiveActions: ["gratitude_reframe", "journal_prompt"],
    avoidSaying: ["You must end something major today"],
    synthesisTags: ["change_release", "grief_processing"],
    confidenceNotes: ["A reflective daily theme, not a forecast."],
    safetyNotes: [],
  },
];
