import type { KnowledgeCard } from "./types.ts";

export const tarotArchetypeCards: KnowledgeCard[] = [
  {
    id: "tarot.major.00_fool",
    system: "tarot",
    key: "the_fool",
    title: "The Fool",
    plainMeaning:
      "A fresh beginning and a leap into the unknown. The Fool invites open-hearted curiosity, a willingness to start before you feel fully ready, and trust in the next small step.",
    strengths: ["Open-hearted curiosity and a beginner's mind", "Courage to start something new", "Freedom from old expectations"],
    growthEdges: ["A chance to pair spontaneity with a little grounding so leaps land softly", "An invitation to notice when avoidance is dressed up as adventure"],
    supportiveActions: ["next_step_plan", "journal_prompt"],
    avoidSaying: ["You are being reckless and will fall", "This warns of a foolish mistake ahead"],
    synthesisTags: ["change_release", "freedom_independence"],
    confidenceNotes: ["Question to ask: What new beginning am I being invited to trust, and what one small step feels possible?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.major.01_magician",
    system: "tarot",
    key: "the_magician",
    title: "The Magician",
    plainMeaning:
      "You already hold the tools you need. The Magician points to focused intention, resourcefulness, and turning ideas into action by aligning what you want with what you do.",
    strengths: ["Resourcefulness and creative skill", "Clear, focused intention", "Ability to turn ideas into action"],
    growthEdges: ["An invitation to make sure your words and actions match", "A nudge to use your gifts in service of something true rather than to impress"],
    supportiveActions: ["next_step_plan", "values_check"],
    avoidSaying: ["You must act now or lose your chance", "Beware manipulation surrounds you"],
    synthesisTags: ["action_initiative", "creativity"],
    confidenceNotes: ["Question to ask: What do I already have that I have been overlooking?", "This reflects a possible inner resource, not a guaranteed outcome."],
    safetyNotes: [],
  },
  {
    id: "tarot.major.02_high_priestess",
    system: "tarot",
    key: "the_high_priestess",
    title: "The High Priestess",
    plainMeaning:
      "A pause to listen inward. The High Priestess honors intuition, quiet knowing, and the wisdom that surfaces when you stop rushing and let things become clear in their own time.",
    strengths: ["Deep intuition and inner knowing", "Comfort with mystery and patience", "Capacity to listen beneath the noise"],
    growthEdges: ["An invitation to trust your quiet signals instead of overriding them", "A gentle nudge to share what you sense rather than keeping it all inside"],
    supportiveActions: ["journal_prompt", "nervous_system_reset"],
    avoidSaying: ["Secrets are being hidden from you", "Ignoring this brings misfortune"],
    synthesisTags: ["timing_patience", "rest_recovery"],
    confidenceNotes: ["Question to ask: What does my quieter, wiser self already sense that I have been talking over?", "Intuition is information to weigh, not a certainty to obey."],
    safetyNotes: [],
  },
  {
    id: "tarot.major.03_empress",
    system: "tarot",
    key: "the_empress",
    title: "The Empress",
    plainMeaning:
      "Nourishment, creativity, and care. The Empress invites you to tend what you are growing, including yourself, with warmth, abundance, and a connection to the senses and the natural world.",
    strengths: ["Nurturing warmth toward self and others", "Creative, generative energy", "Comfort, sensuality, and ease"],
    growthEdges: ["An invitation to receive care, not only give it", "A reminder that tending yourself is part of tending others"],
    supportiveActions: ["nervous_system_reset", "gratitude_reframe"],
    avoidSaying: ["You are neglecting everyone around you", "Smothering others is your flaw"],
    synthesisTags: ["nurture_care", "creativity"],
    confidenceNotes: ["Question to ask: Where could I offer myself the same care I so easily give others?", "This points to a tendency, not a fixed truth about you."],
    safetyNotes: [],
  },
  {
    id: "tarot.major.04_emperor",
    system: "tarot",
    key: "the_emperor",
    title: "The Emperor",
    plainMeaning:
      "Structure, steadiness, and grounded leadership. The Emperor invites you to build stable foundations, set clear boundaries, and bring helpful order to what feels scattered.",
    strengths: ["Grounded leadership and follow-through", "Healthy structure and stability", "Clear, fair boundaries"],
    growthEdges: ["An invitation to let structure stay flexible enough to breathe", "A nudge to lead with warmth alongside firmness"],
    supportiveActions: ["next_step_plan", "boundary_script"],
    avoidSaying: ["You are too controlling and rigid", "Surrender all authority or fail"],
    synthesisTags: ["planning_structure", "leadership"],
    confidenceNotes: ["Question to ask: Where would a little more structure actually free me up?", "Structure is a tool here, not a verdict on your character."],
    safetyNotes: [],
  },
  {
    id: "tarot.major.05_hierophant",
    system: "tarot",
    key: "the_hierophant",
    title: "The Hierophant",
    plainMeaning:
      "Tradition, mentorship, and shared meaning. The Hierophant points to learning from those who came before, finding belonging, and deciding which values you want to carry forward as your own.",
    strengths: ["Respect for wisdom and mentorship", "A sense of belonging and shared values", "Steady, principled grounding"],
    growthEdges: ["An invitation to keep what serves you and gently question what no longer fits", "A nudge to find your own voice within the inherited script"],
    supportiveActions: ["values_check", "journal_prompt"],
    avoidSaying: ["You must conform or be cast out", "Breaking tradition will doom you"],
    synthesisTags: ["learning_growth", "planning_structure"],
    confidenceNotes: ["Question to ask: Which beliefs here are truly mine, and which did I simply inherit?", "This is a reflective prompt about values, not a rule you must obey."],
    safetyNotes: [],
  },
  {
    id: "tarot.major.06_lovers",
    system: "tarot",
    key: "the_lovers",
    title: "The Lovers",
    plainMeaning:
      "Connection, alignment, and meaningful choice. The Lovers invites you to honor what you value in relationships and to choose, with open eyes, the path that matches your deeper truth.",
    strengths: ["Genuine connection and openness", "Values-aligned choices", "Harmony between heart and mind"],
    growthEdges: ["An invitation to choose from your values rather than from fear of missing out", "A nudge to be honest about what you actually want"],
    supportiveActions: ["decision_clarity", "relationship_repair"],
    avoidSaying: ["A wrong choice will ruin everything", "You are destined to lose this love"],
    synthesisTags: ["connection_love", "decision_clarity"],
    confidenceNotes: ["Question to ask: If I chose from my values rather than my fears, which way would I lean?", "A card can clarify a choice but cannot make it for you."],
    safetyNotes: [],
  },
  {
    id: "tarot.major.07_chariot",
    system: "tarot",
    key: "the_chariot",
    title: "The Chariot",
    plainMeaning:
      "Focused momentum and directed will. The Chariot invites you to gather your competing impulses, point them toward one goal, and move forward with steady, self-led determination.",
    strengths: ["Determination and drive", "Self-discipline and focus", "Ability to unite opposing forces toward a goal"],
    growthEdges: ["An invitation to steer with intention rather than push through exhaustion", "A nudge to check that your direction still feels right"],
    supportiveActions: ["next_step_plan", "focus_exercise"],
    avoidSaying: ["Lose control now and everything collapses", "You will be defeated if you slow down"],
    synthesisTags: ["action_initiative", "work_focus"],
    confidenceNotes: ["Question to ask: What would it look like to move forward with focus and without forcing?", "Momentum is something you can shape, not a fate that drives you."],
    safetyNotes: [],
  },
  {
    id: "tarot.major.08_strength",
    system: "tarot",
    key: "strength",
    title: "Strength",
    plainMeaning:
      "Quiet, steady courage. Strength is the gentle power of meeting big feelings with patience rather than force, trusting that softness and self-compassion are their own kind of resilience.",
    strengths: ["Gentle courage and patience", "Emotional resilience and self-compassion", "Calm in the face of intensity"],
    growthEdges: ["An invitation to be as kind to yourself as you are brave for others", "A nudge to let softness, not pressure, guide difficult moments"],
    supportiveActions: ["nervous_system_reset", "journal_prompt"],
    avoidSaying: ["You are too weak to handle this", "Only force will get you through"],
    synthesisTags: ["self_worth", "stress_regulation"],
    confidenceNotes: ["Question to ask: Where could meeting myself with gentleness be stronger than pushing harder?", "Inner strength looks different on different days, and that is okay."],
    safetyNotes: [],
  },
  {
    id: "tarot.major.09_hermit",
    system: "tarot",
    key: "the_hermit",
    title: "The Hermit",
    plainMeaning:
      "A meaningful pause for reflection. The Hermit honors solitude, slowing down, and turning inward to find your own light before stepping back out into the world.",
    strengths: ["Comfort with solitude and reflection", "Inner wisdom and self-honesty", "Willingness to slow down and listen"],
    growthEdges: ["An invitation to make space for rest without slipping into isolation", "A nudge to bring your insights back to the people who care for you"],
    supportiveActions: ["journal_prompt", "nervous_system_reset"],
    avoidSaying: ["You are doomed to be alone", "Withdrawing means you have failed"],
    synthesisTags: ["rest_recovery", "timing_patience"],
    confidenceNotes: ["Question to ask: What might become clear if I gave myself a little quiet right now?", "Time alone can be restorative; only you can tell when it tips into avoidance."],
    safetyNotes: [],
  },
  {
    id: "tarot.major.10_wheel_of_fortune",
    system: "tarot",
    key: "wheel_of_fortune",
    title: "Wheel of Fortune",
    plainMeaning:
      "Cycles, change, and turning points. The Wheel reminds you that seasons shift, and invites you to meet what is changing with flexibility and trust in your ability to adapt.",
    strengths: ["Adaptability through change", "Trust in life's natural cycles", "Openness to new turning points"],
    growthEdges: ["An invitation to focus on your response rather than only the circumstances", "A nudge to notice what you can steer even when much feels out of your hands"],
    supportiveActions: ["journal_prompt", "values_check"],
    avoidSaying: ["Fate has already decided your future", "Bad luck is coming for you"],
    synthesisTags: ["change_release", "timing_patience"],
    confidenceNotes: ["Question to ask: Within this change, what is still mine to shape?", "Cards describe cycles, not predetermined outcomes."],
    safetyNotes: [],
  },
  {
    id: "tarot.major.11_justice",
    system: "tarot",
    key: "justice",
    title: "Justice",
    plainMeaning:
      "Fairness, honesty, and accountability. Justice invites you to weigh things clearly, act in line with your values, and seek balance between what you give and what you receive.",
    strengths: ["Fairness and clear thinking", "Honesty and accountability", "Commitment to balance and integrity"],
    growthEdges: ["An invitation to hold yourself and others to fairness without harshness", "A nudge to let compassion sit alongside clarity"],
    supportiveActions: ["values_check", "decision_clarity"],
    avoidSaying: ["You will be punished for past mistakes", "A harsh judgment is coming"],
    synthesisTags: ["decision_clarity", "boundaries"],
    confidenceNotes: ["Question to ask: What would the fairest, most honest version of this situation look like?", "This invites reflection on fairness, not a prediction of consequences."],
    safetyNotes: [],
  },
  {
    id: "tarot.major.12_hanged_man",
    system: "tarot",
    key: "the_hanged_man",
    title: "The Hanged Man",
    plainMeaning:
      "A pause that brings a new view. The Hanged Man invites you to release the urge to force progress and to see your situation from a fresh angle while you wait.",
    strengths: ["Willingness to pause and reconsider", "Fresh perspective and openness", "Patience with the in-between"],
    growthEdges: ["An invitation to find meaning in waiting rather than only frustration", "A nudge to release what you cannot control right now"],
    supportiveActions: ["journal_prompt", "nervous_system_reset"],
    avoidSaying: ["You are stuck and going nowhere", "Sacrifice is being demanded of you"],
    synthesisTags: ["timing_patience", "change_release"],
    confidenceNotes: ["Question to ask: What might I see if I let go of needing to fix this immediately?", "A pause can be useful; whether to wait is still your call."],
    safetyNotes: [],
  },
  {
    id: "tarot.major.13_death",
    system: "tarot",
    key: "death",
    title: "Death",
    plainMeaning:
      "Endings that make room for what comes next. Death is about transformation and release, the natural close of one chapter so something truer can begin. It is rarely about anything literal.",
    strengths: ["Capacity to release what no longer fits", "Openness to meaningful transformation", "Honesty about what a chapter has ended"],
    growthEdges: ["An invitation to grieve what is ending while trusting space is being made", "A nudge to let go gently rather than gripping the old shape"],
    supportiveActions: ["journal_prompt", "gratitude_reframe"],
    avoidSaying: ["This means a literal death or loss of life", "Something terrible is about to happen"],
    synthesisTags: ["change_release", "grief_processing"],
    confidenceNotes: ["Question to ask: What am I being invited to lovingly release so something new has room?", "This is about symbolic endings and renewal, never a forecast of harm."],
    safetyNotes: ["Never read as literal harm or catastrophe; this card is about transformation and release."],
  },
  {
    id: "tarot.major.14_temperance",
    system: "tarot",
    key: "temperance",
    title: "Temperance",
    plainMeaning:
      "Balance, patience, and gentle blending. Temperance invites you to find the middle path, mix opposing needs with care, and let healing happen at a steady, sustainable pace.",
    strengths: ["Balance and moderation", "Patience and steady pacing", "Skill at blending opposites into harmony"],
    growthEdges: ["An invitation to trust slow, steady progress over quick extremes", "A nudge to tend your own equilibrium, not just smooth things for others"],
    supportiveActions: ["nervous_system_reset", "values_check"],
    avoidSaying: ["You are out of control and unbalanced", "Failing to fix this now is dangerous"],
    synthesisTags: ["stress_regulation", "timing_patience"],
    confidenceNotes: ["Question to ask: Where could a more balanced, patient pace serve me better than extremes?", "This describes a helpful tendency, not a measure of how well you are doing."],
    safetyNotes: [],
  },
  {
    id: "tarot.major.15_devil",
    system: "tarot",
    key: "the_devil",
    title: "The Devil",
    plainMeaning:
      "A look at what feels binding. The Devil invites honest reflection on habits, attachments, or stories that quietly limit you, and reminds you the key to loosening them is often in your own hands.",
    strengths: ["Honesty about what holds you back", "Awareness of unhelpful patterns", "Courage to reclaim your own power"],
    growthEdges: ["An invitation to question the belief that you have no choice here", "A nudge to set a boundary with what drains you, gently and without shame"],
    supportiveActions: ["boundary_script", "values_check"],
    avoidSaying: ["You are trapped with no way out", "Evil or temptation has a hold on you"],
    synthesisTags: ["boundaries", "self_worth"],
    confidenceNotes: ["Question to ask: What story of being stuck might have more give in it than I assumed?", "Naming a pattern is reflection, not a diagnosis or a sentence."],
    safetyNotes: [],
  },
  {
    id: "tarot.major.16_tower",
    system: "tarot",
    key: "the_tower",
    title: "The Tower",
    plainMeaning:
      "A sudden moment of clarity. The Tower marks a necessary shift when something built on a shaky foundation gives way, clearing space for something more honest and sturdy to take its place.",
    strengths: ["Openness to needed change", "Honesty when something no longer holds", "Resilience and the chance for a truer rebuild"],
    growthEdges: ["An invitation to treat sudden clarity as information, not punishment", "A nudge to be tender with yourself while things rearrange"],
    supportiveActions: ["nervous_system_reset", "journal_prompt"],
    avoidSaying: ["Disaster and ruin are coming", "Everything you have will be destroyed"],
    synthesisTags: ["change_release", "stress_regulation"],
    confidenceNotes: ["Question to ask: If something shaky is giving way, what truer thing wants room to be built?", "This points to necessary change and clarity, never to catastrophe."],
    safetyNotes: ["Never read as literal harm or catastrophe; this card is about sudden clarity and necessary change."],
  },
  {
    id: "tarot.major.17_star",
    system: "tarot",
    key: "the_star",
    title: "The Star",
    plainMeaning:
      "Renewal, hope, and gentle healing. The Star invites you to soften after something hard, reconnect with what gives you faith, and let yourself be quietly replenished.",
    strengths: ["Hope and renewed faith", "Gentle healing and openness", "Calm trust in better days"],
    growthEdges: ["An invitation to let yourself rest and refill, not rush back to doing", "A nudge to believe you are worthy of the calm you long for"],
    supportiveActions: ["gratitude_reframe", "nervous_system_reset"],
    avoidSaying: ["Your hope is naive and misplaced", "Disappointment is sure to follow"],
    synthesisTags: ["rest_recovery", "self_worth"],
    confidenceNotes: ["Question to ask: What would help me feel quietly replenished right now?", "Hope here is an invitation to tend, not a promise of outcomes."],
    safetyNotes: [],
  },
  {
    id: "tarot.major.18_moon",
    system: "tarot",
    key: "the_moon",
    title: "The Moon",
    plainMeaning:
      "Working with uncertainty and feeling. The Moon invites you to be gentle with what is unclear, to let emotions and intuition speak, and to take the next step even when the whole path is not lit.",
    strengths: ["Rich intuition and imagination", "Comfort with the unknown", "Emotional depth and honesty"],
    growthEdges: ["An invitation to separate old fears from present facts", "A nudge to be patient as clarity arrives in its own time"],
    supportiveActions: ["journal_prompt", "nervous_system_reset"],
    avoidSaying: ["You are being deceived and betrayed", "Hidden danger surrounds you"],
    synthesisTags: ["stress_regulation", "timing_patience"],
    confidenceNotes: ["Question to ask: Which of my worries are about right now, and which are echoes of the past?", "Uncertainty is uncomfortable but not proof that something is wrong."],
    safetyNotes: [],
  },
  {
    id: "tarot.major.19_sun",
    system: "tarot",
    key: "the_sun",
    title: "The Sun",
    plainMeaning:
      "Warmth, clarity, and simple joy. The Sun invites you to notice what is going well, let yourself be seen, and move through the day with openness and a lighter heart.",
    strengths: ["Warmth, optimism, and vitality", "Clarity and confidence", "Ability to enjoy and share joy"],
    growthEdges: ["An invitation to receive good things without bracing for the catch", "A nudge to let yourself be seen as you are"],
    supportiveActions: ["gratitude_reframe", "journal_prompt"],
    avoidSaying: ["This happiness will not last", "You do not deserve this good feeling"],
    synthesisTags: ["self_worth", "connection_love"],
    confidenceNotes: ["Question to ask: What small good thing can I let myself fully enjoy today?", "Noticing brightness is a practice, not a guarantee every day feels this way."],
    safetyNotes: [],
  },
  {
    id: "tarot.major.20_judgement",
    system: "tarot",
    key: "judgement",
    title: "Judgement",
    plainMeaning:
      "Reflection, renewal, and a call to rise. Judgement invites you to look honestly at where you have been, forgive what needs releasing, and answer the quiet call toward who you are becoming.",
    strengths: ["Honest self-reflection", "Capacity for forgiveness and renewal", "Readiness to answer a deeper calling"],
    growthEdges: ["An invitation to review the past with compassion rather than self-criticism", "A nudge to act on the call you have been quietly hearing"],
    supportiveActions: ["journal_prompt", "values_check"],
    avoidSaying: ["You will be judged and found lacking", "Your past mistakes condemn you"],
    synthesisTags: ["change_release", "learning_growth"],
    confidenceNotes: ["Question to ask: If I looked back with kindness, what would I forgive and what would I answer?", "This is an invitation to reflect, not a verdict on your worth."],
    safetyNotes: [],
  },
  {
    id: "tarot.major.21_world",
    system: "tarot",
    key: "the_world",
    title: "The World",
    plainMeaning:
      "Completion, wholeness, and arrival. The World honors a cycle coming full circle, the integration of what you have learned, and a moment to celebrate before the next chapter opens.",
    strengths: ["Sense of completion and wholeness", "Integration of lessons learned", "Gratitude and readiness for what is next"],
    growthEdges: ["An invitation to pause and honor how far you have come", "A nudge to carry your growth forward without rushing the next beginning"],
    supportiveActions: ["gratitude_reframe", "next_step_plan"],
    avoidSaying: ["You will never reach completion", "Something is missing and always will be"],
    synthesisTags: ["change_release", "learning_growth"],
    confidenceNotes: ["Question to ask: What feels complete enough to honor before I look toward what is next?", "A sense of arrival is worth marking, even though life keeps unfolding."],
    safetyNotes: [],
  },
];
