import type { KnowledgeCard } from "./types.ts";

export const tarotArchetypeCards: KnowledgeCard[] = [
  {
    id: "tarot.major.00_fool",
    system: "tarot",
    key: "the_fool",
    title: "The Fool",
    plainMeaning:
      "A fresh beginning and a leap into the unknown. The Fool invites open-hearted curiosity, a willingness to start before you feel fully ready, and trust in the next small step.",
    strengths: ["Open-hearted curiosity and a beginner's mind", "Courage to start something new", "Freedom from old expectations"],
    growthEdges: ["A chance to pair spontaneity with a little grounding so leaps land softly", "An invitation to notice when avoidance is dressed up as adventure"],
    supportiveActions: ["next_step_plan", "journal_prompt"],
    avoidSaying: ["You are being reckless and will fall", "This warns of a foolish mistake ahead"],
    synthesisTags: ["change_release", "freedom_independence"],
    confidenceNotes: ["Question to ask: What new beginning am I being invited to trust, and what one small step feels possible?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.major.01_magician",
    system: "tarot",
    key: "the_magician",
    title: "The Magician",
    plainMeaning:
      "You already hold the tools you need. The Magician points to focused intention, resourcefulness, and turning ideas into action by aligning what you want with what you do.",
    strengths: ["Resourcefulness and creative skill", "Clear, focused intention", "Ability to turn ideas into action"],
    growthEdges: ["An invitation to make sure your words and actions match", "A nudge to use your gifts in service of something true rather than to impress"],
    supportiveActions: ["next_step_plan", "values_check"],
    avoidSaying: ["You must act now or lose your chance", "Beware manipulation surrounds you"],
    synthesisTags: ["action_initiative", "creativity"],
    confidenceNotes: ["Question to ask: What do I already have that I have been overlooking?", "This reflects a possible inner resource, not a guaranteed outcome."],
    safetyNotes: [],
  },
  {
    id: "tarot.major.02_high_priestess",
    system: "tarot",
    key: "the_high_priestess",
    title: "The High Priestess",
    plainMeaning:
      "A pause to listen inward. The High Priestess honors intuition, quiet knowing, and the wisdom that surfaces when you stop rushing and let things become clear in their own time.",
    strengths: ["Deep intuition and inner knowing", "Comfort with mystery and patience", "Capacity to listen beneath the noise"],
    growthEdges: ["An invitation to trust your quiet signals instead of overriding them", "A gentle nudge to share what you sense rather than keeping it all inside"],
    supportiveActions: ["journal_prompt", "nervous_system_reset"],
    avoidSaying: ["Secrets are being hidden from you", "Ignoring this brings misfortune"],
    synthesisTags: ["timing_patience", "rest_recovery"],
    confidenceNotes: ["Question to ask: What does my quieter, wiser self already sense that I have been talking over?", "Intuition is information to weigh, not a certainty to obey."],
    safetyNotes: [],
  },
  {
    id: "tarot.major.03_empress",
    system: "tarot",
    key: "the_empress",
    title: "The Empress",
    plainMeaning:
      "Nourishment, creativity, and care. The Empress invites you to tend what you are growing, including yourself, with warmth, abundance, and a connection to the senses and the natural world.",
    strengths: ["Nurturing warmth toward self and others", "Creative, generative energy", "Comfort, sensuality, and ease"],
    growthEdges: ["An invitation to receive care, not only give it", "A reminder that tending yourself is part of tending others"],
    supportiveActions: ["nervous_system_reset", "gratitude_reframe"],
    avoidSaying: ["You are neglecting everyone around you", "Smothering others is your flaw"],
    synthesisTags: ["nurture_care", "creativity"],
    confidenceNotes: ["Question to ask: Where could I offer myself the same care I so easily give others?", "This points to a tendency, not a fixed truth about you."],
    safetyNotes: [],
  },
  {
    id: "tarot.major.04_emperor",
    system: "tarot",
    key: "the_emperor",
    title: "The Emperor",
    plainMeaning:
      "Structure, steadiness, and grounded leadership. The Emperor invites you to build stable foundations, set clear boundaries, and bring helpful order to what feels scattered.",
    strengths: ["Grounded leadership and follow-through", "Healthy structure and stability", "Clear, fair boundaries"],
    growthEdges: ["An invitation to let structure stay flexible enough to breathe", "A nudge to lead with warmth alongside firmness"],
    supportiveActions: ["next_step_plan", "boundary_script"],
    avoidSaying: ["You are too controlling and rigid", "Surrender all authority or fail"],
    synthesisTags: ["planning_structure", "leadership"],
    confidenceNotes: ["Question to ask: Where would a little more structure actually free me up?", "Structure is a tool here, not a verdict on your character."],
    safetyNotes: [],
  },
  {
    id: "tarot.major.05_hierophant",
    system: "tarot",
    key: "the_hierophant",
    title: "The Hierophant",
    plainMeaning:
      "Tradition, mentorship, and shared meaning. The Hierophant points to learning from those who came before, finding belonging, and deciding which values you want to carry forward as your own.",
    strengths: ["Respect for wisdom and mentorship", "A sense of belonging and shared values", "Steady, principled grounding"],
    growthEdges: ["An invitation to keep what serves you and gently question what no longer fits", "A nudge to find your own voice within the inherited script"],
    supportiveActions: ["values_check", "journal_prompt"],
    avoidSaying: ["You must conform or be cast out", "Breaking tradition will doom you"],
    synthesisTags: ["learning_growth", "planning_structure"],
    confidenceNotes: ["Question to ask: Which beliefs here are truly mine, and which did I simply inherit?", "This is a reflective prompt about values, not a fixed rule to obey."],
    safetyNotes: [],
  },
  {
    id: "tarot.major.06_lovers",
    system: "tarot",
    key: "the_lovers",
    title: "The Lovers",
    plainMeaning:
      "Connection, alignment, and meaningful choice. The Lovers invites you to honor what you value in relationships and to choose, with open eyes, the path that matches your deeper truth.",
    strengths: ["Genuine connection and openness", "Values-aligned choices", "Harmony between heart and mind"],
    growthEdges: ["An invitation to choose from your values rather than from fear of missing out", "A nudge to be honest about what you actually want"],
    supportiveActions: ["decision_clarity", "relationship_repair"],
    avoidSaying: ["A wrong choice will ruin everything", "You are destined to lose this love"],
    synthesisTags: ["connection_love", "decision_clarity"],
    confidenceNotes: ["Question to ask: If I chose from my values rather than my fears, which way would I lean?", "A card can clarify a choice but cannot make it for you."],
    safetyNotes: [],
  },
  {
    id: "tarot.major.07_chariot",
    system: "tarot",
    key: "the_chariot",
    title: "The Chariot",
    plainMeaning:
      "Focused momentum and directed will. The Chariot invites you to gather your competing impulses, point them toward one goal, and move forward with steady, self-led determination.",
    strengths: ["Determination and drive", "Self-discipline and focus", "Ability to unite opposing forces toward a goal"],
    growthEdges: ["An invitation to steer with intention rather than push through exhaustion", "A nudge to check that your direction still feels right"],
    supportiveActions: ["next_step_plan", "focus_exercise"],
    avoidSaying: ["Lose control now and everything collapses", "You will be defeated if you slow down"],
    synthesisTags: ["action_initiative", "work_focus"],
    confidenceNotes: ["Question to ask: What would it look like to move forward with focus and without forcing?", "Momentum is something you can shape, not a fate that drives you."],
    safetyNotes: [],
  },
  {
    id: "tarot.major.08_strength",
    system: "tarot",
    key: "strength",
    title: "Strength",
    plainMeaning:
      "Quiet, steady courage. Strength is the gentle power of meeting big feelings with patience rather than force, trusting that softness and self-compassion are their own kind of resilience.",
    strengths: ["Gentle courage and patience", "Emotional resilience and self-compassion", "Calm in the face of intensity"],
    growthEdges: ["An invitation to be as kind to yourself as you are brave for others", "A nudge to let softness, not pressure, guide difficult moments"],
    supportiveActions: ["nervous_system_reset", "journal_prompt"],
    avoidSaying: ["You are too weak to handle this", "Only force will get you through"],
    synthesisTags: ["self_worth", "stress_regulation"],
    confidenceNotes: ["Question to ask: Where could meeting myself with gentleness be stronger than pushing harder?", "Inner strength looks different on different days, and that is okay."],
    safetyNotes: [],
  },
  {
    id: "tarot.major.09_hermit",
    system: "tarot",
    key: "the_hermit",
    title: "The Hermit",
    plainMeaning:
      "A meaningful pause for reflection. The Hermit honors solitude, slowing down, and turning inward to find your own light before stepping back out into the world.",
    strengths: ["Comfort with solitude and reflection", "Inner wisdom and self-honesty", "Willingness to slow down and listen"],
    growthEdges: ["An invitation to make space for rest without slipping into isolation", "A nudge to bring your insights back to the people who care for you"],
    supportiveActions: ["journal_prompt", "nervous_system_reset"],
    avoidSaying: ["You are doomed to be alone", "Withdrawing means you have failed"],
    synthesisTags: ["rest_recovery", "timing_patience"],
    confidenceNotes: ["Question to ask: What might become clear if I gave myself a little quiet right now?", "Time alone can be restorative; only you can tell when it tips into avoidance."],
    safetyNotes: [],
  },
  {
    id: "tarot.major.10_wheel_of_fortune",
    system: "tarot",
    key: "wheel_of_fortune",
    title: "Wheel of Fortune",
    plainMeaning:
      "Cycles, change, and turning points. The Wheel reminds you that seasons shift, and invites you to meet what is changing with flexibility and trust in your ability to adapt.",
    strengths: ["Adaptability through change", "Trust in life's natural cycles", "Openness to new turning points"],
    growthEdges: ["An invitation to focus on your response rather than only the circumstances", "A nudge to notice what you can steer even when much feels out of your hands"],
    supportiveActions: ["journal_prompt", "values_check"],
    avoidSaying: ["Fate has already decided your future", "Bad luck is coming for you"],
    synthesisTags: ["change_release", "timing_patience"],
    confidenceNotes: ["Question to ask: Within this change, what is still mine to shape?", "Cards describe cycles, not predetermined outcomes."],
    safetyNotes: [],
  },
  {
    id: "tarot.major.11_justice",
    system: "tarot",
    key: "justice",
    title: "Justice",
    plainMeaning:
      "Fairness, honesty, and accountability. Justice invites you to weigh things clearly, act in line with your values, and seek balance between what you give and what you receive.",
    strengths: ["Fairness and clear thinking", "Honesty and accountability", "Commitment to balance and integrity"],
    growthEdges: ["An invitation to hold yourself and others to fairness without harshness", "A nudge to let compassion sit alongside clarity"],
    supportiveActions: ["values_check", "decision_clarity"],
    avoidSaying: ["You will be punished for past mistakes", "A harsh judgment is coming"],
    synthesisTags: ["decision_clarity", "boundaries"],
    confidenceNotes: ["Question to ask: What would the fairest, most honest version of this situation look like?", "This invites reflection on fairness, not a prediction of consequences."],
    safetyNotes: [],
  },
  {
    id: "tarot.major.12_hanged_man",
    system: "tarot",
    key: "the_hanged_man",
    title: "The Hanged Man",
    plainMeaning:
      "A pause that brings a new view. The Hanged Man invites you to release the urge to force progress and to see your situation from a fresh angle while you wait.",
    strengths: ["Willingness to pause and reconsider", "Fresh perspective and openness", "Patience with the in-between"],
    growthEdges: ["An invitation to find meaning in waiting rather than only frustration", "A nudge to release what you cannot control right now"],
    supportiveActions: ["journal_prompt", "nervous_system_reset"],
    avoidSaying: ["You are stuck and going nowhere", "Sacrifice is being demanded of you"],
    synthesisTags: ["timing_patience", "change_release"],
    confidenceNotes: ["Question to ask: What might I see if I let go of needing to fix this immediately?", "A pause can be useful; whether to wait is still your call."],
    safetyNotes: [],
  },
  {
    id: "tarot.major.13_death",
    system: "tarot",
    key: "death",
    title: "Death",
    plainMeaning:
      "Endings that make room for what comes next. Death is about transformation and release, the natural close of one chapter so something truer can begin. It is rarely about anything literal.",
    strengths: ["Capacity to release what no longer fits", "Openness to meaningful transformation", "Honesty about what a chapter has ended"],
    growthEdges: ["An invitation to grieve what is ending while trusting space is being made", "A nudge to let go gently rather than gripping the old shape"],
    supportiveActions: ["journal_prompt", "gratitude_reframe"],
    avoidSaying: ["This means a literal death or loss of life", "Something terrible is about to happen"],
    synthesisTags: ["change_release", "grief_processing"],
    confidenceNotes: ["Question to ask: What am I being invited to lovingly release so something new has room?", "This is about symbolic endings and renewal, never a forecast of harm."],
    safetyNotes: ["Never read as literal harm or catastrophe; this card is about transformation and release."],
  },
  {
    id: "tarot.major.14_temperance",
    system: "tarot",
    key: "temperance",
    title: "Temperance",
    plainMeaning:
      "Balance, patience, and gentle blending. Temperance invites you to find the middle path, mix opposing needs with care, and let healing happen at a steady, sustainable pace.",
    strengths: ["Balance and moderation", "Patience and steady pacing", "Skill at blending opposites into harmony"],
    growthEdges: ["An invitation to trust slow, steady progress over quick extremes", "A nudge to tend your own equilibrium, not just smooth things for others"],
    supportiveActions: ["nervous_system_reset", "values_check"],
    avoidSaying: ["You are out of control and unbalanced", "Failing to fix this now is dangerous"],
    synthesisTags: ["stress_regulation", "timing_patience"],
    confidenceNotes: ["Question to ask: Where could a more balanced, patient pace serve me better than extremes?", "This describes a helpful tendency, not a measure of how well you are doing."],
    safetyNotes: [],
  },
  {
    id: "tarot.major.15_devil",
    system: "tarot",
    key: "the_devil",
    title: "The Devil",
    plainMeaning:
      "A look at what feels binding. The Devil invites honest reflection on habits, attachments, or stories that quietly limit you, and reminds you the key to loosening them is often in your own hands.",
    strengths: ["Honesty about what holds you back", "Awareness of unhelpful patterns", "Courage to reclaim your own power"],
    growthEdges: ["An invitation to question the belief that you have no choice here", "A nudge to set a boundary with what drains you, gently and without shame"],
    supportiveActions: ["boundary_script", "values_check"],
    avoidSaying: ["You are trapped with no way out", "Evil or temptation has a hold on you"],
    synthesisTags: ["boundaries", "self_worth"],
    confidenceNotes: ["Question to ask: What story of being stuck might have more give in it than I assumed?", "Naming a pattern is reflection, not a diagnosis or a sentence."],
    safetyNotes: [],
  },
  {
    id: "tarot.major.16_tower",
    system: "tarot",
    key: "the_tower",
    title: "The Tower",
    plainMeaning:
      "A sudden moment of clarity. The Tower marks a necessary shift when something built on a shaky foundation gives way, clearing space for something more honest and sturdy to take its place.",
    strengths: ["Openness to needed change", "Honesty when something no longer holds", "Resilience and the chance for a truer rebuild"],
    growthEdges: ["An invitation to treat sudden clarity as information, not punishment", "A nudge to be tender with yourself while things rearrange"],
    supportiveActions: ["nervous_system_reset", "journal_prompt"],
    avoidSaying: ["Disaster and ruin are coming", "Everything you have will be destroyed"],
    synthesisTags: ["change_release", "stress_regulation"],
    confidenceNotes: ["Question to ask: If something shaky is giving way, what truer thing wants room to be built?", "This points to necessary change and clarity, never to catastrophe."],
    safetyNotes: ["Never read as literal harm or catastrophe; this card is about sudden clarity and necessary change."],
  },
  {
    id: "tarot.major.17_star",
    system: "tarot",
    key: "the_star",
    title: "The Star",
    plainMeaning:
      "Renewal, hope, and gentle healing. The Star invites you to soften after something hard, reconnect with what gives you faith, and let yourself be quietly replenished.",
    strengths: ["Hope and renewed faith", "Gentle healing and openness", "Calm trust in better days"],
    growthEdges: ["An invitation to let yourself rest and refill, not rush back to doing", "A nudge to believe you are worthy of the calm you long for"],
    supportiveActions: ["gratitude_reframe", "nervous_system_reset"],
    avoidSaying: ["Your hope is naive and misplaced", "Disappointment is sure to follow"],
    synthesisTags: ["rest_recovery", "self_worth"],
    confidenceNotes: ["Question to ask: What would help me feel quietly replenished right now?", "Hope here is an invitation to tend, not a promise of outcomes."],
    safetyNotes: [],
  },
  {
    id: "tarot.major.18_moon",
    system: "tarot",
    key: "the_moon",
    title: "The Moon",
    plainMeaning:
      "Working with uncertainty and feeling. The Moon invites you to be gentle with what is unclear, to let emotions and intuition speak, and to take the next step even when the whole path is not lit.",
    strengths: ["Rich intuition and imagination", "Comfort with the unknown", "Emotional depth and honesty"],
    growthEdges: ["An invitation to separate old fears from present facts", "A nudge to be patient as clarity arrives in its own time"],
    supportiveActions: ["journal_prompt", "nervous_system_reset"],
    avoidSaying: ["You are being deceived and betrayed", "Hidden danger surrounds you"],
    synthesisTags: ["stress_regulation", "timing_patience"],
    confidenceNotes: ["Question to ask: Which of my worries are about right now, and which are echoes of the past?", "Uncertainty is uncomfortable but not proof that something is wrong."],
    safetyNotes: [],
  },
  {
    id: "tarot.major.19_sun",
    system: "tarot",
    key: "the_sun",
    title: "The Sun",
    plainMeaning:
      "Warmth, clarity, and simple joy. The Sun invites you to notice what is going well, let yourself be seen, and move through the day with openness and a lighter heart.",
    strengths: ["Warmth, optimism, and vitality", "Clarity and confidence", "Ability to enjoy and share joy"],
    growthEdges: ["An invitation to receive good things without bracing for the catch", "A nudge to let yourself be seen as you are"],
    supportiveActions: ["gratitude_reframe", "journal_prompt"],
    avoidSaying: ["This happiness will not last", "You do not deserve this good feeling"],
    synthesisTags: ["self_worth", "connection_love"],
    confidenceNotes: ["Question to ask: What small good thing can I let myself fully enjoy today?", "Noticing brightness is a practice, not a guarantee every day feels this way."],
    safetyNotes: [],
  },
  {
    id: "tarot.major.20_judgement",
    system: "tarot",
    key: "judgement",
    title: "Judgement",
    plainMeaning:
      "Reflection, renewal, and a call to rise. Judgement invites you to look honestly at where you have been, forgive what needs releasing, and answer the quiet call toward who you are becoming.",
    strengths: ["Honest self-reflection", "Capacity for forgiveness and renewal", "Readiness to answer a deeper calling"],
    growthEdges: ["An invitation to review the past with compassion rather than self-criticism", "A nudge to act on the call you have been quietly hearing"],
    supportiveActions: ["journal_prompt", "values_check"],
    avoidSaying: ["You will be judged and found lacking", "Your past mistakes condemn you"],
    synthesisTags: ["change_release", "learning_growth"],
    confidenceNotes: ["Question to ask: If I looked back with kindness, what would I forgive and what would I answer?", "This is an invitation to reflect, not a verdict on your worth."],
    safetyNotes: [],
  },
  {
    id: "tarot.major.21_world",
    system: "tarot",
    key: "the_world",
    title: "The World",
    plainMeaning:
      "Completion, wholeness, and arrival. The World honors a cycle coming full circle, the integration of what you have learned, and a moment to celebrate before the next chapter opens.",
    strengths: ["Sense of completion and wholeness", "Integration of lessons learned", "Gratitude and readiness for what is next"],
    growthEdges: ["An invitation to pause and honor how far you have come", "A nudge to carry your growth forward without rushing the next beginning"],
    supportiveActions: ["gratitude_reframe", "next_step_plan"],
    avoidSaying: ["You will never reach completion", "Something is missing and always will be"],
    synthesisTags: ["change_release", "learning_growth"],
    confidenceNotes: ["Question to ask: What feels complete enough to honor before I look toward what is next?", "A sense of arrival is worth marking, even though life keeps unfolding."],
    safetyNotes: [],
  },

  // ─── Minor Arcana (56) — Wands, Cups, Swords, Pentacles ──────────
  // Keys match the tarot engine's draw names ("Ace of Wands" → ace_of_wands).
{
    id: "tarot.minor.wands_ace", system: "tarot", key: "ace_of_wands", title: "Ace of Wands",
    plainMeaning: "A bright spark of inspiration or fresh desire wants to be acted on. A new creative or energetic impulse is stirring, inviting you to begin before you feel fully ready.",
    strengths: ["Raw creative spark and enthusiasm", "Courage to start something new", "A clear sense of what excites you"],
    growthEdges: ["Letting yourself act on a small flicker of interest", "Trusting energy that is still forming"],
    supportiveActions: ["next_step_plan", "journal_prompt"],
    avoidSaying: ["Success in this venture is guaranteed", "A big opportunity is about to land in your lap"],
    synthesisTags: ["action_initiative", "creativity"],
    confidenceNotes: ["Question to ask: What small spark in me wants a little oxygen right now?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.wands_two", system: "tarot", key: "two_of_wands", title: "Two of Wands",
    plainMeaning: "You hold something real in hand and feel the pull of a wider horizon. This is a moment of planning and choosing where to aim the energy you have already gathered.",
    strengths: ["Vision that reaches beyond the familiar", "Willingness to weigh options thoughtfully", "Confidence in what you have built so far"],
    growthEdges: ["Choosing a direction without needing every detail settled", "Honoring your own ambition rather than shrinking it"],
    supportiveActions: ["decision_clarity", "next_step_plan"],
    avoidSaying: ["You must take this path or regret it forever", "The right choice will be obvious and risk-free"],
    synthesisTags: ["decision_clarity", "planning_structure"],
    confidenceNotes: ["Question to ask: If I trusted my own vision, where would I point this energy?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.wands_three", system: "tarot", key: "three_of_wands", title: "Three of Wands",
    plainMeaning: "Early efforts are taking shape and beginning to move outward. A time of looking ahead with quiet optimism while your plans find their footing in the wider world.",
    strengths: ["Patience to let momentum build", "Openness to collaboration and wider reach", "Steady forward-looking hope"],
    growthEdges: ["Trusting progress you cannot fully see yet", "Welcoming help instead of carrying it all alone"],
    supportiveActions: ["next_step_plan", "values_check"],
    avoidSaying: ["Your ship is certain to come in soon", "Expansion will happen exactly as you imagine"],
    synthesisTags: ["action_initiative", "planning_structure"],
    confidenceNotes: ["Question to ask: What am I ready to send out into the world and watch unfold?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.wands_four", system: "tarot", key: "four_of_wands", title: "Four of Wands",
    plainMeaning: "A moment of stability, celebration, and belonging. The foundations are sound enough to pause and enjoy what you and your people have created together.",
    strengths: ["Capacity to celebrate and feel at home", "Strong, supportive foundations", "Gratitude for shared milestones"],
    growthEdges: ["Letting yourself rest in a good moment without bracing", "Sharing joy openly rather than downplaying it"],
    supportiveActions: ["gratitude_reframe", "nervous_system_reset"],
    avoidSaying: ["This happiness will surely last forever", "A celebration is fated to arrive on schedule"],
    synthesisTags: ["connection_love", "rest_recovery"],
    confidenceNotes: ["Question to ask: What stable, good thing in my life deserves to be celebrated today?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.wands_five", system: "tarot", key: "five_of_wands", title: "Five of Wands",
    plainMeaning: "A lively scramble of competing energies, ideas, or wills. Friction here is not a sign something is wrong; it can be the messy, useful work of finding where you stand.",
    strengths: ["Willingness to engage rather than avoid", "Energy and spirit in the mix", "Practice at holding your own among others"],
    growthEdges: ["Telling the difference between healthy challenge and needless struggle", "Channeling competitive heat into something constructive"],
    supportiveActions: ["boundary_script", "nervous_system_reset"],
    avoidSaying: ["Conflict and defeat are coming for you", "You are bound to be overpowered by others"],
    synthesisTags: ["stress_regulation", "action_initiative"],
    confidenceNotes: ["Question to ask: Where is this friction asking me to clarify what I actually want?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.wands_six", system: "tarot", key: "six_of_wands", title: "Six of Wands",
    plainMeaning: "A moment of well-earned recognition and renewed confidence. Effort has paid off enough to lift your head, feel proud, and let yourself be seen.",
    strengths: ["Confidence grounded in real effort", "Grace in receiving acknowledgment", "Leadership that lifts others too"],
    growthEdges: ["Owning a win without minimizing it", "Letting recognition feed you rather than pressure you"],
    supportiveActions: ["gratitude_reframe", "values_check"],
    avoidSaying: ["Victory is guaranteed in everything ahead", "Everyone will always admire and follow you"],
    synthesisTags: ["self_worth", "leadership"],
    confidenceNotes: ["Question to ask: What effort of mine am I ready to honor instead of brushing aside?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.wands_seven", system: "tarot", key: "seven_of_wands", title: "Seven of Wands",
    plainMeaning: "A call to stand your ground and defend what matters to you. You hold a meaningful position, and this is about steady conviction rather than proving yourself to everyone.",
    strengths: ["Courage to hold a position under pressure", "Clear sense of what is worth protecting", "Perseverance when things feel uphill"],
    growthEdges: ["Choosing which battles truly deserve your energy", "Standing firm without becoming defensive"],
    supportiveActions: ["boundary_script", "values_check"],
    avoidSaying: ["You will be attacked from every side", "You must fight everyone to keep what is yours"],
    synthesisTags: ["boundaries", "self_worth"],
    confidenceNotes: ["Question to ask: What do I value enough to stand for, even when it takes effort?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.wands_eight", system: "tarot", key: "eight_of_wands", title: "Eight of Wands",
    plainMeaning: "Energy in swift motion — things picking up speed, messages flowing, momentum gathering. A reminder to align your aim before the pace quickens.",
    strengths: ["Ability to move quickly when it counts", "Clarity of focus and direction", "Comfort with momentum and flow"],
    growthEdges: ["Pausing to aim before you launch", "Keeping pace without losing your center"],
    supportiveActions: ["next_step_plan", "focus_exercise"],
    avoidSaying: ["Everything will speed up and go your way", "News you want is certain to arrive now"],
    synthesisTags: ["action_initiative", "timing_patience"],
    confidenceNotes: ["Question to ask: If things sped up tomorrow, what do I most want to be aimed toward?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.wands_nine", system: "tarot", key: "nine_of_wands", title: "Nine of Wands",
    plainMeaning: "You have come far and feel the weariness of the journey, yet your resilience is real. This is the quiet strength of carrying on when you are nearly there.",
    strengths: ["Deep resilience and staying power", "Honesty about being tired", "Wisdom earned through experience"],
    growthEdges: ["Letting your guard down enough to rest and receive", "Trusting that being weary does not mean being weak"],
    supportiveActions: ["nervous_system_reset", "values_check"],
    avoidSaying: ["You will be let down the moment you relax", "The struggle is destined to never end"],
    synthesisTags: ["rest_recovery", "boundaries"],
    confidenceNotes: ["Question to ask: Where might I lower my shoulders and trust I am safer than I feel?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.wands_ten", system: "tarot", key: "ten_of_wands", title: "Ten of Wands",
    plainMeaning: "A full load carried with dedication — and an honest moment to notice how much you are holding. An invitation to set down what is no longer yours to carry.",
    strengths: ["Commitment and a strong work ethic", "Willingness to follow through", "Awareness of your own limits"],
    growthEdges: ["Releasing burdens that were never yours to hold", "Asking for help before you reach empty"],
    supportiveActions: ["nervous_system_reset", "boundary_script"],
    avoidSaying: ["You are doomed to carry this alone forever", "You will collapse under the weight ahead"],
    synthesisTags: ["rest_recovery", "change_release"],
    confidenceNotes: ["Question to ask: Which of these loads can I put down or hand off right now?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.wands_page", system: "tarot", key: "page_of_wands", title: "Page of Wands",
    plainMeaning: "The eager, curious spark of a beginner full of ideas and play. A free, exploratory energy that says yes to discovery before it knows where it leads.",
    strengths: ["Playful curiosity and openness", "Enthusiasm for new experiences", "Freedom from needing to know it all first"],
    growthEdges: ["Following an interest without rushing to master it", "Letting exploration be enough for now"],
    supportiveActions: ["journal_prompt", "next_step_plan"],
    avoidSaying: ["This passion is sure to become your destiny", "Your excitement guarantees a perfect outcome"],
    synthesisTags: ["creativity", "freedom_independence"],
    confidenceNotes: ["Question to ask: What would I explore if I let myself be a curious beginner again?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.wands_knight", system: "tarot", key: "knight_of_wands", title: "Knight of Wands",
    plainMeaning: "Bold, passionate forward motion — chasing what lights you up with daring and heat. A spirited energy that loves to leap, balanced best with a little aim.",
    strengths: ["Courage to pursue boldly", "Magnetic passion and drive", "Willingness to take adventurous leaps"],
    growthEdges: ["Pairing enthusiasm with follow-through", "Channeling fire without burning out"],
    supportiveActions: ["next_step_plan", "focus_exercise"],
    avoidSaying: ["This impulsive move is certain to succeed", "Your boldness means nothing can go wrong"],
    synthesisTags: ["action_initiative", "freedom_independence"],
    confidenceNotes: ["Question to ask: Where is my fire ready to move, and where could a steady aim help?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.wands_queen", system: "tarot", key: "queen_of_wands", title: "Queen of Wands",
    plainMeaning: "Warm, confident, self-assured energy that draws others in. An inner mastery of your own fire — radiant, grounded, and generous with your spark.",
    strengths: ["Self-assured warmth and charisma", "Confidence rooted in self-knowledge", "Generosity that uplifts others"],
    growthEdges: ["Tending your own flame, not only others'", "Letting confidence include your softer feelings"],
    supportiveActions: ["values_check", "gratitude_reframe"],
    avoidSaying: ["You will always be adored and never doubted", "Your charm guarantees everything you want"],
    synthesisTags: ["self_worth", "leadership"],
    confidenceNotes: ["Question to ask: What helps my inner fire feel warm and steady rather than burned out?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.wands_king", system: "tarot", key: "king_of_wands", title: "King of Wands",
    plainMeaning: "Visionary, grounded leadership of your own energy and direction. The mature ability to inspire others while steering passion toward a clear purpose.",
    strengths: ["Inspiring, purposeful leadership", "Big-picture vision with follow-through", "Confidence that empowers others"],
    growthEdges: ["Leading with others, not just out front of them", "Letting vision stay flexible as things change"],
    supportiveActions: ["next_step_plan", "values_check"],
    avoidSaying: ["Your leadership guarantees everyone will follow", "This vision is destined to come true exactly so"],
    synthesisTags: ["leadership", "action_initiative"],
    confidenceNotes: ["Question to ask: What purpose do I most want my energy and influence to serve?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.cups_ace", system: "tarot", key: "ace_of_cups", title: "Ace of Cups",
    plainMeaning: "A tender new opening of the heart — fresh feeling, compassion, or connection that wants to be received. An invitation to let yourself feel and be filled.",
    strengths: ["Emotional openness and warmth", "Capacity to give and receive love", "Fresh intuitive flow"],
    growthEdges: ["Letting yourself receive, not only pour out", "Trusting a soft feeling enough to honor it"],
    supportiveActions: ["journal_prompt", "gratitude_reframe"],
    avoidSaying: ["This promises a soulmate is coming", "Love is guaranteed now"],
    synthesisTags: ["connection_love", "nurture_care"],
    confidenceNotes: ["Question to ask: What feeling is asking to be welcomed rather than managed right now?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.cups_two", system: "tarot", key: "two_of_cups", title: "Two of Cups",
    plainMeaning: "A meeting of hearts in mutual care and respect. This is the warmth of genuine connection — partnership, friendship, or harmony built on real exchange.",
    strengths: ["Capacity for mutual, balanced connection", "Openness and emotional honesty", "Respect that flows both ways"],
    growthEdges: ["Letting closeness be reciprocal, not one-sided", "Staying open while honoring your own needs"],
    supportiveActions: ["relationship_repair", "gratitude_reframe"],
    avoidSaying: ["This person is your guaranteed soulmate", "A lasting union is certain to form now"],
    synthesisTags: ["connection_love", "communication"],
    confidenceNotes: ["Question to ask: What does real, balanced connection feel like for me?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.cups_three", system: "tarot", key: "three_of_cups", title: "Three of Cups",
    plainMeaning: "Joyful community, friendship, and shared celebration. A reminder of the nourishment found in belonging and in lifting one another up.",
    strengths: ["Warmth in friendship and community", "Ability to celebrate and be celebrated", "Joy shared rather than held alone"],
    growthEdges: ["Letting yourself lean on your circle", "Receiving support as readily as you give it"],
    supportiveActions: ["gratitude_reframe", "relationship_repair"],
    avoidSaying: ["Your friendships are destined to never change", "A celebration is fated to arrive soon"],
    synthesisTags: ["connection_love", "nurture_care"],
    confidenceNotes: ["Question to ask: Who are my people, and how might I let them closer this week?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.cups_four", system: "tarot", key: "four_of_cups", title: "Four of Cups",
    plainMeaning: "A reflective, inward pause where the usual offerings feel flat. This is not emptiness but a turning point — an invitation to notice what you may be overlooking.",
    strengths: ["Honesty about feeling uninspired", "Capacity for inward reflection", "Discernment about what truly nourishes you"],
    growthEdges: ["Staying open to a gift you have not yet noticed", "Letting contentment back in when you are ready"],
    supportiveActions: ["journal_prompt", "gratitude_reframe"],
    avoidSaying: ["You will stay stuck and dissatisfied for good", "Nothing good will be offered to you now"],
    synthesisTags: ["rest_recovery", "grief_processing"],
    confidenceNotes: ["Question to ask: What might I be overlooking while I wait for something more?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.cups_five", system: "tarot", key: "five_of_cups", title: "Five of Cups",
    plainMeaning: "A tender moment of grief or disappointment, where attention rests on what was lost. With time and care, you may notice the cups still standing beside you.",
    strengths: ["Willingness to feel grief honestly", "Depth of caring that loss reveals", "Capacity to find what remains"],
    growthEdges: ["Letting yourself mourn without rushing past it", "Gently turning to notice what is still here"],
    supportiveActions: ["journal_prompt", "nervous_system_reset"],
    avoidSaying: ["You have lost everything that mattered", "This sadness is destined to define you"],
    synthesisTags: ["grief_processing", "stress_regulation"],
    confidenceNotes: ["Question to ask: What loss deserves my tenderness, and what is still standing beside me?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: ["Never read as literal loss or misfortune; this card is about honoring grief and gently noticing what remains."],
  },
  {
    id: "tarot.minor.cups_six", system: "tarot", key: "six_of_cups", title: "Six of Cups",
    plainMeaning: "A sweet return to warmth, nostalgia, and innocence. Memory and kindness offer comfort here, inviting playfulness and the simple generosity of the heart.",
    strengths: ["Tenderness and capacity for warmth", "Healing connection to good memories", "Generosity and gentle play"],
    growthEdges: ["Honoring the past without living only there", "Bringing childlike openness into the present"],
    supportiveActions: ["gratitude_reframe", "journal_prompt"],
    avoidSaying: ["Someone from your past is fated to return", "The good old days are the only happiness you will know"],
    synthesisTags: ["nurture_care", "connection_love"],
    confidenceNotes: ["Question to ask: What gentle, nostalgic comfort might I welcome into today?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.cups_seven", system: "tarot", key: "seven_of_cups", title: "Seven of Cups",
    plainMeaning: "Many shimmering possibilities float before you, some real and some imagined. A moment to dream freely, then to ground yourself and discern what is truly nourishing.",
    strengths: ["Rich imagination and vision", "Openness to many possibilities", "Capacity to dream before deciding"],
    growthEdges: ["Telling wishful fantasy from grounded desire", "Choosing one path rather than drifting among many"],
    supportiveActions: ["decision_clarity", "values_check"],
    avoidSaying: ["The illusion you want is sure to come true", "You are doomed to choose wrong among these"],
    synthesisTags: ["decision_clarity", "creativity"],
    confidenceNotes: ["Question to ask: Of all these options, which one feels real and nourishing rather than just shiny?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.cups_eight", system: "tarot", key: "eight_of_cups", title: "Eight of Cups",
    plainMeaning: "A quiet, courageous turning away from what no longer fulfills you, toward something deeper. This is leaving with love, in search of more meaningful ground.",
    strengths: ["Courage to seek deeper meaning", "Honesty about what no longer fits", "Willingness to walk your own path"],
    growthEdges: ["Honoring what you outgrow with gratitude", "Trusting the search even before the destination is clear"],
    supportiveActions: ["values_check", "next_step_plan"],
    avoidSaying: ["You are bound to abandon everything you love", "Walking away will surely leave you alone"],
    synthesisTags: ["change_release", "freedom_independence"],
    confidenceNotes: ["Question to ask: What am I being invited to leave with love so I can seek something deeper?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.cups_nine", system: "tarot", key: "nine_of_cups", title: "Nine of Cups",
    plainMeaning: "A satisfying moment of emotional contentment and gratitude. A reminder to savor what you have cultivated and to let yourself feel genuinely pleased.",
    strengths: ["Capacity for contentment and gratitude", "Ability to savor what is good", "Emotional fullness and ease"],
    growthEdges: ["Letting satisfaction be enough without grasping for more", "Sharing your joy rather than guarding it"],
    supportiveActions: ["gratitude_reframe", "journal_prompt"],
    avoidSaying: ["Every wish you make is guaranteed to come true", "This contentment is certain to last forever"],
    synthesisTags: ["self_worth", "nurture_care"],
    confidenceNotes: ["Question to ask: What in my life right now deserves a moment of honest savoring?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.cups_ten", system: "tarot", key: "ten_of_cups", title: "Ten of Cups",
    plainMeaning: "A picture of emotional fulfillment and belonging — harmony, love, and connection shared with others. A reminder of what wholeness can feel like.",
    strengths: ["Deep sense of belonging and love", "Harmony in close relationships", "Gratitude for emotional richness"],
    growthEdges: ["Letting yourself fully receive happiness", "Tending the connections that make you whole"],
    supportiveActions: ["gratitude_reframe", "relationship_repair"],
    avoidSaying: ["Perfect family happiness is guaranteed for you", "This harmony can never be disturbed"],
    synthesisTags: ["connection_love", "nurture_care"],
    confidenceNotes: ["Question to ask: What does emotional wholeness look like for me, and where do I already feel it?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.cups_page", system: "tarot", key: "page_of_cups", title: "Page of Cups",
    plainMeaning: "A gentle, imaginative invitation to follow your feelings and intuition with curiosity. Openhearted and a little dreamy, ready to receive a tender new message.",
    strengths: ["Sensitivity and emotional curiosity", "Openness to intuition and inspiration", "Playful, tender imagination"],
    growthEdges: ["Trusting a soft inner nudge enough to follow it", "Letting yourself feel without judging the feeling"],
    supportiveActions: ["journal_prompt", "gratitude_reframe"],
    avoidSaying: ["A love message is certain to arrive soon", "Your daydreams are guaranteed to come true"],
    synthesisTags: ["creativity", "connection_love"],
    confidenceNotes: ["Question to ask: What is my intuition whispering that I have been too busy to hear?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.cups_knight", system: "tarot", key: "knight_of_cups", title: "Knight of Cups",
    plainMeaning: "A romantic, heart-led pursuit of beauty, meaning, or connection. This is following feeling with grace — offering your heart while staying grounded in what is real.",
    strengths: ["Romantic, heartfelt sincerity", "Pursuit of beauty and meaning", "Willingness to lead with feeling"],
    growthEdges: ["Pairing idealism with steady follow-through", "Telling true devotion from fleeting infatuation"],
    supportiveActions: ["values_check", "relationship_repair"],
    avoidSaying: ["A romantic offer is certain to sweep you away", "Following your heart guarantees a happy ending"],
    synthesisTags: ["connection_love", "creativity"],
    confidenceNotes: ["Question to ask: What is my heart moving toward, and is it grounded in something real?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.cups_queen", system: "tarot", key: "queen_of_cups", title: "Queen of Cups",
    plainMeaning: "Deep emotional wisdom, compassion, and intuitive attunement. The inner mastery of feeling — able to hold your own depths and care for others with steady tenderness.",
    strengths: ["Compassion and emotional depth", "Strong, trustworthy intuition", "Ability to hold feelings with grace"],
    growthEdges: ["Caring for others without losing your own center", "Honoring your needs as much as everyone else's"],
    supportiveActions: ["nervous_system_reset", "values_check"],
    avoidSaying: ["You will always sense exactly what others feel", "Your empathy guarantees no one will hurt you"],
    synthesisTags: ["nurture_care", "stress_regulation"],
    confidenceNotes: ["Question to ask: How can I offer myself the same compassion I so easily give others?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.cups_king", system: "tarot", key: "king_of_cups", title: "King of Cups",
    plainMeaning: "Mature emotional steadiness — feeling deeply while staying calm and grounded. The art of holding strong emotion with balance and offering others a safe harbor.",
    strengths: ["Emotional balance under pressure", "Compassion paired with steadiness", "Calm presence others can lean on"],
    growthEdges: ["Letting yourself feel rather than only managing feelings", "Staying open even while staying steady"],
    supportiveActions: ["nervous_system_reset", "values_check"],
    avoidSaying: ["You will always stay perfectly calm no matter what", "Your composure guarantees nothing will shake you"],
    synthesisTags: ["stress_regulation", "leadership"],
    confidenceNotes: ["Question to ask: Where can I let my feelings move through me while staying grounded?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.swords_ace", system: "tarot", key: "ace_of_swords", title: "Ace of Swords",
    plainMeaning: "A sudden flash of clarity, truth, or fresh understanding cutting through fog. A clear new thought or insight wants to be named and acted on with honesty.",
    strengths: ["Mental clarity and sharp insight", "Courage to name the truth", "A fresh, focused perspective"],
    growthEdges: ["Speaking your truth with kindness as well as clarity", "Letting a clear thought guide action, not just analysis"],
    supportiveActions: ["journal_prompt", "decision_clarity"],
    avoidSaying: ["This insight guarantees you will win the argument", "The harsh truth ahead will hurt you"],
    synthesisTags: ["communication", "decision_clarity"],
    confidenceNotes: ["Question to ask: What truth is becoming clear that I am ready to honor?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.swords_two", system: "tarot", key: "two_of_swords", title: "Two of Swords",
    plainMeaning: "A careful pause at a crossroads, weighing two paths with eyes half-closed. This is the quiet before a choice — an invitation to lower the blindfold and feel as well as think.",
    strengths: ["Thoughtful, fair-minded weighing", "Ability to hold tension without rushing", "Respect for a decision's complexity"],
    growthEdges: ["Letting your feelings inform the choice, not only logic", "Gently moving toward a decision rather than freezing"],
    supportiveActions: ["decision_clarity", "journal_prompt"],
    avoidSaying: ["You are destined to choose the wrong path", "Refusing to decide will ruin everything"],
    synthesisTags: ["decision_clarity", "stress_regulation"],
    confidenceNotes: ["Question to ask: What might I see if I gently lowered the blindfold and let myself feel?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.swords_three", system: "tarot", key: "three_of_swords", title: "Three of Swords",
    plainMeaning: "An honest acknowledgment of heartache or painful truth. Naming the hurt is part of how it begins to heal, and clarity here makes room for tenderness.",
    strengths: ["Honesty about painful feelings", "Courage to face difficult truth", "Capacity to begin healing through naming"],
    growthEdges: ["Letting grief move through rather than holding it in", "Treating yourself gently while you hurt"],
    supportiveActions: ["journal_prompt", "nervous_system_reset"],
    avoidSaying: ["Heartbreak is coming for you", "This pain will never heal"],
    synthesisTags: ["grief_processing", "stress_regulation"],
    confidenceNotes: ["Question to ask: What hurt is asking to be named gently so it can begin to ease?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: ["Never read as literal heartbreak or betrayal to come; this card is about honoring pain that is present and beginning to heal."],
  },
  {
    id: "tarot.minor.swords_four", system: "tarot", key: "four_of_swords", title: "Four of Swords",
    plainMeaning: "A needed pause for rest, stillness, and mental recovery. After effort or strain, this is permission to lay your thoughts down and let your mind be quiet.",
    strengths: ["Wisdom to rest before pushing on", "Capacity for stillness and recovery", "Honoring the mind's need for quiet"],
    growthEdges: ["Allowing rest without guilt", "Trusting that pausing is part of progress"],
    supportiveActions: ["nervous_system_reset", "focus_exercise"],
    avoidSaying: ["You will fall behind if you stop now", "Rest will surely cost you what you have built"],
    synthesisTags: ["rest_recovery", "stress_regulation"],
    confidenceNotes: ["Question to ask: What would it feel like to give my mind genuine permission to rest?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.swords_five", system: "tarot", key: "five_of_swords", title: "Five of Swords",
    plainMeaning: "A moment to look honestly at conflict and what winning truly costs. This card invites reflection on which battles serve you and where peace matters more than being right.",
    strengths: ["Honesty about the cost of conflict", "Discernment about which battles matter", "Willingness to choose peace over pride"],
    growthEdges: ["Letting go of needing to be right", "Repairing what tension has strained"],
    supportiveActions: ["relationship_repair", "values_check"],
    avoidSaying: ["You will be defeated and humiliated", "Conflict and loss are coming your way"],
    synthesisTags: ["change_release", "boundaries"],
    confidenceNotes: ["Question to ask: In this tension, what matters more to me than being right?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.swords_six", system: "tarot", key: "six_of_swords", title: "Six of Swords",
    plainMeaning: "A gentle passage toward calmer waters, leaving turbulence behind. Movement away from what was hard, carrying what you have learned toward steadier ground.",
    strengths: ["Willingness to move toward calmer ground", "Resilience carried from hard times", "Trust in gradual, steady recovery"],
    growthEdges: ["Letting the transition take the time it needs", "Accepting help as you cross into calmer waters"],
    supportiveActions: ["next_step_plan", "nervous_system_reset"],
    avoidSaying: ["You are destined to flee your troubles forever", "Smooth sailing is guaranteed from here on"],
    synthesisTags: ["change_release", "stress_regulation"],
    confidenceNotes: ["Question to ask: What calmer shore am I moving toward, and what am I ready to leave behind?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.swords_seven", system: "tarot", key: "seven_of_swords", title: "Seven of Swords",
    plainMeaning: "An invitation to be honest with yourself about strategy, independence, and where you may be hiding something. A nudge toward integrity and a smarter, clearer approach.",
    strengths: ["Cleverness and strategic thinking", "Capacity for self-reliance", "Willingness to look at hidden motives honestly"],
    growthEdges: ["Choosing honesty over shortcuts that cost trust", "Noticing where you might be avoiding the direct path"],
    supportiveActions: ["values_check", "journal_prompt"],
    avoidSaying: ["Someone is certainly deceiving you", "You are bound to be betrayed or robbed"],
    synthesisTags: ["decision_clarity", "boundaries"],
    confidenceNotes: ["Question to ask: Where might more honesty, with myself or others, actually serve me?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.swords_eight", system: "tarot", key: "eight_of_swords", title: "Eight of Swords",
    plainMeaning: "A feeling of being stuck or trapped by anxious thoughts. The restriction is often more in the mind than the world, and the first step is simply seeing that.",
    strengths: ["Capacity to recognize a mental trap", "Inner resourcefulness even when stuck", "Readiness to question limiting thoughts"],
    growthEdges: ["Loosening the stories that say you cannot move", "Reaching for support instead of facing it alone"],
    supportiveActions: ["nervous_system_reset", "journal_prompt"],
    avoidSaying: ["You are truly trapped with no way out", "Helplessness is your fate now"],
    synthesisTags: ["stress_regulation", "change_release"],
    confidenceNotes: ["Question to ask: Which of these limits are real, and which are stories I can question?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: ["Never read as literal entrapment or doom; this card is about anxious thoughts that can loosen once seen clearly."],
  },
  {
    id: "tarot.minor.swords_nine", system: "tarot", key: "nine_of_swords", title: "Nine of Swords",
    plainMeaning: "The heavy weight of worry, often loudest in the quiet of night. These fears feel large in the dark, yet daylight and support can return them to their true size.",
    strengths: ["Honesty about fear and worry", "Courage to face anxious thoughts", "Capacity to seek comfort and perspective"],
    growthEdges: ["Letting worries be witnessed instead of hidden", "Gently testing whether a fear matches reality"],
    supportiveActions: ["nervous_system_reset", "journal_prompt"],
    avoidSaying: ["Your worst fears are sure to come true", "This dread is a warning of disaster ahead"],
    synthesisTags: ["stress_regulation", "grief_processing"],
    confidenceNotes: ["Question to ask: What fear feels huge at night that I could examine gently in daylight?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: ["Never read as a prediction of catastrophe; this card is about anxiety and worry, which often shrink with care and perspective."],
  },
  {
    id: "tarot.minor.swords_ten", system: "tarot", key: "ten_of_swords", title: "Ten of Swords",
    plainMeaning: "The low point of an exhausting mental cycle — and, with it, the relief that the worst is behind you. A hard chapter ending, with dawn already on its way.",
    strengths: ["Honesty that a cycle has run its course", "Resilience found at the bottom", "Readiness for a fresh, lighter start"],
    growthEdges: ["Letting an overworked storyline finally rest", "Receiving support instead of carrying it alone"],
    supportiveActions: ["nervous_system_reset", "journal_prompt"],
    avoidSaying: ["Betrayal or ruin is coming for you", "This is the end and there's no recovery"],
    synthesisTags: ["change_release", "stress_regulation"],
    confidenceNotes: ["Question to ask: What tired story am I ready to let end so something lighter can begin?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: ["Never read as literal harm or catastrophe; this card is about an ending and the relief that follows."],
  },
  {
    id: "tarot.minor.swords_page", system: "tarot", key: "page_of_swords", title: "Page of Swords",
    plainMeaning: "A curious, sharp-minded eagerness to learn, question, and understand. Quick and alert, ready to ask honest questions and chase ideas with fresh energy.",
    strengths: ["Keen curiosity and quick thinking", "Eagerness to learn and ask questions", "Alert, honest mental energy"],
    growthEdges: ["Pairing quick words with patience and tact", "Listening as much as you analyze"],
    supportiveActions: ["journal_prompt", "focus_exercise"],
    avoidSaying: ["Your sharp words are certain to win every debate", "Watch out, someone is spying on you"],
    synthesisTags: ["communication", "learning_growth"],
    confidenceNotes: ["Question to ask: What am I genuinely curious to understand more deeply right now?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.swords_knight", system: "tarot", key: "knight_of_swords", title: "Knight of Swords",
    plainMeaning: "Fast, focused mental drive — charging toward an idea or truth with conviction. Bold and direct, best paired with a pause to consider the people in the path.",
    strengths: ["Decisive, focused determination", "Courage to pursue truth directly", "Quick, confident thinking"],
    growthEdges: ["Slowing enough to consider impact on others", "Letting directness include some gentleness"],
    supportiveActions: ["focus_exercise", "decision_clarity"],
    avoidSaying: ["Your charge ahead is guaranteed to succeed", "Rushing in means nothing can go wrong"],
    synthesisTags: ["communication", "action_initiative"],
    confidenceNotes: ["Question to ask: Where is my mind racing ahead, and would a brief pause serve me?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.swords_queen", system: "tarot", key: "queen_of_swords", title: "Queen of Swords",
    plainMeaning: "Clear, honest perception paired with compassion learned through experience. The inner mastery of the mind — direct, fair, and able to speak truth with kindness.",
    strengths: ["Clarity and honest perception", "Independence and fair judgment", "Truth-telling tempered by compassion"],
    growthEdges: ["Letting clarity stay warm, not just sharp", "Allowing softness alongside your strength"],
    supportiveActions: ["boundary_script", "values_check"],
    avoidSaying: ["You will always see through everyone perfectly", "Your sharpness guarantees no one can fool you"],
    synthesisTags: ["communication", "boundaries"],
    confidenceNotes: ["Question to ask: How can I speak my truth clearly and kindly at the same time?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.swords_king", system: "tarot", key: "king_of_swords", title: "King of Swords",
    plainMeaning: "Grounded mental authority — clear judgment, fairness, and principled thinking. The mature ability to lead with reason while staying connected to your values.",
    strengths: ["Clear, fair-minded judgment", "Principled, ethical leadership", "Ability to think with calm authority"],
    growthEdges: ["Letting logic make room for feeling", "Leading with reason and warmth together"],
    supportiveActions: ["decision_clarity", "values_check"],
    avoidSaying: ["Your reasoning guarantees you are always right", "Pure logic will never lead you astray"],
    synthesisTags: ["decision_clarity", "leadership"],
    confidenceNotes: ["Question to ask: Where can clear reasoning and my deeper values guide me together?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.pentacles_ace", system: "tarot", key: "ace_of_pentacles", title: "Ace of Pentacles",
    plainMeaning: "A grounded new beginning in the practical world — a seed of stability, work, or wellbeing that wants nurturing. A tangible opportunity to build something real.",
    strengths: ["Practical, grounded potential", "Readiness to build something solid", "Awareness of real, tangible resources"],
    growthEdges: ["Tending a small beginning with patience", "Trusting steady effort over instant results"],
    supportiveActions: ["next_step_plan", "values_check"],
    avoidSaying: ["Wealth or success is guaranteed to arrive", "This opportunity is destined to make you secure"],
    synthesisTags: ["planning_structure", "work_focus"],
    confidenceNotes: ["Question to ask: What small, practical seed am I ready to plant and tend?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.pentacles_two", system: "tarot", key: "two_of_pentacles", title: "Two of Pentacles",
    plainMeaning: "A nimble balancing of demands, priorities, and resources. This is the dance of juggling life's many parts — best done with flexibility and a light touch.",
    strengths: ["Adaptability and flexible focus", "Skill at balancing competing demands", "Resourcefulness under shifting conditions"],
    growthEdges: ["Setting down a ball that does not need juggling", "Finding ease within the balancing act"],
    supportiveActions: ["next_step_plan", "nervous_system_reset"],
    avoidSaying: ["You will surely drop everything you are holding", "Financial trouble is certain to strike"],
    synthesisTags: ["planning_structure", "stress_regulation"],
    confidenceNotes: ["Question to ask: What am I juggling, and is there anything I can gently set down?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.pentacles_three", system: "tarot", key: "three_of_pentacles", title: "Three of Pentacles",
    plainMeaning: "Skill meeting collaboration as something is built together. A reminder that your contribution matters and that good work grows through shared effort and learning.",
    strengths: ["Skillful, dedicated craftsmanship", "Openness to collaboration", "Pride in contributing your part"],
    growthEdges: ["Welcoming feedback as part of growth", "Trusting others to share the load"],
    supportiveActions: ["next_step_plan", "values_check"],
    avoidSaying: ["Your project is guaranteed to be praised", "Recognition is fated to come from this work"],
    synthesisTags: ["work_focus", "learning_growth"],
    confidenceNotes: ["Question to ask: Where might collaboration strengthen what I am trying to build?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.pentacles_four", system: "tarot", key: "four_of_pentacles", title: "Four of Pentacles",
    plainMeaning: "A focus on security and holding on to what you have. An honest moment to notice the difference between healthy stability and gripping too tightly out of fear.",
    strengths: ["Care for stability and security", "Awareness of what you value", "Capacity to protect your resources"],
    growthEdges: ["Loosening a grip held out of fear", "Allowing generosity and flow alongside saving"],
    supportiveActions: ["values_check", "journal_prompt"],
    avoidSaying: ["You are destined to lose what you cling to", "Holding on guarantees lasting safety"],
    synthesisTags: ["self_worth", "boundaries"],
    confidenceNotes: ["Question to ask: Where am I holding on for safety, and where might I loosen my grip?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.pentacles_five", system: "tarot", key: "five_of_pentacles", title: "Five of Pentacles",
    plainMeaning: "A tender moment of feeling left out in the cold — worry about lack or not having enough. A gentle reminder that support and warmth may be nearer than they seem.",
    strengths: ["Honesty about hardship or worry", "Resilience in lean times", "Capacity to reach for support"],
    growthEdges: ["Noticing the help that is within reach", "Letting yourself receive rather than struggle alone"],
    supportiveActions: ["nervous_system_reset", "values_check"],
    avoidSaying: ["You are bound for poverty and isolation", "Hard times are certain to overwhelm you"],
    synthesisTags: ["stress_regulation", "self_worth"],
    confidenceNotes: ["Question to ask: What support or warmth might be closer than it feels right now?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: ["Never read as a prediction of hardship or loss; this card is about a feeling of lack and the support that is often nearer than it seems."],
  },
  {
    id: "tarot.minor.pentacles_six", system: "tarot", key: "six_of_pentacles", title: "Six of Pentacles",
    plainMeaning: "A flow of giving and receiving, generosity and fairness. A reminder to notice how resources move in your life and to keep that exchange balanced and kind.",
    strengths: ["Generosity and fairness", "Awareness of give-and-take", "Willingness to both offer and accept help"],
    growthEdges: ["Letting yourself receive, not only give", "Keeping generosity balanced rather than depleting"],
    supportiveActions: ["gratitude_reframe", "values_check"],
    avoidSaying: ["A gift or windfall is guaranteed to come", "You will always be the one who gives"],
    synthesisTags: ["nurture_care", "self_worth"],
    confidenceNotes: ["Question to ask: Is the flow of giving and receiving in my life balanced right now?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.pentacles_seven", system: "tarot", key: "seven_of_pentacles", title: "Seven of Pentacles",
    plainMeaning: "A thoughtful pause to assess what you have grown so far. Patience and reflection here — a chance to decide where your continued effort is best invested.",
    strengths: ["Patience with slow, real growth", "Capacity to step back and assess", "Wisdom about where to invest effort"],
    growthEdges: ["Trusting growth that is still unfolding", "Letting go of effort that is no longer bearing fruit"],
    supportiveActions: ["values_check", "next_step_plan"],
    avoidSaying: ["Your hard work is guaranteed to pay off big", "Your efforts are destined to come to nothing"],
    synthesisTags: ["timing_patience", "work_focus"],
    confidenceNotes: ["Question to ask: Looking at what I've grown, where is my effort best invested next?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.pentacles_eight", system: "tarot", key: "eight_of_pentacles", title: "Eight of Pentacles",
    plainMeaning: "Devoted, focused effort in honing a skill or craft. The quiet satisfaction of steady practice and care, where mastery grows one patient step at a time.",
    strengths: ["Dedication and focused practice", "Care for quality and craft", "Patience to improve step by step"],
    growthEdges: ["Honoring progress without demanding perfection", "Letting effort feel meaningful, not just endless"],
    supportiveActions: ["focus_exercise", "next_step_plan"],
    avoidSaying: ["This work is certain to make you an expert", "Your diligence guarantees the reward you want"],
    synthesisTags: ["work_focus", "learning_growth"],
    confidenceNotes: ["Question to ask: What skill is asking for my patient, focused care right now?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.pentacles_nine", system: "tarot", key: "nine_of_pentacles", title: "Nine of Pentacles",
    plainMeaning: "A moment of self-made comfort, independence, and earned ease. A reminder to enjoy the fruits of your own effort and to savor what you have cultivated alone.",
    strengths: ["Self-reliance and earned independence", "Capacity to enjoy your own efforts", "Refined appreciation of comfort"],
    growthEdges: ["Savoring success without over-working for more", "Welcoming connection alongside your independence"],
    supportiveActions: ["gratitude_reframe", "values_check"],
    avoidSaying: ["Lasting wealth and luxury are guaranteed now", "Your independence means you will never need anyone"],
    synthesisTags: ["self_worth", "freedom_independence"],
    confidenceNotes: ["Question to ask: What fruit of my own effort can I pause to genuinely enjoy?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.pentacles_ten", system: "tarot", key: "ten_of_pentacles", title: "Ten of Pentacles",
    plainMeaning: "A sense of lasting stability, legacy, and belonging — the richness of foundations built over time. A reminder of the security found in roots, family, and home.",
    strengths: ["Stability built to last", "Connection to roots and legacy", "Gratitude for enduring foundations"],
    growthEdges: ["Honoring tradition while staying open to change", "Letting wealth include relationships, not only things"],
    supportiveActions: ["gratitude_reframe", "values_check"],
    avoidSaying: ["Generational wealth is guaranteed for you", "Your security can never be disturbed"],
    synthesisTags: ["planning_structure", "self_worth"],
    confidenceNotes: ["Question to ask: What lasting foundation in my life am I grateful to stand on?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.pentacles_page", system: "tarot", key: "page_of_pentacles", title: "Page of Pentacles",
    plainMeaning: "A studious, grounded eagerness to learn something practical and build it for real. Curious and patient, ready to turn a fresh idea into steady, tangible effort.",
    strengths: ["Practical curiosity and focus", "Eagerness to learn and apply", "Patience to start something real"],
    growthEdges: ["Letting yourself begin before you feel expert", "Turning study into small, concrete steps"],
    supportiveActions: ["next_step_plan", "focus_exercise"],
    avoidSaying: ["This study is certain to make you wealthy", "Your plans guarantee a secure future"],
    synthesisTags: ["learning_growth", "planning_structure"],
    confidenceNotes: ["Question to ask: What practical thing am I curious to learn and ready to begin?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.pentacles_knight", system: "tarot", key: "knight_of_pentacles", title: "Knight of Pentacles",
    plainMeaning: "Steady, reliable, methodical progress toward a real goal. Not flashy but dependable — the quiet power of consistent effort and follow-through over time.",
    strengths: ["Reliability and consistency", "Patience and thorough follow-through", "Dependability others can count on"],
    growthEdges: ["Letting in some spontaneity and ease", "Trusting that slow and steady is still moving"],
    supportiveActions: ["next_step_plan", "focus_exercise"],
    avoidSaying: ["Your steady effort is guaranteed to win out", "Hard work means nothing can go wrong"],
    synthesisTags: ["work_focus", "timing_patience"],
    confidenceNotes: ["Question to ask: Where is steady, patient effort serving me, and where might I lighten up?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.pentacles_queen", system: "tarot", key: "queen_of_pentacles", title: "Queen of Pentacles",
    plainMeaning: "Warm, practical nurturing — caring for self, others, and home with grounded generosity. The inner mastery of tending the material world while staying soft and whole.",
    strengths: ["Practical, nurturing care", "Groundedness and resourcefulness", "Ability to nourish self and others"],
    growthEdges: ["Tending yourself as well as everyone else", "Letting care include rest, not only doing"],
    supportiveActions: ["nervous_system_reset", "values_check"],
    avoidSaying: ["You will always provide for everyone perfectly", "Your care guarantees nothing will go lacking"],
    synthesisTags: ["nurture_care", "self_worth"],
    confidenceNotes: ["Question to ask: How can I offer myself the same grounded care I give to others?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
  {
    id: "tarot.minor.pentacles_king", system: "tarot", key: "king_of_pentacles", title: "King of Pentacles",
    plainMeaning: "Grounded mastery of the practical world — stability, abundance, and steady stewardship. The mature ability to build, sustain, and share security generously.",
    strengths: ["Steady, capable stewardship", "Abundance built through patience", "Generosity grounded in security"],
    growthEdges: ["Letting success leave room for joy and ease", "Sharing abundance rather than only guarding it"],
    supportiveActions: ["values_check", "next_step_plan"],
    avoidSaying: ["Your wealth and success are guaranteed to grow", "Material security means nothing can shake you"],
    synthesisTags: ["planning_structure", "leadership"],
    confidenceNotes: ["Question to ask: What does true, grounded abundance mean to me beyond what I own?", "A card is a mirror for reflection, not a forecast of what will happen."],
    safetyNotes: [],
  },
];
