import type { KnowledgeCard } from "./types.ts";

/**
 * Vedic (sidereal / Jyotish) cards — Soluna-owned, original reflective interpretation.
 *
 * Selected ONLY from a real, provider-backed Vedic chart (see engines/vedic.ts).
 * This is a DISTINCT tradition from the Western (tropical) layer — its signs are
 * intentionally different. The defining depth here is the 27 nakshatras (lunar
 * mansions); the Moon's nakshatra is the heart of a Vedic reading. Everything is a
 * reflective lens for self-insight and entertainment — never fixed fate, and never
 * used for caste, marriage-fitness, health, legal, financial, or destiny verdicts.
 *
 * Card keys: `nak_<name>` (e.g. nak_ashwini), plus a few foundational cards.
 */

const NAK_NOTE = "Vedic (sidereal) astrology is a reflective lens for self-insight, not fixed fate.";
const MOON_NOTE = "Your Moon's nakshatra is the heart of a Vedic reading — offered as a mirror, not a verdict.";

export const vedicCards: KnowledgeCard[] = [
  // ── Foundational ──────────────────────────────────────────────────
  {
    id: "vedic.core", system: "vedic", key: "vedic_core", title: "Your Vedic (Sidereal) Chart",
    plainMeaning: "Vedic astrology reads the sky against the fixed stars, so its signs sit roughly a sign earlier than your Western chart — on purpose. It's a separate Eastern lens, centered on the Moon and its nakshatra (lunar mansion).",
    strengths: ["A second, independent lens on your nature", "Emphasis on the inner/emotional Moon", "Rich symbolic depth via the nakshatras"],
    growthEdges: ["Holding two zodiac frames without forcing them to match", "Letting the contrast spark insight rather than confusion"],
    supportiveActions: ["journal_prompt", "values_check"],
    avoidSaying: ["Your Vedic chart overrides your Western one", "This is your true, fixed destiny"],
    synthesisTags: ["learning_growth"],
    confidenceNotes: [NAK_NOTE],
    safetyNotes: ["Never used for caste, marriage-fitness, longevity, or destiny verdicts."],
  },
  {
    id: "vedic.sade_sati.active", system: "vedic", key: "sade_sati_active", title: "Sade Sati — Saturn's Long Season",
    plainMeaning: "Saturn is moving through the stretch around your natal Moon — a roughly seven-and-a-half-year season Vedic astrology associates with maturing, slowing down, and getting honest about what's real. Often demanding, often clarifying.",
    strengths: ["A season that builds genuine resilience", "Clarity about what (and who) actually matters", "Hard-won maturity and self-reliance"],
    growthEdges: ["Pacing yourself and resting rather than pushing", "Letting go of what's already complete"],
    supportiveActions: ["nervous_system_reset", "values_check", "next_step_plan"],
    avoidSaying: ["Sade Sati will ruin these years", "Saturn is punishing you"],
    synthesisTags: ["change_release", "rest_recovery"],
    confidenceNotes: [NAK_NOTE, "Transit timing is approximate and reflective, never a prediction of events."],
    safetyNotes: ["Not a forecast of misfortune, illness, or loss."],
  },
  {
    id: "vedic.rahu", system: "vedic", key: "rahu_axis", title: "Rahu — The Hungry North Node",
    plainMeaning: "Rahu marks where you're reaching for something unfamiliar and magnetic this lifetime — the area of big appetite, ambition, and learning by diving in. Exciting, but easy to overdo before you find your footing.",
    strengths: ["Boldness to pursue the unfamiliar", "Magnetic drive and ambition", "Capacity to grow fast through experience"],
    growthEdges: ["Wanting more without losing yourself in the chase", "Grounding excitement in something steady"],
    supportiveActions: ["values_check", "next_step_plan"],
    avoidSaying: ["Rahu will bring disaster", "Your desires are cursed"],
    synthesisTags: ["change_release", "freedom_independence"],
    confidenceNotes: [NAK_NOTE],
    safetyNotes: [],
  },
  {
    id: "vedic.ketu", system: "vedic", key: "ketu_axis", title: "Ketu — The Releasing South Node",
    plainMeaning: "Ketu marks where you already carry deep, almost effortless mastery — and where you're invited to hold more lightly, even let go. The area of detachment, intuition, and quiet completion.",
    strengths: ["Innate skill that needs little effort", "Strong intuition and inner knowing", "Ease with letting go and simplifying"],
    growthEdges: ["Not dismissing your own gifts as 'nothing special'", "Releasing what's finished without guilt"],
    supportiveActions: ["journal_prompt", "gratitude_reframe"],
    avoidSaying: ["Ketu means loss is coming", "You are meant to lose this"],
    synthesisTags: ["change_release", "rest_recovery"],
    confidenceNotes: [NAK_NOTE],
    safetyNotes: [],
  },

  // ── The 27 Nakshatras (Moon's lunar mansion) ──────────────────────
  {
    id: "vedic.nak.ashwini", system: "vedic", key: "nak_ashwini", title: "Moon in Ashwini",
    plainMeaning: "A fresh-start, fast-moving temperament — pioneering, quick to act, and drawn to healing or helping. You tend to begin things others hesitate over, with youthful, hopeful energy.",
    strengths: ["Initiative and speed", "A healing, helpful instinct", "Fresh, hopeful outlook"],
    growthEdges: ["Finishing what you start before the next spark", "Pausing long enough to aim"],
    supportiveActions: ["next_step_plan", "focus_exercise"],
    avoidSaying: ["You will always rush and fail", "Your impatience is a flaw"],
    synthesisTags: ["action_initiative", "change_release"],
    confidenceNotes: [MOON_NOTE, NAK_NOTE], safetyNotes: [],
  },
  {
    id: "vedic.nak.bharani", system: "vedic", key: "nak_bharani", title: "Moon in Bharani",
    plainMeaning: "An intense, holding temperament — capable of carrying, transforming, and seeing things through difficult passages. You tend to feel deeply and bear what others can't, with quiet strength.",
    strengths: ["Endurance through intensity", "Creative, transformative energy", "Loyalty and depth"],
    growthEdges: ["Setting limits before you're overloaded", "Releasing what no longer needs carrying"],
    supportiveActions: ["boundary_script", "nervous_system_reset"],
    avoidSaying: ["You are doomed to struggle", "Your intensity will destroy you"],
    synthesisTags: ["change_release", "boundaries"],
    confidenceNotes: [MOON_NOTE, NAK_NOTE], safetyNotes: [],
  },
  {
    id: "vedic.nak.krittika", system: "vedic", key: "nak_krittika", title: "Moon in Krittika",
    plainMeaning: "A sharp, purifying temperament — honest, focused, and able to cut through to what's true. You tend to see clearly and say it plainly, with a determined, refining edge.",
    strengths: ["Clarity and honesty", "Focused determination", "A refining, improving instinct"],
    growthEdges: ["Softening sharpness into warmth when it lands hard", "Letting 'good enough' be enough sometimes"],
    supportiveActions: ["decision_clarity", "values_check"],
    avoidSaying: ["You are too harsh to be loved", "Your bluntness ruins everything"],
    synthesisTags: ["decision_clarity", "action_initiative"],
    confidenceNotes: [MOON_NOTE, NAK_NOTE], safetyNotes: [],
  },
  {
    id: "vedic.nak.rohini", system: "vedic", key: "nak_rohini", title: "Moon in Rohini",
    plainMeaning: "A magnetic, growth-loving temperament — sensual, creative, and drawn to beauty and comfort. You tend to make things (and people) flourish, with natural charm and steadiness.",
    strengths: ["Warm magnetism", "Creative, nurturing growth", "An eye for beauty and comfort"],
    growthEdges: ["Loosening attachment to comfort or appearances", "Sharing the spotlight you naturally attract"],
    supportiveActions: ["gratitude_reframe", "values_check"],
    avoidSaying: ["You are vain and materialistic", "Your need for beauty is shallow"],
    synthesisTags: ["creativity", "connection_love"],
    confidenceNotes: [MOON_NOTE, NAK_NOTE], safetyNotes: [],
  },
  {
    id: "vedic.nak.mrigashira", system: "vedic", key: "nak_mrigashira", title: "Moon in Mrigashira",
    plainMeaning: "A seeking, curious temperament — gentle, restless, and always searching for something more. You tend to explore, question, and follow your curiosity wherever it leads.",
    strengths: ["Curiosity and openness", "Gentle, approachable nature", "A searcher's adaptability"],
    growthEdges: ["Settling into what you find rather than always seeking", "Trusting that you have enough"],
    supportiveActions: ["journal_prompt", "focus_exercise"],
    avoidSaying: ["You will never be satisfied", "Your restlessness is a defect"],
    synthesisTags: ["learning_growth", "creativity"],
    confidenceNotes: [MOON_NOTE, NAK_NOTE], safetyNotes: [],
  },
  {
    id: "vedic.nak.ardra", system: "vedic", key: "nak_ardra", title: "Moon in Ardra",
    plainMeaning: "A storm-and-renewal temperament — sharp-minded, emotionally deep, and able to grow through upheaval. You tend to feel things intensely and come out clearer on the other side.",
    strengths: ["Penetrating intelligence", "Resilience through hard change", "Emotional depth and honesty"],
    growthEdges: ["Tending your nervous system through storms", "Letting calm be safe, not boring"],
    supportiveActions: ["nervous_system_reset", "journal_prompt"],
    avoidSaying: ["Your life will be full of chaos", "You are too emotional to cope"],
    synthesisTags: ["change_release", "stress_regulation"],
    confidenceNotes: [MOON_NOTE, NAK_NOTE], safetyNotes: [],
  },
  {
    id: "vedic.nak.punarvasu", system: "vedic", key: "nak_punarvasu", title: "Moon in Punarvasu",
    plainMeaning: "A renewing, hopeful temperament — resilient, generous, and able to begin again after setbacks. You tend to find your way home, restore what's frayed, and keep faith.",
    strengths: ["Resilience and renewal", "Optimism and generosity", "A grounding sense of home"],
    growthEdges: ["Letting yourself fully arrive instead of restarting", "Receiving care, not only giving it"],
    supportiveActions: ["gratitude_reframe", "next_step_plan"],
    avoidSaying: ["You will keep losing everything", "Starting over means you failed"],
    synthesisTags: ["rest_recovery", "nurture_care"],
    confidenceNotes: [MOON_NOTE, NAK_NOTE], safetyNotes: [],
  },
  {
    id: "vedic.nak.pushya", system: "vedic", key: "nak_pushya", title: "Moon in Pushya",
    plainMeaning: "A nourishing, devoted temperament — caring, dependable, and steadying for others. You tend to feed, support, and protect the people and causes you love.",
    strengths: ["Deep care and devotion", "Dependability and steadiness", "A nourishing presence"],
    growthEdges: ["Letting yourself be cared for too", "Not over-giving to earn belonging"],
    supportiveActions: ["boundary_script", "gratitude_reframe"],
    avoidSaying: ["You only matter when you're useful", "Your caretaking will be taken for granted"],
    synthesisTags: ["nurture_care", "connection_love"],
    confidenceNotes: [MOON_NOTE, NAK_NOTE], safetyNotes: [],
  },
  {
    id: "vedic.nak.ashlesha", system: "vedic", key: "nak_ashlesha", title: "Moon in Ashlesha",
    plainMeaning: "A penetrating, perceptive temperament — intuitive, persuasive, and able to read what's beneath the surface. You tend to sense hidden currents others miss.",
    strengths: ["Sharp perception and insight", "Persuasive, hypnotic presence", "Deep intuition"],
    growthEdges: ["Directing your intensity toward what heals", "Trusting openness as much as strategy"],
    supportiveActions: ["boundary_script", "journal_prompt"],
    avoidSaying: ["You are manipulative by nature", "Your intensity is dangerous"],
    synthesisTags: ["learning_growth", "boundaries"],
    confidenceNotes: [MOON_NOTE, NAK_NOTE], safetyNotes: [],
  },
  {
    id: "vedic.nak.magha", system: "vedic", key: "nak_magha", title: "Moon in Magha",
    plainMeaning: "A dignified, ancestral temperament — proud in the best sense, drawn to honor your roots and lead with grace. You tend to carry a sense of legacy and quiet authority.",
    strengths: ["Natural dignity and leadership", "Respect for roots and tradition", "Generosity from a full seat"],
    growthEdges: ["Leading without needing to be above", "Honoring lineage while writing your own line"],
    supportiveActions: ["values_check", "gratitude_reframe"],
    avoidSaying: ["You are arrogant and entitled", "Your pride will be your downfall"],
    synthesisTags: ["leadership", "self_worth"],
    confidenceNotes: [MOON_NOTE, NAK_NOTE], safetyNotes: [],
  },
  {
    id: "vedic.nak.purva_phalguni", system: "vedic", key: "nak_purva_phalguni", title: "Moon in Purva Phalguni",
    plainMeaning: "A warm, pleasure-loving temperament — creative, generous, and drawn to enjoyment, rest, and connection. You tend to bring ease and delight wherever you go.",
    strengths: ["Warmth and generosity", "Creative, playful spirit", "A gift for rest and enjoyment"],
    growthEdges: ["Balancing pleasure with follow-through", "Letting depth join the lightness"],
    supportiveActions: ["gratitude_reframe", "values_check"],
    avoidSaying: ["You are lazy and indulgent", "Your love of comfort makes you weak"],
    synthesisTags: ["creativity", "connection_love"],
    confidenceNotes: [MOON_NOTE, NAK_NOTE], safetyNotes: [],
  },
  {
    id: "vedic.nak.uttara_phalguni", system: "vedic", key: "nak_uttara_phalguni", title: "Moon in Uttara Phalguni",
    plainMeaning: "A reliable, friendship-minded temperament — generous, helpful, and steady in partnership. You tend to show love through loyalty and dependable support.",
    strengths: ["Loyalty and dependability", "Generosity and helpfulness", "Steady partnership"],
    growthEdges: ["Receiving help, not only offering it", "Choosing where your generosity goes"],
    supportiveActions: ["relationship_repair", "boundary_script"],
    avoidSaying: ["You will be used for your kindness", "Helping others is your only worth"],
    synthesisTags: ["connection_love", "planning_structure"],
    confidenceNotes: [MOON_NOTE, NAK_NOTE], safetyNotes: [],
  },
  {
    id: "vedic.nak.hasta", system: "vedic", key: "nak_hasta", title: "Moon in Hasta",
    plainMeaning: "A skillful, clever temperament — handy, witty, and able to turn ideas into real things. You tend to make, fix, and craft, with a light touch and quick mind.",
    strengths: ["Skill and craftsmanship", "Cleverness and wit", "A gift for making things real"],
    growthEdges: ["Trusting your work without over-perfecting", "Letting your hands rest, too"],
    supportiveActions: ["focus_exercise", "next_step_plan"],
    avoidSaying: ["You are never good enough at your craft", "Your perfectionism is hopeless"],
    synthesisTags: ["creativity", "work_focus"],
    confidenceNotes: [MOON_NOTE, NAK_NOTE], safetyNotes: [],
  },
  {
    id: "vedic.nak.chitra", system: "vedic", key: "nak_chitra", title: "Moon in Chitra",
    plainMeaning: "A brilliant, design-minded temperament — charismatic, artistic, and drawn to create beauty and order. You tend to shine and to make things shine around you.",
    strengths: ["Charisma and artistry", "An eye for design and form", "Bold self-expression"],
    growthEdges: ["Building substance beneath the shine", "Letting yourself be seen plainly, too"],
    supportiveActions: ["values_check", "journal_prompt"],
    avoidSaying: ["You are all surface and no depth", "Your need to shine is shallow"],
    synthesisTags: ["creativity", "self_worth"],
    confidenceNotes: [MOON_NOTE, NAK_NOTE], safetyNotes: [],
  },
  {
    id: "vedic.nak.swati", system: "vedic", key: "nak_swati", title: "Moon in Swati",
    plainMeaning: "An independent, adaptable temperament — self-reliant, balanced, and like the wind, hard to pin down. You tend to value freedom and find your own way.",
    strengths: ["Independence and self-reliance", "Adaptability and balance", "Diplomatic flexibility"],
    growthEdges: ["Letting people close without losing freedom", "Committing when it matters"],
    supportiveActions: ["decision_clarity", "values_check"],
    avoidSaying: ["You are too detached to belong", "Your independence will leave you alone"],
    synthesisTags: ["freedom_independence", "decision_clarity"],
    confidenceNotes: [MOON_NOTE, NAK_NOTE], safetyNotes: [],
  },
  {
    id: "vedic.nak.vishakha", system: "vedic", key: "nak_vishakha", title: "Moon in Vishakha",
    plainMeaning: "A goal-driven, determined temperament — focused, ambitious, and willing to work hard for what you want. You tend to lock onto a target and pursue it with patience and fire.",
    strengths: ["Determination and ambition", "Focused, goal-directed energy", "Patience for the long game"],
    growthEdges: ["Enjoying the journey, not only the goal", "Letting rest be part of the plan"],
    supportiveActions: ["next_step_plan", "focus_exercise"],
    avoidSaying: ["You will never feel you've arrived", "Your ambition will burn you out"],
    synthesisTags: ["work_focus", "action_initiative"],
    confidenceNotes: [MOON_NOTE, NAK_NOTE], safetyNotes: [],
  },
  {
    id: "vedic.nak.anuradha", system: "vedic", key: "nak_anuradha", title: "Moon in Anuradha",
    plainMeaning: "A devoted, cooperative temperament — loyal, friendly, and able to thrive through relationship. You tend to succeed by building bonds and working with others.",
    strengths: ["Loyalty and devotion", "A gift for cooperation", "Success through connection"],
    growthEdges: ["Honoring your own needs within bonds", "Leading as well as supporting"],
    supportiveActions: ["relationship_repair", "boundary_script"],
    avoidSaying: ["You will always come second", "Your loyalty will be betrayed"],
    synthesisTags: ["connection_love", "planning_structure"],
    confidenceNotes: [MOON_NOTE, NAK_NOTE], safetyNotes: [],
  },
  {
    id: "vedic.nak.jyeshtha", system: "vedic", key: "nak_jyeshtha", title: "Moon in Jyeshtha",
    plainMeaning: "A capable, responsible temperament — the elder energy, protective and able to carry weight. You tend to take charge and look after others, even when it costs you.",
    strengths: ["Capability and responsibility", "Protective leadership", "Resilience under pressure"],
    growthEdges: ["Asking for help before you're depleted", "Letting others be capable, too"],
    supportiveActions: ["boundary_script", "nervous_system_reset"],
    avoidSaying: ["You must carry everything alone", "Your burdens are yours to bear forever"],
    synthesisTags: ["leadership", "boundaries"],
    confidenceNotes: [MOON_NOTE, NAK_NOTE], safetyNotes: [],
  },
  {
    id: "vedic.nak.mula", system: "vedic", key: "nak_mula", title: "Moon in Mula",
    plainMeaning: "A root-seeking, investigative temperament — drawn to get to the bottom of things, even if it means dismantling them first. You tend to question deeply and rebuild from truth.",
    strengths: ["Depth and investigative drive", "Courage to face hard truths", "Philosophical insight"],
    growthEdges: ["Rebuilding gently after you've uprooted", "Letting some things stay whole"],
    supportiveActions: ["journal_prompt", "values_check"],
    avoidSaying: ["Your life is destined for upheaval", "You destroy what you touch"],
    synthesisTags: ["change_release", "learning_growth"],
    confidenceNotes: [MOON_NOTE, NAK_NOTE], safetyNotes: [],
  },
  {
    id: "vedic.nak.purva_ashadha", system: "vedic", key: "nak_purva_ashadha", title: "Moon in Purva Ashadha",
    plainMeaning: "A confident, persuasive temperament — optimistic, undefeated, and able to lift others with your conviction. You tend to believe in possibility and carry people with you.",
    strengths: ["Conviction and optimism", "Persuasive, uplifting energy", "Refreshing resilience"],
    growthEdges: ["Staying open to other views", "Letting confidence include uncertainty"],
    supportiveActions: ["values_check", "next_step_plan"],
    avoidSaying: ["Your confidence is arrogance", "You're destined to be humbled"],
    synthesisTags: ["self_worth", "action_initiative"],
    confidenceNotes: [MOON_NOTE, NAK_NOTE], safetyNotes: [],
  },
  {
    id: "vedic.nak.uttara_ashadha", system: "vedic", key: "nak_uttara_ashadha", title: "Moon in Uttara Ashadha",
    plainMeaning: "An enduring, principled temperament — drawn to lasting achievement built on integrity. You tend to win slowly and for keeps, by doing things the right way.",
    strengths: ["Integrity and patience", "Lasting, well-built success", "Steady leadership"],
    growthEdges: ["Letting good-enough wins count", "Flexibility within your principles"],
    supportiveActions: ["next_step_plan", "values_check"],
    avoidSaying: ["You must be perfect to succeed", "Your standards will isolate you"],
    synthesisTags: ["leadership", "work_focus"],
    confidenceNotes: [MOON_NOTE, NAK_NOTE], safetyNotes: [],
  },
  {
    id: "vedic.nak.shravana", system: "vedic", key: "nak_shravana", title: "Moon in Shravana",
    plainMeaning: "A listening, learning temperament — attentive, wise, and able to gather understanding through deep attention. You tend to learn by truly hearing others.",
    strengths: ["Deep listening and attention", "Wisdom through learning", "A connecting, trusted presence"],
    growthEdges: ["Voicing your own knowing, too", "Filtering whose words you take in"],
    supportiveActions: ["journal_prompt", "focus_exercise"],
    avoidSaying: ["You absorb everyone else's problems", "Your sensitivity is a weakness"],
    synthesisTags: ["learning_growth", "communication"],
    confidenceNotes: [MOON_NOTE, NAK_NOTE], safetyNotes: [],
  },
  {
    id: "vedic.nak.dhanishta", system: "vedic", key: "nak_dhanishta", title: "Moon in Dhanishta",
    plainMeaning: "A rhythmic, abundant temperament — musical, adaptable, and able to bring people into harmony. You tend to keep the beat and create prosperity around you.",
    strengths: ["Rhythm and timing", "Adaptable, prosperous energy", "A gift for group harmony"],
    growthEdges: ["Pausing the drumbeat to rest", "Letting feeling join the performance"],
    supportiveActions: ["nervous_system_reset", "gratitude_reframe"],
    avoidSaying: ["You must always perform to be valued", "Stillness means you're failing"],
    synthesisTags: ["creativity", "work_focus"],
    confidenceNotes: [MOON_NOTE, NAK_NOTE], safetyNotes: [],
  },
  {
    id: "vedic.nak.shatabhisha", system: "vedic", key: "nak_shatabhisha", title: "Moon in Shatabhisha",
    plainMeaning: "A healing, independent temperament — private, inventive, and drawn to mystery and mending. You tend to go your own way and quietly help others heal.",
    strengths: ["Healing and inventiveness", "Independence and privacy", "Comfort with mystery"],
    growthEdges: ["Letting trusted people in", "Healing yourself, not only others"],
    supportiveActions: ["nervous_system_reset", "journal_prompt"],
    avoidSaying: ["You are too isolated to be well", "Your privacy is avoidance"],
    synthesisTags: ["freedom_independence", "stress_regulation"],
    confidenceNotes: [MOON_NOTE, NAK_NOTE], safetyNotes: [],
  },
  {
    id: "vedic.nak.purva_bhadrapada", system: "vedic", key: "nak_purva_bhadrapada", title: "Moon in Purva Bhadrapada",
    plainMeaning: "An intense, idealistic temperament — passionate, visionary, and able to transform through deep conviction. You tend to feel strongly and reach for something higher.",
    strengths: ["Visionary intensity", "Idealism and conviction", "Transformative depth"],
    growthEdges: ["Grounding big ideals in small steps", "Tending your nervous system through intensity"],
    supportiveActions: ["nervous_system_reset", "next_step_plan"],
    avoidSaying: ["Your intensity makes you unstable", "Your ideals are unrealistic"],
    synthesisTags: ["change_release", "creativity"],
    confidenceNotes: [MOON_NOTE, NAK_NOTE], safetyNotes: [],
  },
  {
    id: "vedic.nak.uttara_bhadrapada", system: "vedic", key: "nak_uttara_bhadrapada", title: "Moon in Uttara Bhadrapada",
    plainMeaning: "A deep, calm temperament — wise, compassionate, and steady like still water. You tend to hold depth without drama, offering quiet, grounding wisdom.",
    strengths: ["Calm depth and wisdom", "Compassion and patience", "A steadying presence"],
    growthEdges: ["Letting your depth be seen and known", "Acting on insight, not only holding it"],
    supportiveActions: ["journal_prompt", "values_check"],
    avoidSaying: ["Your stillness means you're stuck", "You feel too much to function"],
    synthesisTags: ["rest_recovery", "learning_growth"],
    confidenceNotes: [MOON_NOTE, NAK_NOTE], safetyNotes: [],
  },
  {
    id: "vedic.nak.revati", system: "vedic", key: "nak_revati", title: "Moon in Revati",
    plainMeaning: "A gentle, nourishing temperament — kind, imaginative, and a safe harbor for others. You tend to care for the vulnerable and help people reach the end of the road safely.",
    strengths: ["Kindness and compassion", "Imagination and gentleness", "A protective, guiding warmth"],
    growthEdges: ["Keeping some care for yourself", "Setting limits without guilt"],
    supportiveActions: ["gratitude_reframe", "boundary_script"],
    avoidSaying: ["You are too soft for this world", "Your kindness will be exploited"],
    synthesisTags: ["nurture_care", "rest_recovery"],
    confidenceNotes: [MOON_NOTE, NAK_NOTE], safetyNotes: [],
  },
];
