import type { KnowledgeCard } from "./types.ts";

export const westernAstrologyCards: KnowledgeCard[] = [
  {
    id: "wa.sun.aries",
    system: "western_astrology",
    key: "sun_aries",
    title: "Aries Sun",
    plainMeaning:
      "A spark-first temperament that comes alive at the start of things and tends to lead by moving first.",
    strengths: ["Courageous and direct", "Quick to start", "Naturally energizing to others"],
    growthEdges: [
      "Practicing patience with slower-moving moments",
      "Letting follow-through matter as much as the launch",
    ],
    supportiveActions: ["next_step_plan", "nervous_system_reset"],
    avoidSaying: ["You're too aggressive", "You always rush and ruin things"],
    synthesisTags: ["action_initiative", "leadership"],
    confidenceNotes: ["Sun sign is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.sun.taurus",
    system: "western_astrology",
    key: "sun_taurus",
    title: "Taurus Sun",
    plainMeaning:
      "A steady, sensory temperament that builds slowly and values comfort, reliability, and things that last.",
    strengths: ["Grounded and dependable", "Patient", "Deeply appreciates simple pleasures"],
    growthEdges: [
      "Staying open when change is the kinder option",
      "Noticing when comfort becomes avoidance",
    ],
    supportiveActions: ["values_check", "next_step_plan"],
    avoidSaying: ["You're stubborn and lazy", "You never change"],
    synthesisTags: ["planning_structure", "rest_recovery"],
    confidenceNotes: ["Sun sign is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.sun.gemini",
    system: "western_astrology",
    key: "sun_gemini",
    title: "Gemini Sun",
    plainMeaning:
      "A curious, quick-witted temperament that thinks out loud and is energized by ideas, words, and variety.",
    strengths: ["Adaptable and curious", "Great communicator", "Sees many sides of a thing"],
    growthEdges: [
      "Letting some choices stay settled",
      "Following one thread long enough to finish it",
    ],
    supportiveActions: ["decision_clarity", "focus_exercise"],
    avoidSaying: ["You're flaky and two-faced", "You can't commit to anything"],
    synthesisTags: ["communication", "learning_growth"],
    confidenceNotes: ["Sun sign is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.sun.cancer",
    system: "western_astrology",
    key: "sun_cancer",
    title: "Cancer Sun",
    plainMeaning:
      "A caring, feeling-led temperament that bonds deeply and reads the emotional tone of a room before words are spoken.",
    strengths: ["Nurturing and loyal", "Emotionally intuitive", "Creates a sense of home"],
    growthEdges: [
      "Tending your own needs as well as everyone else's",
      "Letting a closed shell open when it's safe",
    ],
    supportiveActions: ["nervous_system_reset", "boundary_script"],
    avoidSaying: ["You're too sensitive", "You're clingy"],
    synthesisTags: ["nurture_care", "connection_love", "rest_recovery"],
    confidenceNotes: ["Sun sign is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.sun.leo",
    system: "western_astrology",
    key: "sun_leo",
    title: "Leo Sun",
    plainMeaning:
      "A warm, expressive temperament that shines when seen and tends to lead with heart, generosity, and play.",
    strengths: ["Generous and warm", "Naturally encouraging", "Brings creative spark"],
    growthEdges: [
      "Knowing your worth without an audience",
      "Sharing the spotlight when it matters",
    ],
    supportiveActions: ["gratitude_reframe", "values_check"],
    avoidSaying: ["You're an attention-seeker", "It's all about you"],
    synthesisTags: ["creativity", "leadership", "self_worth"],
    confidenceNotes: ["Sun sign is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.sun.virgo",
    system: "western_astrology",
    key: "sun_virgo",
    title: "Virgo Sun",
    plainMeaning:
      "A precise, helpful temperament that notices details others miss and shows care through being useful.",
    strengths: ["Thoughtful and thorough", "Practical problem-solver", "Quietly devoted"],
    growthEdges: [
      "Letting good-enough be enough",
      "Softening the inner critic into an inner mentor",
    ],
    supportiveActions: ["gratitude_reframe", "focus_exercise"],
    avoidSaying: ["You're a nitpicky perfectionist", "Nothing is ever good enough for you"],
    synthesisTags: ["work_focus", "planning_structure"],
    confidenceNotes: ["Sun sign is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.sun.libra",
    system: "western_astrology",
    key: "sun_libra",
    title: "Libra Sun",
    plainMeaning:
      "A relational, harmony-seeking temperament that weighs perspectives and is energized by connection, beauty, and fairness.",
    strengths: ["Diplomatic and fair", "Warm in relationship", "Sees the balance in things"],
    growthEdges: [
      "Trusting your own preference before the group's",
      "Letting some decisions be made without everyone's approval",
    ],
    supportiveActions: ["decision_clarity", "boundary_script"],
    avoidSaying: ["You're a people-pleaser who can't decide", "You're so indecisive"],
    synthesisTags: ["connection_love", "decision_clarity", "communication"],
    confidenceNotes: ["Sun sign is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.sun.scorpio",
    system: "western_astrology",
    key: "sun_scorpio",
    title: "Scorpio Sun",
    plainMeaning:
      "An intense, depth-seeking temperament that feels things fully and is drawn to truth, transformation, and real intimacy.",
    strengths: ["Emotionally brave", "Loyal and perceptive", "Comfortable with depth"],
    growthEdges: [
      "Letting trust build instead of testing it",
      "Releasing what's ready to be released",
    ],
    supportiveActions: ["journal_prompt", "relationship_repair"],
    avoidSaying: ["You're secretive and vengeful", "You're too much"],
    synthesisTags: ["change_release", "connection_love"],
    confidenceNotes: ["Sun sign is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.sun.sagittarius",
    system: "western_astrology",
    key: "sun_sagittarius",
    title: "Sagittarius Sun",
    plainMeaning:
      "An adventurous, meaning-seeking temperament that craves freedom, honesty, and a wider view of life.",
    strengths: ["Optimistic and open", "Honest and direct", "Hungry to learn and explore"],
    growthEdges: [
      "Staying present when the next horizon calls",
      "Pairing big-picture vision with the small steps",
    ],
    supportiveActions: ["next_step_plan", "values_check"],
    avoidSaying: ["You're a tactless flake", "You never stick around"],
    synthesisTags: ["freedom_independence", "learning_growth"],
    confidenceNotes: ["Sun sign is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.sun.capricorn",
    system: "western_astrology",
    key: "sun_capricorn",
    title: "Capricorn Sun",
    plainMeaning:
      "A disciplined, long-game temperament that builds steadily toward goals and takes quiet pride in earned results.",
    strengths: ["Responsible and resilient", "Strong work ethic", "Patient with the long climb"],
    growthEdges: [
      "Letting rest count as productive too",
      "Measuring worth by more than achievement",
    ],
    supportiveActions: ["values_check", "next_step_plan", "nervous_system_reset"],
    avoidSaying: ["You're cold and all work", "You only care about status"],
    synthesisTags: ["planning_structure", "work_focus"],
    confidenceNotes: ["Sun sign is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.sun.aquarius",
    system: "western_astrology",
    key: "sun_aquarius",
    title: "Aquarius Sun",
    plainMeaning:
      "An independent, future-minded temperament that thinks in systems and cares about fairness and the bigger collective.",
    strengths: ["Original and principled", "Independent thinker", "Cares about the whole"],
    growthEdges: [
      "Letting people close, not just ideas",
      "Honoring feelings alongside logic",
    ],
    supportiveActions: ["journal_prompt", "values_check"],
    avoidSaying: ["You're detached and weird", "You think you're better than everyone"],
    synthesisTags: ["freedom_independence", "learning_growth"],
    confidenceNotes: ["Sun sign is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.sun.pisces",
    system: "western_astrology",
    key: "sun_pisces",
    title: "Pisces Sun",
    plainMeaning:
      "A dreamy, compassionate temperament that feels the world deeply and moves through life by intuition and imagination.",
    strengths: ["Empathetic and creative", "Gentle and accepting", "Richly imaginative"],
    growthEdges: [
      "Building boundaries that protect your softness",
      "Staying grounded when feelings flood in",
    ],
    supportiveActions: ["boundary_script", "nervous_system_reset"],
    avoidSaying: ["You're a spaced-out escapist", "You're too emotional to function"],
    synthesisTags: ["creativity", "grief_processing", "nurture_care"],
    confidenceNotes: ["Sun sign is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.moon.core",
    system: "western_astrology",
    key: "moon_core",
    title: "The Moon (Emotional Self)",
    plainMeaning:
      "In astrology the Moon represents your inner emotional world — how you feel, soothe yourself, and what makes you feel safe and at home.",
    strengths: ["Points to what genuinely comforts you", "Names your emotional needs", "Honors your inner life"],
    growthEdges: [
      "Letting your emotional needs be valid, not inconvenient",
      "Tending feelings before they overflow",
    ],
    supportiveActions: ["journal_prompt", "nervous_system_reset"],
    avoidSaying: ["Your feelings are irrational", "You should just get over it"],
    synthesisTags: ["nurture_care", "stress_regulation", "rest_recovery"],
    confidenceNotes: ["The Moon is one layer of many; treat it as a gentle mirror, not a rulebook."],
    safetyNotes: [],
  },
  {
    id: "wa.moon.fire",
    system: "western_astrology",
    key: "moon_fire",
    title: "Fire Moon (Emotional Style)",
    plainMeaning:
      "An emotional style that runs warm and quick — feelings arrive with energy and are often best moved through action or expression.",
    strengths: ["Passionate and honest", "Bounces back quickly", "Brings warmth to others"],
    growthEdges: ["Pausing before reacting in the heat", "Letting some feelings simmer rather than flare"],
    supportiveActions: ["nervous_system_reset", "journal_prompt"],
    avoidSaying: ["You're dramatic", "You overreact to everything"],
    synthesisTags: ["stress_regulation", "action_initiative"],
    confidenceNotes: ["Element groupings are broad strokes; your full Moon placement adds nuance."],
    safetyNotes: [],
  },
  {
    id: "wa.moon.earth",
    system: "western_astrology",
    key: "moon_earth",
    title: "Earth Moon (Emotional Style)",
    plainMeaning:
      "An emotional style that finds safety in the tangible — feelings settle through routine, comfort, and steady, practical care.",
    strengths: ["Calm and steadying", "Reliable in feeling", "Soothed by simple rituals"],
    growthEdges: ["Naming feelings even when they're hard to articulate", "Letting comfort flex when life shifts"],
    supportiveActions: ["nervous_system_reset", "values_check"],
    avoidSaying: ["You're emotionally shut down", "You bottle everything up"],
    synthesisTags: ["rest_recovery", "planning_structure"],
    confidenceNotes: ["Element groupings are broad strokes; your full Moon placement adds nuance."],
    safetyNotes: [],
  },
  {
    id: "wa.moon.air",
    system: "western_astrology",
    key: "moon_air",
    title: "Air Moon (Emotional Style)",
    plainMeaning:
      "An emotional style that processes feeling through thought and words — talking it out and understanding why often brings relief.",
    strengths: ["Articulate about feelings", "Seeks perspective", "Soothed by connection and conversation"],
    growthEdges: ["Letting feelings be felt, not just analyzed", "Sitting with emotion before explaining it away"],
    supportiveActions: ["journal_prompt", "relationship_repair"],
    avoidSaying: ["You're cold and over-rational", "You avoid your real feelings"],
    synthesisTags: ["communication", "stress_regulation"],
    confidenceNotes: ["Element groupings are broad strokes; your full Moon placement adds nuance."],
    safetyNotes: [],
  },
  {
    id: "wa.moon.water",
    system: "western_astrology",
    key: "moon_water",
    title: "Water Moon (Emotional Style)",
    plainMeaning:
      "An emotional style that feels deeply and absorbs the moods around it — intuition runs strong and emotions move in tides.",
    strengths: ["Deeply empathetic", "Intuitive and tender", "Emotionally attuned to others"],
    growthEdges: ["Telling your feelings apart from everyone else's", "Building gentle boundaries to avoid flooding"],
    supportiveActions: ["boundary_script", "nervous_system_reset"],
    avoidSaying: ["You're too sensitive", "You make everything about emotion"],
    synthesisTags: ["nurture_care", "grief_processing", "stress_regulation"],
    confidenceNotes: ["Element groupings are broad strokes; your full Moon placement adds nuance."],
    safetyNotes: [],
  },
  {
    id: "wa.element.fire",
    system: "western_astrology",
    key: "element_fire",
    title: "Fire Element",
    plainMeaning:
      "Fire signs (Aries, Leo, Sagittarius) carry an energy of spark, action, and inspiration — they tend to initiate and enliven.",
    strengths: ["Energizing and bold", "Inspiring to others", "Action-oriented"],
    growthEdges: ["Pacing energy so it lasts", "Tending the slow-burning parts of a goal"],
    supportiveActions: ["next_step_plan", "nervous_system_reset"],
    avoidSaying: ["You're reckless and impatient", "You burn everyone out"],
    synthesisTags: ["action_initiative", "creativity"],
    confidenceNotes: ["Element is a broad temperament lens, not a full description of a person."],
    safetyNotes: [],
  },
  {
    id: "wa.element.earth",
    system: "western_astrology",
    key: "element_earth",
    title: "Earth Element",
    plainMeaning:
      "Earth signs (Taurus, Virgo, Capricorn) carry an energy of grounding and building — they tend to make things real, steady, and lasting.",
    strengths: ["Practical and dependable", "Patient builders", "Grounded under pressure"],
    growthEdges: ["Staying flexible when plans change", "Letting in play alongside productivity"],
    supportiveActions: ["next_step_plan", "values_check"],
    avoidSaying: ["You're rigid and stuck", "You never take risks"],
    synthesisTags: ["planning_structure", "work_focus"],
    confidenceNotes: ["Element is a broad temperament lens, not a full description of a person."],
    safetyNotes: [],
  },
  {
    id: "wa.element.air",
    system: "western_astrology",
    key: "element_air",
    title: "Air Element",
    plainMeaning:
      "Air signs (Gemini, Libra, Aquarius) carry an energy of thought and connection — they tend to communicate, link ideas, and see perspectives.",
    strengths: ["Clear thinkers", "Socially connective", "Open to new ideas"],
    growthEdges: ["Grounding ideas into action", "Coming back into the body and feelings"],
    supportiveActions: ["decision_clarity", "focus_exercise"],
    avoidSaying: ["You're all talk", "You live in your head and avoid feeling"],
    synthesisTags: ["communication", "learning_growth"],
    confidenceNotes: ["Element is a broad temperament lens, not a full description of a person."],
    safetyNotes: [],
  },
  {
    id: "wa.element.water",
    system: "western_astrology",
    key: "element_water",
    title: "Water Element",
    plainMeaning:
      "Water signs (Cancer, Scorpio, Pisces) carry an energy of feeling and intuition — they tend to sense deeply and connect through emotion.",
    strengths: ["Empathetic and intuitive", "Emotionally attuned", "Deeply caring"],
    growthEdges: ["Holding boundaries amid others' feelings", "Letting feelings move without drowning in them"],
    supportiveActions: ["boundary_script", "nervous_system_reset"],
    avoidSaying: ["You're moody and oversensitive", "You're ruled by emotion"],
    synthesisTags: ["nurture_care", "grief_processing"],
    confidenceNotes: ["Element is a broad temperament lens, not a full description of a person."],
    safetyNotes: [],
  },
  {
    id: "wa.modality.cardinal",
    system: "western_astrology",
    key: "modality_cardinal",
    title: "Cardinal Modality",
    plainMeaning:
      "Cardinal signs (Aries, Cancer, Libra, Capricorn) carry starter energy — they're good at beginning things and setting things in motion.",
    strengths: ["Great initiators", "Natural leaders", "Comfortable making the first move"],
    growthEdges: ["Sustaining momentum past the launch", "Letting others lead sometimes too"],
    supportiveActions: ["next_step_plan", "decision_clarity"],
    avoidSaying: ["You start things you never finish", "You're too pushy"],
    synthesisTags: ["action_initiative", "leadership"],
    confidenceNotes: ["Modality describes a tendency in energy, not a fixed rule for behavior."],
    safetyNotes: [],
  },
  {
    id: "wa.modality.fixed",
    system: "western_astrology",
    key: "modality_fixed",
    title: "Fixed Modality",
    plainMeaning:
      "Fixed signs (Taurus, Leo, Scorpio, Aquarius) carry sustaining energy — they're good at holding steady, deepening, and seeing things through.",
    strengths: ["Loyal and persistent", "Steady under pressure", "Sees commitments through"],
    growthEdges: ["Loosening grip when change is wiser", "Letting in new perspectives"],
    supportiveActions: ["values_check", "journal_prompt"],
    avoidSaying: ["You're stubborn and inflexible", "You never let anything go"],
    synthesisTags: ["planning_structure", "work_focus"],
    confidenceNotes: ["Modality describes a tendency in energy, not a fixed rule for behavior."],
    safetyNotes: [],
  },
  {
    id: "wa.modality.mutable",
    system: "western_astrology",
    key: "modality_mutable",
    title: "Mutable Modality",
    plainMeaning:
      "Mutable signs (Gemini, Virgo, Sagittarius, Pisces) carry adaptable energy — they're good at adjusting, transitioning, and going with the flow.",
    strengths: ["Flexible and versatile", "Eases transitions", "Reads changing situations well"],
    growthEdges: ["Holding a direction long enough to arrive", "Finding steadiness amid change"],
    supportiveActions: ["focus_exercise", "decision_clarity"],
    avoidSaying: ["You're scattered and unreliable", "You can't commit"],
    synthesisTags: ["change_release", "learning_growth"],
    confidenceNotes: ["Modality describes a tendency in energy, not a fixed rule for behavior."],
    safetyNotes: [],
  },
  {
    id: "wa.planet.mercury",
    system: "western_astrology",
    key: "planet_mercury",
    title: "Mercury (Mind & Communication)",
    plainMeaning:
      "Mercury represents how you think, learn, and communicate — your style of taking in information and putting it into words.",
    strengths: ["Names your thinking style", "Honors how you learn best", "Points to your voice"],
    growthEdges: ["Listening as much as expressing", "Letting understanding come before judgment"],
    supportiveActions: ["journal_prompt", "decision_clarity"],
    avoidSaying: ["You communicate wrong", "You're not smart enough"],
    synthesisTags: ["communication", "learning_growth", "decision_clarity"],
    confidenceNotes: ["Planetary placements are reflective lenses, not fixed personality verdicts."],
    safetyNotes: [],
  },
  {
    id: "wa.planet.venus",
    system: "western_astrology",
    key: "planet_venus",
    title: "Venus (Love & Values)",
    plainMeaning:
      "Venus represents how you love, what you find beautiful, and what you value — your style of connection, pleasure, and worth.",
    strengths: ["Names what you cherish", "Honors your way of loving", "Points to what brings you joy"],
    growthEdges: ["Valuing yourself as much as you value others", "Letting love be received, not only given"],
    supportiveActions: ["values_check", "relationship_repair"],
    avoidSaying: ["You love the wrong way", "You're too needy in relationships"],
    synthesisTags: ["connection_love", "self_worth", "creativity"],
    confidenceNotes: ["Planetary placements are reflective lenses, not fixed personality verdicts."],
    safetyNotes: [],
  },
  {
    id: "wa.planet.mars",
    system: "western_astrology",
    key: "planet_mars",
    title: "Mars (Drive & Action)",
    plainMeaning:
      "Mars represents your drive, energy, and how you assert yourself — the way you pursue what you want and meet conflict.",
    strengths: ["Names your motivation style", "Honors healthy assertiveness", "Points to your courage"],
    growthEdges: ["Channeling frustration into purpose", "Asserting needs without steamrolling"],
    supportiveActions: ["boundary_script", "next_step_plan"],
    avoidSaying: ["You're too angry", "Your drive makes you difficult"],
    synthesisTags: ["action_initiative", "boundaries"],
    confidenceNotes: ["Planetary placements are reflective lenses, not fixed personality verdicts."],
    safetyNotes: [],
  },
  {
    id: "wa.planet.saturn",
    system: "western_astrology",
    key: "planet_saturn",
    title: "Saturn (Structure & Limits)",
    plainMeaning:
      "Saturn represents structure, responsibility, and limits — the areas where patience, discipline, and maturity are quietly built over time.",
    strengths: ["Builds lasting foundations", "Teaches patience", "Rewards steady effort"],
    growthEdges: ["Softening harsh inner rules into kind ones", "Trusting that limits can be teachers, not punishments"],
    supportiveActions: ["next_step_plan", "values_check"],
    avoidSaying: ["You're doomed to struggle here", "This is a curse you can't escape"],
    synthesisTags: ["planning_structure", "boundaries", "timing_patience"],
    confidenceNotes: ["Saturn's themes are framed as growth over time, never as fixed punishment."],
    safetyNotes: [],
  },
  {
    id: "wa.planet.jupiter",
    system: "western_astrology",
    key: "planet_jupiter",
    title: "Jupiter (Growth & Expansion)",
    plainMeaning:
      "Jupiter represents growth, optimism, and expansion — the areas where life tends to open up, teach, and invite a bigger view.",
    strengths: ["Brings optimism and faith", "Points to natural growth areas", "Encourages generosity"],
    growthEdges: ["Pairing big visions with grounded steps", "Knowing when enough is enough"],
    supportiveActions: ["gratitude_reframe", "next_step_plan"],
    avoidSaying: ["This guarantees good luck", "You can't fail here"],
    synthesisTags: ["learning_growth", "freedom_independence"],
    confidenceNotes: ["Jupiter points to opportunity, not guaranteed outcomes."],
    safetyNotes: [],
  },
  {
    id: "wa.rising.core",
    system: "western_astrology",
    key: "rising_core",
    title: "Rising Sign (Ascendant)",
    plainMeaning:
      "Your Rising sign is the impression you give arriving in a room — your first-meeting style and how you tend to approach new situations.",
    strengths: ["Names your natural first impression", "Honors how you meet the world", "Points to your instinctive approach"],
    growthEdges: ["Letting the inner self show, not just the surface", "Trusting people with what's underneath the mask"],
    supportiveActions: ["journal_prompt", "values_check"],
    avoidSaying: ["This is your true self and nothing else", "Your Rising is fake or just a front"],
    synthesisTags: ["self_worth", "communication"],
    confidenceNotes: ["Rising depends on an accurate birth time; without it, hold this loosely."],
    safetyNotes: [],
  },
  {
    id: "wa.transit.mercury_retrograde",
    system: "western_astrology",
    key: "mercury_retrograde",
    title: "Mercury Retrograde",
    plainMeaning:
      "A few-week stretch often felt as a slow-down in communication and plans — best used as an invitation to review, revise, and reflect rather than rush.",
    strengths: ["A natural cue to slow down", "Good for revisiting and editing", "Invites reflection over reaction"],
    growthEdges: ["Double-checking details with patience", "Letting plans breathe instead of forcing them"],
    supportiveActions: ["journal_prompt", "nervous_system_reset"],
    avoidSaying: ["Everything will go wrong now", "Don't make any decisions or it's doomed"],
    synthesisTags: ["communication", "rest_recovery", "timing_patience"],
    confidenceNotes: [
      "Retrogrades are an apparent motion, not a cause of disaster.",
      "Any slow-down is an invitation to reflect, not a prediction of misfortune.",
    ],
    safetyNotes: [],
  },
  {
    id: "wa.phase.new_moon",
    system: "western_astrology",
    key: "new_moon",
    title: "New Moon (Beginnings)",
    plainMeaning:
      "The dark, quiet point of the lunar cycle — often used as a gentle marker for setting intentions and planting seeds for what's next.",
    strengths: ["A natural fresh-start marker", "Good for intention-setting", "Invites quiet and rest"],
    growthEdges: ["Letting beginnings stay small and tender", "Resting before rushing to act"],
    supportiveActions: ["journal_prompt", "next_step_plan"],
    avoidSaying: ["You must launch everything now", "Miss this window and you've failed"],
    synthesisTags: ["change_release", "rest_recovery", "planning_structure"],
    confidenceNotes: ["Moon phases are symbolic rhythms to work with, not deadlines imposed on you."],
    safetyNotes: [],
  },
  {
    id: "wa.phase.full_moon",
    system: "western_astrology",
    key: "full_moon",
    title: "Full Moon (Culmination & Release)",
    plainMeaning:
      "The bright peak of the lunar cycle — often felt as a time of culmination, heightened feeling, and a chance to celebrate or let go.",
    strengths: ["A natural marker for culmination", "Good for releasing what's done", "Invites honest emotional reflection"],
    growthEdges: ["Letting feelings crest without acting on every wave", "Releasing gently rather than forcing closure"],
    supportiveActions: ["gratitude_reframe", "nervous_system_reset"],
    avoidSaying: ["The full moon makes you crazy", "You must cut everything off tonight"],
    synthesisTags: ["change_release", "grief_processing", "stress_regulation"],
    confidenceNotes: ["Moon phases are symbolic rhythms to work with, not forces controlling your mood."],
    safetyNotes: [],
  },
  {
    id: "wa.phase.waxing_moon",
    system: "western_astrology",
    key: "waxing_moon",
    title: "Waxing Moon (Building)",
    plainMeaning:
      "The growing half of the lunar cycle, between new and full — often used as a gentle window for building on intentions, taking steps, and letting things gather momentum.",
    strengths: ["A natural cue to build and grow", "Good for steady, encouraging momentum", "Supports following through on intentions"],
    growthEdges: ["Letting growth happen at a sustainable pace", "Tending one step at a time rather than rushing the peak"],
    supportiveActions: ["next_step_plan", "focus_exercise"],
    avoidSaying: ["You must accomplish everything before the full moon", "Miss this window and you've failed"],
    synthesisTags: ["action_initiative", "planning_structure"],
    confidenceNotes: ["Moon phase is computed from the date (accurate to about a day) — a symbolic rhythm, not a force acting on you."],
    safetyNotes: [],
  },
  {
    id: "wa.phase.waning_moon",
    system: "western_astrology",
    key: "waning_moon",
    title: "Waning Moon (Releasing)",
    plainMeaning:
      "The shrinking half of the lunar cycle, between full and new — often felt as a softer window for winding down, releasing what's complete, and making room to rest.",
    strengths: ["A natural cue to release and rest", "Good for reflecting and tidying up", "Invites a gentler, slower pace"],
    growthEdges: ["Letting yourself rest without guilt", "Releasing gradually rather than forcing an ending"],
    supportiveActions: ["nervous_system_reset", "gratitude_reframe"],
    avoidSaying: ["The waning moon drains your luck", "You must purge everything now"],
    synthesisTags: ["rest_recovery", "change_release"],
    confidenceNotes: ["Moon phase is computed from the date (accurate to about a day) — a symbolic rhythm, not a force acting on you."],
    safetyNotes: [],
  },
  {
    id: "wa.transit.core",
    system: "western_astrology",
    key: "transits_core",
    title: "Transits (Sky Weather)",
    plainMeaning:
      "Transits are the moving planets' relationship to your birth chart — think of them as weather, a changing climate you can dress for, not a fixed fate.",
    strengths: ["Offers timing cues to work with", "Normalizes ups and downs", "Invites gentle preparation"],
    growthEdges: ["Holding forecasts lightly", "Acting from values, not from fear of the sky"],
    supportiveActions: ["journal_prompt", "values_check"],
    avoidSaying: ["The transit will make this happen to you", "You have no choice during this period"],
    synthesisTags: ["timing_patience", "change_release"],
    confidenceNotes: [
      "Transits describe themes and timing, never guaranteed events.",
      "You always keep your agency; the sky is weather, not a script.",
    ],
    safetyNotes: [],
  },

  // ─── Planet-in-sign (personal & social planets) ──────────────────
  // Selected per real planet sign from the provider. 5 planets × 12 signs.
{
    id: "wa.mercury.aries", system: "western_astrology", key: "mercury_aries", title: "Mercury in Aries",
    plainMeaning: "A quick, direct mind that thinks out loud and says what it means — ideas arrive fast and want to move into words and action right away.",
    strengths: ["Fast, decisive thinker", "Honest and clear in speech", "Sparks momentum in a conversation"],
    growthEdges: ["Letting a thought finish forming before it leaves your mouth", "Hearing the whole question before answering"],
    supportiveActions: ["decision_clarity", "journal_prompt"],
    avoidSaying: ["You're rude and never listen", "You always speak without thinking"],
    synthesisTags: ["communication", "action_initiative", "decision_clarity"],
    confidenceNotes: ["Mercury is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.mercury.taurus", system: "western_astrology", key: "mercury_taurus", title: "Mercury in Taurus",
    plainMeaning: "A steady, grounded mind that takes its time and trusts what it can see and touch — once an idea settles in, it stays.",
    strengths: ["Patient, thorough thinking", "Calm, reassuring way of speaking", "Remembers practical detail well"],
    growthEdges: ["Staying open to a new idea even after you've decided", "Letting some conversations move faster than feels comfortable"],
    supportiveActions: ["journal_prompt", "next_step_plan"],
    avoidSaying: ["You're so stubborn and slow", "You never change your mind"],
    synthesisTags: ["communication", "learning_growth", "planning_structure"],
    confidenceNotes: ["Mercury is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.mercury.gemini", system: "western_astrology", key: "mercury_gemini", title: "Mercury in Gemini",
    plainMeaning: "A curious, agile mind that loves words, questions, and connections — it gathers ideas everywhere and enjoys turning them over with others.",
    strengths: ["Quick, flexible learner", "Lively and engaging communicator", "Sees many sides of a topic"],
    growthEdges: ["Letting some ideas settle into depth before moving on", "Choosing one thread to follow all the way through"],
    supportiveActions: ["focus_exercise", "journal_prompt"],
    avoidSaying: ["You're scattered and shallow", "You can't focus on anything"],
    synthesisTags: ["communication", "learning_growth", "creativity"],
    confidenceNotes: ["Mercury is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.mercury.cancer", system: "western_astrology", key: "mercury_cancer", title: "Mercury in Cancer",
    plainMeaning: "A feeling, intuitive mind that thinks through the heart — it remembers what mattered and reads the emotional tone beneath the words.",
    strengths: ["Emotionally attuned listener", "Strong memory for what feels meaningful", "Speaks with warmth and care"],
    growthEdges: ["Naming your thoughts even when they feel tender to share", "Letting facts and feelings both have a seat at the table"],
    supportiveActions: ["journal_prompt", "nervous_system_reset"],
    avoidSaying: ["You're too sensitive to think clearly", "You take everything personally"],
    synthesisTags: ["communication", "nurture_care", "learning_growth"],
    confidenceNotes: ["Mercury is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.mercury.leo", system: "western_astrology", key: "mercury_leo", title: "Mercury in Leo",
    plainMeaning: "A warm, expressive mind that thinks in stories and speaks with heart — ideas feel personal, and sharing them is a creative act.",
    strengths: ["Confident, engaging speaker", "Brings color and warmth to ideas", "Communicates with genuine conviction"],
    growthEdges: ["Inviting other voices to shine alongside yours", "Staying curious when feedback differs from your view"],
    supportiveActions: ["journal_prompt", "values_check"],
    avoidSaying: ["You're arrogant and love your own voice", "You only care about being right"],
    synthesisTags: ["communication", "creativity", "self_worth"],
    confidenceNotes: ["Mercury is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.mercury.virgo", system: "western_astrology", key: "mercury_virgo", title: "Mercury in Virgo",
    plainMeaning: "A precise, discerning mind that notices the details others miss — it loves to understand how things work and how to make them better.",
    strengths: ["Sharp, analytical thinking", "Clear and useful explanations", "Skilled at spotting what needs fixing"],
    growthEdges: ["Letting good enough be enough sometimes", "Offering yourself the same patience you give your work"],
    supportiveActions: ["focus_exercise", "gratitude_reframe"],
    avoidSaying: ["You're a nitpicky perfectionist", "You overthink everything"],
    synthesisTags: ["communication", "work_focus", "decision_clarity"],
    confidenceNotes: ["Mercury is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.mercury.libra", system: "western_astrology", key: "mercury_libra", title: "Mercury in Libra",
    plainMeaning: "A fair, relational mind that weighs every side and wants conversations to feel balanced — it thinks best in dialogue with others.",
    strengths: ["Diplomatic, even-handed communicator", "Sees situations from multiple perspectives", "Brings people toward common ground"],
    growthEdges: ["Naming your own view even before everyone agrees", "Letting a decision be made without endless weighing"],
    supportiveActions: ["decision_clarity", "values_check"],
    avoidSaying: ["You can't make up your mind", "You're a people-pleaser with no opinions"],
    synthesisTags: ["communication", "connection_love", "decision_clarity"],
    confidenceNotes: ["Mercury is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.mercury.scorpio", system: "western_astrology", key: "mercury_scorpio", title: "Mercury in Scorpio",
    plainMeaning: "A deep, investigative mind that looks beneath the surface — it wants the real story and trusts what it uncovers more than what it's told.",
    strengths: ["Penetrating, focused insight", "Sees through to the heart of things", "Keeps confidences and speaks with depth"],
    growthEdges: ["Sharing your conclusions before others have to ask", "Letting some things stay simple rather than hidden"],
    supportiveActions: ["journal_prompt", "focus_exercise"],
    avoidSaying: ["You're secretive and suspicious", "You read too much into everything"],
    synthesisTags: ["communication", "learning_growth", "decision_clarity"],
    confidenceNotes: ["Mercury is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.mercury.sagittarius", system: "western_astrology", key: "mercury_sagittarius", title: "Mercury in Sagittarius",
    plainMeaning: "A big-picture, honest mind that loves ideas, meaning, and the freedom to explore — it reaches for the truth and says it plainly.",
    strengths: ["Visionary, optimistic thinker", "Frank and refreshing in speech", "Connects ideas into a larger meaning"],
    growthEdges: ["Filling in the details that turn a vision into a plan", "Softening blunt truths with a little tact"],
    supportiveActions: ["next_step_plan", "journal_prompt"],
    avoidSaying: ["You're tactless and full of yourself", "You never finish what you start"],
    synthesisTags: ["communication", "learning_growth", "freedom_independence"],
    confidenceNotes: ["Mercury is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.mercury.capricorn", system: "western_astrology", key: "mercury_capricorn", title: "Mercury in Capricorn",
    plainMeaning: "A structured, strategic mind that thinks in steps and outcomes — it speaks with care and prefers ideas it can actually build on.",
    strengths: ["Disciplined, practical thinking", "Measured and credible communicator", "Turns ideas into workable plans"],
    growthEdges: ["Letting playful or untested ideas breathe a little", "Trusting that not every thought needs to be useful"],
    supportiveActions: ["next_step_plan", "decision_clarity"],
    avoidSaying: ["You're cold and rigid", "You only care about results"],
    synthesisTags: ["communication", "planning_structure", "decision_clarity"],
    confidenceNotes: ["Mercury is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.mercury.aquarius", system: "western_astrology", key: "mercury_aquarius", title: "Mercury in Aquarius",
    plainMeaning: "An inventive, independent mind that thinks in patterns and possibilities — it loves an original idea and isn't afraid to see things differently.",
    strengths: ["Original, future-facing thinking", "Objective and open-minded", "Connects ideas in surprising ways"],
    growthEdges: ["Letting feelings into a conversation, not just logic", "Staying with a familiar idea long enough to deepen it"],
    supportiveActions: ["journal_prompt", "focus_exercise"],
    avoidSaying: ["You're detached and think you're superior", "You're contrary just to be different"],
    synthesisTags: ["communication", "learning_growth", "freedom_independence"],
    confidenceNotes: ["Mercury is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.mercury.pisces", system: "western_astrology", key: "mercury_pisces", title: "Mercury in Pisces",
    plainMeaning: "An imaginative, intuitive mind that thinks in images and feelings — it senses what words can't quite hold and speaks with gentle empathy.",
    strengths: ["Creative, associative thinker", "Deeply empathic listener", "Picks up on subtle, unspoken cues"],
    growthEdges: ["Grounding a dreamy idea in a few concrete steps", "Trusting your impressions enough to say them clearly"],
    supportiveActions: ["journal_prompt", "next_step_plan"],
    avoidSaying: ["You're vague and can't focus", "You live in a fantasy world"],
    synthesisTags: ["communication", "creativity", "learning_growth"],
    confidenceNotes: ["Mercury is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.venus.aries", system: "western_astrology", key: "venus_aries", title: "Venus in Aries",
    plainMeaning: "Loves boldly and directly — drawn to spark, honesty, and the thrill of the chase, you show affection by going after what you want.",
    strengths: ["Warm, enthusiastic affection", "Honest about what you want", "Brings excitement and spontaneity to love"],
    growthEdges: ["Letting a connection deepen slowly after the first spark", "Noticing what a partner wants alongside your own wishes"],
    supportiveActions: ["values_check", "relationship_repair"],
    avoidSaying: ["You're selfish in love", "You only want the chase"],
    synthesisTags: ["connection_love", "self_worth", "action_initiative"],
    confidenceNotes: ["Venus is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.venus.taurus", system: "western_astrology", key: "venus_taurus", title: "Venus in Taurus",
    plainMeaning: "Loves with steadiness and sensory warmth — you value loyalty, comfort, and the simple pleasures, and you show care in tangible, lasting ways.",
    strengths: ["Devoted and dependable in love", "Creates comfort and beauty around you", "Savors pleasure and presence fully"],
    growthEdges: ["Staying open when a relationship asks you to change", "Letting go of comforts that no longer serve you"],
    supportiveActions: ["values_check", "gratitude_reframe"],
    avoidSaying: ["You're possessive and materialistic", "You're too set in your ways to love freely"],
    synthesisTags: ["connection_love", "self_worth", "creativity"],
    confidenceNotes: ["Venus is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.venus.gemini", system: "western_astrology", key: "venus_gemini", title: "Venus in Gemini",
    plainMeaning: "Loves through words, wit, and curiosity — you're drawn to lively minds and good conversation, and connection stays fresh when there's something to talk about.",
    strengths: ["Playful, engaging in relationships", "Keeps connection light and curious", "Expresses affection through words and ideas"],
    growthEdges: ["Letting a feeling stay even when it's quiet", "Choosing depth with one person over many surface sparks"],
    supportiveActions: ["journal_prompt", "values_check"],
    avoidSaying: ["You're flaky and can't commit", "You only love with your head, not your heart"],
    synthesisTags: ["connection_love", "communication", "creativity"],
    confidenceNotes: ["Venus is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.venus.cancer", system: "western_astrology", key: "venus_cancer", title: "Venus in Cancer",
    plainMeaning: "Loves tenderly and protectively — you show care by nurturing, remembering, and making people feel safe, and closeness means everything.",
    strengths: ["Deeply caring and nurturing", "Creates emotional safety for loved ones", "Loyal and devoted once trust is built"],
    growthEdges: ["Asking for the care you so freely give", "Letting closeness grow without needing constant reassurance"],
    supportiveActions: ["relationship_repair", "values_check"],
    avoidSaying: ["You're clingy and needy", "You smother the people you love"],
    synthesisTags: ["connection_love", "nurture_care", "self_worth"],
    confidenceNotes: ["Venus is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.venus.leo", system: "western_astrology", key: "venus_leo", title: "Venus in Leo",
    plainMeaning: "Loves warmly and wholeheartedly — generous with affection and devotion, you light up when love is celebrated and given with your whole heart.",
    strengths: ["Generous, devoted affection", "Makes loved ones feel special", "Romantic, playful, and loyal"],
    growthEdges: ["Trusting love that's quiet as much as love that's loud", "Letting a partner shine without needing the spotlight"],
    supportiveActions: ["gratitude_reframe", "values_check"],
    avoidSaying: ["You need too much attention", "You only love when you're admired"],
    synthesisTags: ["connection_love", "self_worth", "creativity"],
    confidenceNotes: ["Venus is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.venus.virgo", system: "western_astrology", key: "venus_virgo", title: "Venus in Virgo",
    plainMeaning: "Loves through care, attention, and useful acts — you show affection by noticing the details and helping, and you value sincerity over show.",
    strengths: ["Thoughtful, attentive in love", "Shows care through helpful acts", "Sincere and reliable in relationships"],
    growthEdges: ["Receiving love without feeling it must be earned", "Letting yourself and a partner be lovably imperfect"],
    supportiveActions: ["gratitude_reframe", "values_check"],
    avoidSaying: ["You're too critical to be loving", "You pick everyone apart"],
    synthesisTags: ["connection_love", "self_worth", "nurture_care"],
    confidenceNotes: ["Venus is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.venus.libra", system: "western_astrology", key: "venus_libra", title: "Venus in Libra",
    plainMeaning: "Loves through harmony, beauty, and partnership — you value fairness and connection deeply, and relationships are where you feel most yourself.",
    strengths: ["Gracious and considerate in love", "Creates harmony and beauty in connection", "Values fairness and mutual care"],
    growthEdges: ["Voicing your own needs even if it ruffles the peace", "Feeling whole on your own, not only in partnership"],
    supportiveActions: ["boundary_script", "values_check"],
    avoidSaying: ["You lose yourself in relationships", "You avoid conflict at any cost"],
    synthesisTags: ["connection_love", "self_worth", "boundaries"],
    confidenceNotes: ["Venus is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.venus.scorpio", system: "western_astrology", key: "venus_scorpio", title: "Venus in Scorpio",
    plainMeaning: "Loves intensely and all the way — you crave real depth and emotional truth, and once you're devoted, you're devoted completely.",
    strengths: ["Passionate, deeply loyal love", "Unafraid of emotional intimacy", "Forms profound, transformative bonds"],
    growthEdges: ["Letting trust build without testing it", "Sharing vulnerability before being certain it's safe"],
    supportiveActions: ["relationship_repair", "journal_prompt"],
    avoidSaying: ["You're jealous and controlling", "You make everything too intense"],
    synthesisTags: ["connection_love", "self_worth", "boundaries"],
    confidenceNotes: ["Venus is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.venus.sagittarius", system: "western_astrology", key: "venus_sagittarius", title: "Venus in Sagittarius",
    plainMeaning: "Loves through adventure, honesty, and shared growth — you're drawn to people who expand your world and give your heart room to roam.",
    strengths: ["Warm, generous, and open-hearted", "Brings adventure and optimism to love", "Honest and easygoing in connection"],
    growthEdges: ["Staying close through the quieter, everyday moments", "Trusting that commitment can feel like freedom too"],
    supportiveActions: ["values_check", "journal_prompt"],
    avoidSaying: ["You're afraid of commitment", "You'll always run when it gets real"],
    synthesisTags: ["connection_love", "freedom_independence", "self_worth"],
    confidenceNotes: ["Venus is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.venus.capricorn", system: "western_astrology", key: "venus_capricorn", title: "Venus in Capricorn",
    plainMeaning: "Loves with commitment and quiet devotion — you take relationships seriously and show care through loyalty, steadiness, and showing up over time.",
    strengths: ["Loyal and committed in love", "Shows care through reliable action", "Builds relationships that last"],
    growthEdges: ["Letting affection be playful, not just dependable", "Believing you're worthy of love before you've earned it"],
    supportiveActions: ["values_check", "gratitude_reframe"],
    avoidSaying: ["You're cold and unromantic", "You treat love like a transaction"],
    synthesisTags: ["connection_love", "self_worth", "planning_structure"],
    confidenceNotes: ["Venus is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.venus.aquarius", system: "western_astrology", key: "venus_aquarius", title: "Venus in Aquarius",
    plainMeaning: "Loves through friendship, freedom, and authenticity — you value connection that respects your independence and meets you as an equal and a friend.",
    strengths: ["Accepting and open-minded in love", "Values friendship and freedom in connection", "Loves people for who they truly are"],
    growthEdges: ["Letting emotional closeness in alongside the freedom", "Naming what you feel, not just what you think"],
    supportiveActions: ["journal_prompt", "values_check"],
    avoidSaying: ["You're emotionally unavailable", "You keep everyone at arm's length"],
    synthesisTags: ["connection_love", "freedom_independence", "self_worth"],
    confidenceNotes: ["Venus is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.venus.pisces", system: "western_astrology", key: "venus_pisces", title: "Venus in Pisces",
    plainMeaning: "Loves tenderly, dreamily, and with deep compassion — you give your heart fully and feel love as something almost spiritual and boundless.",
    strengths: ["Compassionate and romantic", "Gives love freely and gently", "Deeply empathic and tender in connection"],
    growthEdges: ["Keeping a little for yourself as you give so much", "Seeing a person clearly, not only the dream of them"],
    supportiveActions: ["boundary_script", "values_check"],
    avoidSaying: ["You're naive and lose yourself in love", "You love an illusion, not a person"],
    synthesisTags: ["connection_love", "creativity", "boundaries"],
    confidenceNotes: ["Venus is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.mars.aries", system: "western_astrology", key: "mars_aries", title: "Mars in Aries",
    plainMeaning: "Pursues what it wants directly and with real force — you act on instinct, move fast, and aren't afraid to lead or to start.",
    strengths: ["Courageous and decisive in action", "Strong drive to initiate", "Faces challenges head-on"],
    growthEdges: ["Pausing to aim before you fire", "Letting some battles go that aren't worth your energy"],
    supportiveActions: ["next_step_plan", "nervous_system_reset"],
    avoidSaying: ["You're aggressive and impatient", "You always have to win"],
    synthesisTags: ["action_initiative", "boundaries", "leadership"],
    confidenceNotes: ["Mars is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.mars.taurus", system: "western_astrology", key: "mars_taurus", title: "Mars in Taurus",
    plainMeaning: "Pursues goals with patience and staying power — you build momentum slowly and steadily, and once you commit, almost nothing stops you.",
    strengths: ["Persistent and determined", "Steady, reliable follow-through", "Stays calm under pressure"],
    growthEdges: ["Changing course when the plan stops working", "Starting before every condition feels perfect"],
    supportiveActions: ["next_step_plan", "values_check"],
    avoidSaying: ["You're lazy and stubborn", "You never want to move"],
    synthesisTags: ["action_initiative", "planning_structure", "boundaries"],
    confidenceNotes: ["Mars is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.mars.gemini", system: "western_astrology", key: "mars_gemini", title: "Mars in Gemini",
    plainMeaning: "Pursues many interests with quick, lively energy — you act through words, ideas, and variety, and you thrive when you can keep moving and switching gears.",
    strengths: ["Mentally quick and adaptable", "Energized by variety and ideas", "Persuasive and nimble in action"],
    growthEdges: ["Finishing one thing before chasing the next", "Channeling restless energy into a single clear aim"],
    supportiveActions: ["focus_exercise", "next_step_plan"],
    avoidSaying: ["You're scattered and never commit", "You start everything and finish nothing"],
    synthesisTags: ["action_initiative", "communication", "decision_clarity"],
    confidenceNotes: ["Mars is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.mars.cancer", system: "western_astrology", key: "mars_cancer", title: "Mars in Cancer",
    plainMeaning: "Pursues what it cares about with feeling and fierce protectiveness — your energy rises to defend the people and things you love.",
    strengths: ["Fiercely protective of loved ones", "Acts from deep emotional motivation", "Tenacious when something truly matters"],
    growthEdges: ["Expressing anger directly rather than letting it simmer", "Acting on your goals even when your mood dips"],
    supportiveActions: ["boundary_script", "nervous_system_reset"],
    avoidSaying: ["You're moody and passive-aggressive", "You can't handle confrontation"],
    synthesisTags: ["action_initiative", "nurture_care", "boundaries"],
    confidenceNotes: ["Mars is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.mars.leo", system: "western_astrology", key: "mars_leo", title: "Mars in Leo",
    plainMeaning: "Pursues goals with heart, pride, and flair — you put your whole self into what you do and shine brightest when your efforts are seen and matter.",
    strengths: ["Confident and wholehearted in action", "Natural, warm leadership", "Brings passion and energy to any pursuit"],
    growthEdges: ["Staying motivated when no one is watching", "Sharing the lead and the credit generously"],
    supportiveActions: ["values_check", "next_step_plan"],
    avoidSaying: ["You're a show-off who needs applause", "You only do things for attention"],
    synthesisTags: ["action_initiative", "leadership", "creativity"],
    confidenceNotes: ["Mars is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.mars.virgo", system: "western_astrology", key: "mars_virgo", title: "Mars in Virgo",
    plainMeaning: "Pursues goals with precision and steady effort — you put energy into doing things well, improving the details, and being genuinely useful.",
    strengths: ["Diligent and skillful in action", "Excellent at refining and improving", "Channels energy into practical results"],
    growthEdges: ["Acting before everything is perfectly ready", "Easing the inner critic when effort falls short of ideal"],
    supportiveActions: ["next_step_plan", "gratitude_reframe"],
    avoidSaying: ["You're a fussy perfectionist", "Nothing is ever good enough for you"],
    synthesisTags: ["action_initiative", "work_focus", "planning_structure"],
    confidenceNotes: ["Mars is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.mars.libra", system: "western_astrology", key: "mars_libra", title: "Mars in Libra",
    plainMeaning: "Pursues goals through fairness, charm, and collaboration — you'd rather win people over than overpower them, and you act best with a partner in mind.",
    strengths: ["Diplomatic and persuasive in action", "Works well with and through others", "Motivated by fairness and balance"],
    growthEdges: ["Making a move even before everyone agrees", "Letting healthy conflict happen instead of smoothing it over"],
    supportiveActions: ["decision_clarity", "boundary_script"],
    avoidSaying: ["You're indecisive and avoid all conflict", "You can't act without someone else"],
    synthesisTags: ["action_initiative", "connection_love", "decision_clarity"],
    confidenceNotes: ["Mars is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.mars.scorpio", system: "western_astrology", key: "mars_scorpio", title: "Mars in Scorpio",
    plainMeaning: "Pursues goals with depth, focus, and unshakable will — your energy runs powerful and controlled, and you commit to what you want completely.",
    strengths: ["Intensely focused and determined", "Powerful staying power under pressure", "Acts with depth and strategy"],
    growthEdges: ["Releasing control when holding on costs more than it gives", "Letting some feelings move through rather than building them up"],
    supportiveActions: ["nervous_system_reset", "boundary_script"],
    avoidSaying: ["You're vengeful and controlling", "You hold grudges forever"],
    synthesisTags: ["action_initiative", "boundaries", "work_focus"],
    confidenceNotes: ["Mars is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.mars.sagittarius", system: "western_astrology", key: "mars_sagittarius", title: "Mars in Sagittarius",
    plainMeaning: "Pursues goals with adventurous, expansive energy — you chase what excites and inspires you, and you move best when you have room and a reason.",
    strengths: ["Enthusiastic and bold in action", "Energized by adventure and purpose", "Inspires others to aim higher"],
    growthEdges: ["Following through once the first excitement fades", "Aiming your energy before you leap"],
    supportiveActions: ["next_step_plan", "focus_exercise"],
    avoidSaying: ["You're restless and never commit", "You leap without ever looking"],
    synthesisTags: ["action_initiative", "freedom_independence", "leadership"],
    confidenceNotes: ["Mars is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.mars.capricorn", system: "western_astrology", key: "mars_capricorn", title: "Mars in Capricorn",
    plainMeaning: "Pursues goals with discipline, patience, and ambition — you channel energy into steady, strategic effort and play the long game to win.",
    strengths: ["Disciplined and goal-driven", "Excellent at sustained, strategic effort", "Stays composed under pressure"],
    growthEdges: ["Resting before you've fully earned it", "Letting some pursuits be for joy, not just achievement"],
    supportiveActions: ["next_step_plan", "nervous_system_reset"],
    avoidSaying: ["You're a cold workaholic", "You only care about getting ahead"],
    synthesisTags: ["action_initiative", "planning_structure", "leadership"],
    confidenceNotes: ["Mars is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.mars.aquarius", system: "western_astrology", key: "mars_aquarius", title: "Mars in Aquarius",
    plainMeaning: "Pursues goals in its own original way and for a cause — you act on principle, value independence, and put energy into ideas that could change things.",
    strengths: ["Inventive and independent in action", "Driven by principle and vision", "Energized by causes bigger than the self"],
    growthEdges: ["Letting others in on the plan and the work", "Acting on feeling sometimes, not only on logic"],
    supportiveActions: ["values_check", "next_step_plan"],
    avoidSaying: ["You're stubborn and emotionally detached", "You're contrary just to prove a point"],
    synthesisTags: ["action_initiative", "freedom_independence", "leadership"],
    confidenceNotes: ["Mars is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.mars.pisces", system: "western_astrology", key: "mars_pisces", title: "Mars in Pisces",
    plainMeaning: "Pursues goals with imagination, compassion, and flow — your energy moves like water, strongest when it follows inspiration and serves something larger.",
    strengths: ["Creative and intuitive in action", "Motivated by compassion and meaning", "Adapts gracefully to changing currents"],
    growthEdges: ["Choosing a direction even when many feel possible", "Honoring your own anger and needs alongside others'"],
    supportiveActions: ["next_step_plan", "boundary_script"],
    avoidSaying: ["You're passive and have no drive", "You let everyone walk over you"],
    synthesisTags: ["action_initiative", "creativity", "boundaries"],
    confidenceNotes: ["Mars is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.jupiter.aries", system: "western_astrology", key: "jupiter_aries", title: "Jupiter in Aries",
    plainMeaning: "Grows through courage and initiative — life tends to open up when you trust your instincts, take the lead, and bravely begin.",
    strengths: ["Bold faith in new beginnings", "Inspires courage in yourself and others", "Grows by taking the first step"],
    growthEdges: ["Pairing bold leaps with a little patience", "Letting growth include others' pace, not only your own"],
    supportiveActions: ["next_step_plan", "values_check"],
    avoidSaying: ["You're reckless and overconfident", "You always bite off more than you can chew"],
    synthesisTags: ["learning_growth", "action_initiative", "leadership"],
    confidenceNotes: ["Jupiter is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.jupiter.taurus", system: "western_astrology", key: "jupiter_taurus", title: "Jupiter in Taurus",
    plainMeaning: "Grows through patience, steadiness, and savoring what's real — abundance tends to come as you build slowly and enjoy the gifts already here.",
    strengths: ["Grows through steady, grounded effort", "A natural sense of abundance and gratitude", "Builds lasting, tangible good"],
    growthEdges: ["Staying open to growth that requires change", "Trusting there's enough so you can share freely"],
    supportiveActions: ["gratitude_reframe", "values_check"],
    avoidSaying: ["You're complacent and overindulgent", "You only value money and comfort"],
    synthesisTags: ["learning_growth", "self_worth", "planning_structure"],
    confidenceNotes: ["Jupiter is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.jupiter.gemini", system: "western_astrology", key: "jupiter_gemini", title: "Jupiter in Gemini",
    plainMeaning: "Grows through curiosity, learning, and connection — life expands as you ask questions, gather ideas, and share what you discover.",
    strengths: ["Grows through endless curiosity", "Connects ideas and people richly", "A lifelong, joyful learner"],
    growthEdges: ["Going deep with a few things, not just wide with many", "Trusting the wisdom beneath all the information"],
    supportiveActions: ["focus_exercise", "journal_prompt"],
    avoidSaying: ["You know a little about everything and nothing well", "You're scattered and never commit"],
    synthesisTags: ["learning_growth", "communication", "creativity"],
    confidenceNotes: ["Jupiter is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.jupiter.cancer", system: "western_astrology", key: "jupiter_cancer", title: "Jupiter in Cancer",
    plainMeaning: "Grows through care, belonging, and emotional generosity — life expands as you nurture others and let yourself be held in return.",
    strengths: ["Grows through caring and connection", "Generous, big-hearted nurturer", "Creates a sense of home and belonging"],
    growthEdges: ["Letting your care flow outward beyond the familiar", "Receiving support as warmly as you give it"],
    supportiveActions: ["gratitude_reframe", "values_check"],
    avoidSaying: ["You're overly sentimental and dependent", "You smother people with caring"],
    synthesisTags: ["learning_growth", "nurture_care", "connection_love"],
    confidenceNotes: ["Jupiter is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.jupiter.leo", system: "western_astrology", key: "jupiter_leo", title: "Jupiter in Leo",
    plainMeaning: "Grows through warmth, creativity, and generous self-expression — life expands as you share your gifts boldly and uplift others by shining.",
    strengths: ["Grows through creative self-expression", "Generous and warmly encouraging", "Inspires joy and confidence in others"],
    growthEdges: ["Letting growth include humility and quiet moments", "Celebrating others' light as brightly as your own"],
    supportiveActions: ["gratitude_reframe", "values_check"],
    avoidSaying: ["You're an arrogant attention-seeker", "You always make it about you"],
    synthesisTags: ["learning_growth", "creativity", "self_worth"],
    confidenceNotes: ["Jupiter is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.jupiter.virgo", system: "western_astrology", key: "jupiter_virgo", title: "Jupiter in Virgo",
    plainMeaning: "Grows through service, skill, and steady improvement — life expands as you refine your craft, help where it counts, and value useful work.",
    strengths: ["Grows through meaningful service", "Finds the bigger picture in small details", "Improves steadily and skillfully"],
    growthEdges: ["Seeing how far you've come, not just what's left to fix", "Letting growth feel abundant, not only earned"],
    supportiveActions: ["gratitude_reframe", "next_step_plan"],
    avoidSaying: ["You're a worrier who can't see the big picture", "Nothing is ever good enough for you"],
    synthesisTags: ["learning_growth", "work_focus", "planning_structure"],
    confidenceNotes: ["Jupiter is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.jupiter.libra", system: "western_astrology", key: "jupiter_libra", title: "Jupiter in Libra",
    plainMeaning: "Grows through relationship, fairness, and beauty — life expands as you build connection, seek justice, and bring more harmony into the world.",
    strengths: ["Grows through meaningful partnership", "A strong, generous sense of fairness", "Brings people together gracefully"],
    growthEdges: ["Growing on your own terms, not only through others", "Letting some disagreement exist on the way to balance"],
    supportiveActions: ["values_check", "decision_clarity"],
    avoidSaying: ["You can't function without a partner", "You avoid every hard truth to keep the peace"],
    synthesisTags: ["learning_growth", "connection_love", "decision_clarity"],
    confidenceNotes: ["Jupiter is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.jupiter.scorpio", system: "western_astrology", key: "jupiter_scorpio", title: "Jupiter in Scorpio",
    plainMeaning: "Grows through depth, honesty, and transformation — life expands as you face what's hidden, heal what's deep, and trust your own power to change.",
    strengths: ["Grows through deep transformation", "Unafraid of life's profound questions", "Finds meaning in renewal and healing"],
    growthEdges: ["Letting growth feel light sometimes, not only intense", "Trusting and opening up before you're fully certain"],
    supportiveActions: ["journal_prompt", "values_check"],
    avoidSaying: ["You're obsessive and secretive", "You make everything a crisis"],
    synthesisTags: ["learning_growth", "change_release", "self_worth"],
    confidenceNotes: ["Jupiter is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.jupiter.sagittarius", system: "western_astrology", key: "jupiter_sagittarius", title: "Jupiter in Sagittarius",
    plainMeaning: "Grows through exploration, meaning, and freedom — life expands as you adventure, seek truth, and follow your sense of what's possible.",
    strengths: ["Grows through bold exploration", "Natural optimism and faith in life", "Inspires others with vision and meaning"],
    growthEdges: ["Grounding big visions in everyday follow-through", "Holding your truths with room for other views"],
    supportiveActions: ["next_step_plan", "values_check"],
    avoidSaying: ["You're a preachy know-it-all", "You overpromise and never deliver"],
    synthesisTags: ["learning_growth", "freedom_independence", "leadership"],
    confidenceNotes: ["Jupiter is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.jupiter.capricorn", system: "western_astrology", key: "jupiter_capricorn", title: "Jupiter in Capricorn",
    plainMeaning: "Grows through discipline, patience, and earned mastery — life expands as you commit to the long climb and build something solid over time.",
    strengths: ["Grows through patient, lasting effort", "Turns ambition into real achievement", "Finds meaning in responsibility"],
    growthEdges: ["Letting abundance feel possible without constant effort", "Trusting good things can arrive sooner than expected"],
    supportiveActions: ["next_step_plan", "gratitude_reframe"],
    avoidSaying: ["You're a joyless workaholic", "You only respect success and status"],
    synthesisTags: ["learning_growth", "planning_structure", "leadership"],
    confidenceNotes: ["Jupiter is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.jupiter.aquarius", system: "western_astrology", key: "jupiter_aquarius", title: "Jupiter in Aquarius",
    plainMeaning: "Grows through vision, innovation, and community — life expands as you imagine a better future, honor your ideals, and connect with kindred spirits.",
    strengths: ["Grows through original, future-facing ideas", "Generous toward community and causes", "Open-minded and forward-thinking"],
    growthEdges: ["Letting growth feel personal, not only principled", "Staying with people through messy, human moments"],
    supportiveActions: ["values_check", "journal_prompt"],
    avoidSaying: ["You're a detached idealist", "You care about humanity but not people"],
    synthesisTags: ["learning_growth", "freedom_independence", "connection_love"],
    confidenceNotes: ["Jupiter is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.jupiter.pisces", system: "western_astrology", key: "jupiter_pisces", title: "Jupiter in Pisces",
    plainMeaning: "Grows through compassion, imagination, and faith — life expands as you open your heart, trust the unseen, and let kindness guide the way.",
    strengths: ["Grows through deep compassion", "Rich imagination and intuition", "A generous, forgiving spirit"],
    growthEdges: ["Pairing boundless compassion with healthy limits", "Grounding dreams in a few concrete steps"],
    supportiveActions: ["boundary_script", "values_check"],
    avoidSaying: ["You're naive and escapist", "You give until there's nothing left of you"],
    synthesisTags: ["learning_growth", "creativity", "nurture_care"],
    confidenceNotes: ["Jupiter is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.saturn.aries", system: "western_astrology", key: "saturn_aries", title: "Saturn in Aries",
    plainMeaning: "Builds maturity around courage and action — over time you learn to channel raw drive into steady, self-directed strength you can rely on.",
    strengths: ["Develops disciplined courage", "Learns to lead with patience", "Turns impulse into purposeful action"],
    growthEdges: ["Trusting your right to assert yourself", "Letting action and patience work together over time"],
    supportiveActions: ["next_step_plan", "boundary_script"],
    avoidSaying: ["You're held back and never brave enough", "You'll always struggle to stand up for yourself"],
    synthesisTags: ["planning_structure", "action_initiative", "boundaries"],
    confidenceNotes: ["Saturn's themes grow gentler with time; this is never a punishment.", "One placement among many in a full chart."],
    safetyNotes: [],
  },
  {
    id: "wa.saturn.taurus", system: "western_astrology", key: "saturn_taurus", title: "Saturn in Taurus",
    plainMeaning: "Builds security and lasting worth slowly and surely — over time you learn that real stability comes from patience, not from clinging.",
    strengths: ["Builds genuine, lasting security", "Develops deep patience and persistence", "Grounds values into steady reality"],
    growthEdges: ["Trusting there is enough, even when fear says otherwise", "Letting go of what no longer brings real stability"],
    supportiveActions: ["values_check", "next_step_plan"],
    avoidSaying: ["You're cheap and afraid of losing everything", "You'll never feel secure"],
    synthesisTags: ["planning_structure", "self_worth", "timing_patience"],
    confidenceNotes: ["Saturn's themes grow gentler with time; this is never a punishment.", "One placement among many in a full chart."],
    safetyNotes: [],
  },
  {
    id: "wa.saturn.gemini", system: "western_astrology", key: "saturn_gemini", title: "Saturn in Gemini",
    plainMeaning: "Builds discipline around thinking and communication — over time you learn to focus a busy mind and speak with real depth and weight.",
    strengths: ["Develops focused, structured thinking", "Learns to communicate with depth", "Masters subjects through patient study"],
    growthEdges: ["Trusting your voice even when words feel imperfect", "Letting curiosity coexist with disciplined focus"],
    supportiveActions: ["focus_exercise", "journal_prompt"],
    avoidSaying: ["You're not smart or articulate enough", "You'll never be able to focus"],
    synthesisTags: ["planning_structure", "communication", "learning_growth"],
    confidenceNotes: ["Saturn's themes grow gentler with time; this is never a punishment.", "One placement among many in a full chart."],
    safetyNotes: [],
  },
  {
    id: "wa.saturn.cancer", system: "western_astrology", key: "saturn_cancer", title: "Saturn in Cancer",
    plainMeaning: "Builds emotional security and steady care over time — you learn, gradually, to give your feelings a safe home and to let others in.",
    strengths: ["Develops deep emotional resilience", "Builds a true and stable sense of home", "Learns to care for self and others wisely"],
    growthEdges: ["Letting yourself be vulnerable and supported", "Trusting that needing others is a strength, not a risk"],
    supportiveActions: ["nervous_system_reset", "values_check"],
    avoidSaying: ["You're emotionally closed off forever", "You'll never feel safe enough to open up"],
    synthesisTags: ["planning_structure", "nurture_care", "stress_regulation"],
    confidenceNotes: ["Saturn's themes grow gentler with time; this is never a punishment.", "One placement among many in a full chart."],
    safetyNotes: [],
  },
  {
    id: "wa.saturn.leo", system: "western_astrology", key: "saturn_leo", title: "Saturn in Leo",
    plainMeaning: "Builds authentic confidence over time — you learn that real self-worth and creative power come from within, not only from being seen.",
    strengths: ["Develops grounded, earned confidence", "Builds creative discipline and mastery", "Learns to lead with quiet authority"],
    growthEdges: ["Trusting your worth without needing constant proof", "Letting yourself shine before you feel fully ready"],
    supportiveActions: ["values_check", "gratitude_reframe"],
    avoidSaying: ["You're not special enough to stand out", "You'll always doubt your own worth"],
    synthesisTags: ["planning_structure", "self_worth", "creativity"],
    confidenceNotes: ["Saturn's themes grow gentler with time; this is never a punishment.", "One placement among many in a full chart."],
    safetyNotes: [],
  },
  {
    id: "wa.saturn.virgo", system: "western_astrology", key: "saturn_virgo", title: "Saturn in Virgo",
    plainMeaning: "Builds mastery through diligence and care — over time you learn to do meaningful work well while letting go of impossible standards.",
    strengths: ["Develops real skill and reliability", "Brings discipline to useful work", "Learns to improve steadily and wisely"],
    growthEdges: ["Letting good work be enough without perfection", "Offering yourself the patience you give your craft"],
    supportiveActions: ["gratitude_reframe", "next_step_plan"],
    avoidSaying: ["You're never competent enough", "You'll always be too hard on yourself"],
    synthesisTags: ["planning_structure", "work_focus", "self_worth"],
    confidenceNotes: ["Saturn's themes grow gentler with time; this is never a punishment.", "One placement among many in a full chart."],
    safetyNotes: [],
  },
  {
    id: "wa.saturn.libra", system: "western_astrology", key: "saturn_libra", title: "Saturn in Libra",
    plainMeaning: "Builds mature, lasting relationships over time — you learn that real harmony comes from fairness, commitment, and honest balance.",
    strengths: ["Develops deep relationship wisdom", "Builds fair, committed partnerships", "Learns to balance self and other"],
    growthEdges: ["Trusting that healthy conflict can strengthen a bond", "Knowing your own worth within any partnership"],
    supportiveActions: ["boundary_script", "relationship_repair"],
    avoidSaying: ["You're doomed to lonely or unfair relationships", "You'll never get partnership right"],
    synthesisTags: ["planning_structure", "connection_love", "boundaries"],
    confidenceNotes: ["Saturn's themes grow gentler with time; this is never a punishment.", "One placement among many in a full chart."],
    safetyNotes: [],
  },
  {
    id: "wa.saturn.scorpio", system: "western_astrology", key: "saturn_scorpio", title: "Saturn in Scorpio",
    plainMeaning: "Builds resilience through depth and honest transformation — over time you learn to face hard truths and to trust your own power to heal.",
    strengths: ["Develops profound emotional strength", "Faces difficulty with courage and depth", "Learns to trust through transformation"],
    growthEdges: ["Letting control soften into trust over time", "Allowing closeness even where you've been guarded"],
    supportiveActions: ["journal_prompt", "nervous_system_reset"],
    avoidSaying: ["You're destined for pain and betrayal", "You'll never be able to trust"],
    synthesisTags: ["planning_structure", "change_release", "boundaries"],
    confidenceNotes: ["Saturn's themes grow gentler with time; this is never a punishment.", "One placement among many in a full chart."],
    safetyNotes: [],
  },
  {
    id: "wa.saturn.sagittarius", system: "western_astrology", key: "saturn_sagittarius", title: "Saturn in Sagittarius",
    plainMeaning: "Builds wisdom and grounded belief over time — you learn to turn big ideas into lived truth and to commit to a meaningful path.",
    strengths: ["Develops earned, tested wisdom", "Grounds vision in real commitment", "Learns to teach from genuine experience"],
    growthEdges: ["Trusting your beliefs while staying open to learning", "Letting freedom and commitment grow together"],
    supportiveActions: ["values_check", "next_step_plan"],
    avoidSaying: ["You're rigid and closed-minded", "You'll never find what you believe in"],
    synthesisTags: ["planning_structure", "learning_growth", "freedom_independence"],
    confidenceNotes: ["Saturn's themes grow gentler with time; this is never a punishment.", "One placement among many in a full chart."],
    safetyNotes: [],
  },
  {
    id: "wa.saturn.capricorn", system: "western_astrology", key: "saturn_capricorn", title: "Saturn in Capricorn",
    plainMeaning: "Builds lasting achievement through discipline and time — you learn that patient, responsible effort creates something that truly endures.",
    strengths: ["Masters long-term, disciplined effort", "Builds enduring, real accomplishment", "Develops steady, trustworthy authority"],
    growthEdges: ["Letting rest and joy count as success too", "Measuring your worth beyond what you achieve"],
    supportiveActions: ["next_step_plan", "values_check"],
    avoidSaying: ["You're cold and only value status", "You'll never feel you've done enough"],
    synthesisTags: ["planning_structure", "timing_patience", "leadership"],
    confidenceNotes: ["Saturn's themes grow gentler with time; this is never a punishment.", "One placement among many in a full chart."],
    safetyNotes: [],
  },
  {
    id: "wa.saturn.aquarius", system: "western_astrology", key: "saturn_aquarius", title: "Saturn in Aquarius",
    plainMeaning: "Builds structure around ideals and community over time — you learn to turn vision into something real and to belong while staying true to yourself.",
    strengths: ["Turns ideals into lasting structures", "Develops disciplined, original thinking", "Builds genuine community over time"],
    growthEdges: ["Letting yourself belong without losing your individuality", "Trusting your ideas enough to build them patiently"],
    supportiveActions: ["values_check", "next_step_plan"],
    avoidSaying: ["You're an outsider who never fits in", "You'll always feel alone in your ideals"],
    synthesisTags: ["planning_structure", "freedom_independence", "learning_growth"],
    confidenceNotes: ["Saturn's themes grow gentler with time; this is never a punishment.", "One placement among many in a full chart."],
    safetyNotes: [],
  },
  {
    id: "wa.saturn.pisces", system: "western_astrology", key: "saturn_pisces", title: "Saturn in Pisces",
    plainMeaning: "Builds structure around dreams, compassion, and intuition — learning, over time, to give formless feelings a shape that can hold them.",
    strengths: ["Brings discipline to creative or spiritual life", "Compassion that matures into steady care", "Can make the intangible real"],
    growthEdges: ["Trusting intuition enough to act on it", "Letting boundaries protect your softness rather than harden it"],
    supportiveActions: ["boundary_script", "values_check"],
    avoidSaying: ["Your dreams are doomed to fail", "You'll never get it together"],
    synthesisTags: ["planning_structure", "boundaries", "creativity"],
    confidenceNotes: ["Saturn's themes grow gentler with time; this is never a punishment.", "One placement among many in a full chart."],
    safetyNotes: [],
  },

  // ─── Houses (require an accurate birth time) ──────────────────────
  // These are selected ONLY when the provider returns real houses, which only
  // happens with a known birth time. Every card carries the time caveat.
  {
    id: "wa.house.1",
    system: "western_astrology",
    key: "house_1",
    title: "First House (Self & Approach)",
    plainMeaning:
      "The house of how you show up and meet new beginnings — your instinctive approach to life and the energy you lead with when you walk into a room.",
    strengths: ["A clear, natural way of meeting the world", "Self-starting instincts", "Presence others can feel"],
    growthEdges: ["Letting your inner world show, not just your approach", "Choosing your response rather than only reacting"],
    supportiveActions: ["journal_prompt", "values_check"],
    avoidSaying: ["This house defines your whole personality", "Your identity here is fixed forever"],
    synthesisTags: ["self_worth", "action_initiative"],
    confidenceNotes: ["Houses depend on an accurate birth time; without it, hold this loosely.", "One area of a whole chart, not a verdict."],
    safetyNotes: [],
  },
  {
    id: "wa.house.2",
    system: "western_astrology",
    key: "house_2",
    title: "Second House (Worth & Resources)",
    plainMeaning:
      "The house of values, security, and self-worth — your relationship with what you have, what you treasure, and feeling grounded and resourced.",
    strengths: ["A grounded sense of what matters", "Practical care for security", "Capacity to build steadiness"],
    growthEdges: ["Letting worth come from within, not only from what you hold", "Noticing when security tips into holding on too tightly"],
    supportiveActions: ["values_check", "gratitude_reframe"],
    avoidSaying: ["This guarantees wealth or lack", "Your worth depends on what you own"],
    synthesisTags: ["self_worth", "planning_structure"],
    confidenceNotes: ["Houses depend on an accurate birth time; without it, hold this loosely.", "A reflective lens on values, never financial advice."],
    safetyNotes: [],
  },
  {
    id: "wa.house.3",
    system: "western_astrology",
    key: "house_3",
    title: "Third House (Mind & Connection)",
    plainMeaning:
      "The house of everyday thinking, talking, and learning — how you share ideas, stay curious, and connect with the people and places close to home.",
    strengths: ["Curiosity and quick learning", "Natural everyday communication", "Interest in many things"],
    growthEdges: ["Following one thread long enough to deepen it", "Letting silence be part of conversation too"],
    supportiveActions: ["journal_prompt", "focus_exercise"],
    avoidSaying: ["You'll never focus your mind", "This makes you scattered"],
    synthesisTags: ["communication", "learning_growth"],
    confidenceNotes: ["Houses depend on an accurate birth time; without it, hold this loosely.", "One area of a whole chart, not a fixed trait."],
    safetyNotes: [],
  },
  {
    id: "wa.house.4",
    system: "western_astrology",
    key: "house_4",
    title: "Fourth House (Home & Roots)",
    plainMeaning:
      "The house of home, family, and emotional foundation — where you come from, what makes you feel safe, and the inner base you return to.",
    strengths: ["A deep sense of roots and belonging", "Care for home and the people in it", "Emotional memory and loyalty"],
    growthEdges: ["Tending your own inner home, not only others'", "Letting the past inform you without defining you"],
    supportiveActions: ["nervous_system_reset", "journal_prompt"],
    avoidSaying: ["Your family wounds are permanent", "You're trapped by your past"],
    synthesisTags: ["nurture_care", "rest_recovery"],
    confidenceNotes: ["Houses depend on an accurate birth time; without it, hold this loosely.", "A gentle mirror for home themes, not a diagnosis."],
    safetyNotes: [],
  },
  {
    id: "wa.house.5",
    system: "western_astrology",
    key: "house_5",
    title: "Fifth House (Creativity & Joy)",
    plainMeaning:
      "The house of play, creativity, and self-expression — where you make things, take heartfelt risks, and let joy and romance light you up.",
    strengths: ["Natural creative spark", "Capacity for play and delight", "Warmth in self-expression"],
    growthEdges: ["Creating for joy, not only for approval", "Letting yourself be seen while you play"],
    supportiveActions: ["gratitude_reframe", "next_step_plan"],
    avoidSaying: ["Your creativity isn't real talent", "Play is a waste of your time"],
    synthesisTags: ["creativity", "self_worth"],
    confidenceNotes: ["Houses depend on an accurate birth time; without it, hold this loosely.", "One area of a whole chart, held lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.house.6",
    system: "western_astrology",
    key: "house_6",
    title: "Sixth House (Routines & Care)",
    plainMeaning:
      "The house of daily rhythms, work, and well-being — how you tend the small habits, the body, and the steady acts of care that hold a life together.",
    strengths: ["Skill with helpful routines", "Care shown through usefulness", "Attention to well-being"],
    growthEdges: ["Letting good-enough be enough", "Resting before the body has to insist on it"],
    supportiveActions: ["nervous_system_reset", "next_step_plan"],
    avoidSaying: ["You have a health condition", "You'll always be overwhelmed"],
    synthesisTags: ["work_focus", "stress_regulation"],
    confidenceNotes: ["Houses depend on an accurate birth time; without it, hold this loosely.", "A reflective lens on routines, never medical advice."],
    safetyNotes: [],
  },
  {
    id: "wa.house.7",
    system: "western_astrology",
    key: "house_7",
    title: "Seventh House (Partnership)",
    plainMeaning:
      "The house of one-to-one relationships — how you partner, commit, and meet others as equals, and what you tend to seek and mirror in close bonds.",
    strengths: ["A gift for genuine partnership", "Awareness of balance with others", "Willingness to meet people halfway"],
    growthEdges: ["Keeping your own center inside closeness", "Asking for what you need, not only adapting"],
    supportiveActions: ["relationship_repair", "boundary_script"],
    avoidSaying: ["You'll struggle in love forever", "The other person's feelings are knowable for certain"],
    synthesisTags: ["connection_love", "communication"],
    confidenceNotes: ["Houses depend on an accurate birth time; without it, hold this loosely.", "A mirror for your side of relating, not the other person's mind."],
    safetyNotes: [],
  },
  {
    id: "wa.house.8",
    system: "western_astrology",
    key: "house_8",
    title: "Eighth House (Depth & Change)",
    plainMeaning:
      "The house of intimacy, deep trust, and transformation — where you share what's beneath the surface, let things end, and grow through what changes you.",
    strengths: ["Comfort with emotional depth", "Capacity for real intimacy", "Resilience through change"],
    growthEdges: ["Letting trust build in its own time", "Releasing what a chapter has completed"],
    supportiveActions: ["journal_prompt", "nervous_system_reset"],
    avoidSaying: ["This predicts loss or crisis", "Something is bound to be taken from you"],
    synthesisTags: ["change_release", "connection_love"],
    confidenceNotes: ["Houses depend on an accurate birth time; without it, hold this loosely.", "About symbolic depth and renewal, never literal harm."],
    safetyNotes: [],
  },
  {
    id: "wa.house.9",
    system: "western_astrology",
    key: "house_9",
    title: "Ninth House (Meaning & Horizons)",
    plainMeaning:
      "The house of meaning, belief, and wider horizons — where you seek understanding through learning, travel, and the bigger questions that give life direction.",
    strengths: ["Hunger to learn and understand", "Openness to new horizons", "A search for meaning"],
    growthEdges: ["Grounding big ideas in lived steps", "Staying curious rather than certain about beliefs"],
    supportiveActions: ["values_check", "next_step_plan"],
    avoidSaying: ["Your beliefs are the only truth", "You'll never find what you're seeking"],
    synthesisTags: ["learning_growth", "freedom_independence"],
    confidenceNotes: ["Houses depend on an accurate birth time; without it, hold this loosely.", "One area of a whole chart, held openly."],
    safetyNotes: [],
  },
  {
    id: "wa.house.10",
    system: "western_astrology",
    key: "house_10",
    title: "Tenth House (Vocation & Direction)",
    plainMeaning:
      "The house of vocation and long-term direction — your public role, the contribution you're building, and how you want to be known for your work over time.",
    strengths: ["A sense of direction and ambition", "Willingness to build over time", "Care for doing meaningful work"],
    growthEdges: ["Measuring worth by more than achievement", "Letting rest count as part of the climb"],
    supportiveActions: ["next_step_plan", "values_check"],
    avoidSaying: ["You're destined to fail or to succeed", "Your worth equals your status"],
    synthesisTags: ["work_focus", "leadership"],
    confidenceNotes: ["Houses depend on an accurate birth time; without it, hold this loosely.", "A reflective lens on direction, not a prediction of outcomes."],
    safetyNotes: [],
  },
  {
    id: "wa.house.11",
    system: "western_astrology",
    key: "house_11",
    title: "Eleventh House (Community & Hopes)",
    plainMeaning:
      "The house of friendship, community, and hopes — where you find your people, contribute to something larger, and let yourself imagine what's possible.",
    strengths: ["A sense of belonging in community", "Care for shared hopes", "Openness to wide connection"],
    growthEdges: ["Letting a few close bonds matter as much as the group", "Honoring your own dreams within collective ones"],
    supportiveActions: ["relationship_repair", "gratitude_reframe"],
    avoidSaying: ["You'll always feel like an outsider", "Your hopes are unrealistic"],
    synthesisTags: ["connection_love", "freedom_independence"],
    confidenceNotes: ["Houses depend on an accurate birth time; without it, hold this loosely.", "One area of a whole chart, held lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.house.12",
    system: "western_astrology",
    key: "house_12",
    title: "Twelfth House (Rest & Inner World)",
    plainMeaning:
      "The house of the inner world, rest, and quiet release — the behind-the-scenes space where you dream, restore, and let go of what you've been carrying.",
    strengths: ["Rich inner and imaginative life", "Capacity for compassion and surrender", "Need for restorative quiet honored"],
    growthEdges: ["Letting rest be productive too", "Bringing what's hidden gently into the light"],
    supportiveActions: ["nervous_system_reset", "journal_prompt"],
    avoidSaying: ["Hidden enemies are working against you", "This house brings secret misfortune"],
    synthesisTags: ["rest_recovery", "change_release"],
    confidenceNotes: ["Houses depend on an accurate birth time; without it, hold this loosely.", "About inner rest and release, never hidden doom."],
    safetyNotes: [],
  },

  // ─── Aspects (how two parts of the chart relate) ──────────────────
  // Selected only when the provider returns real aspects. Hard aspects
  // (square, opposition) are framed as growth and integration, never doom.
  {
    id: "wa.aspect.conjunction",
    system: "western_astrology",
    key: "aspect_conjunction",
    title: "Conjunction (Blended Energies)",
    plainMeaning:
      "Two parts of your chart sit together and blend into one strong current — they amplify each other, bringing focus and intensity to whatever they touch.",
    strengths: ["Concentrated focus and power", "A unified, recognizable strength", "Energy that's easy to feel and use"],
    growthEdges: ["Giving blended energies room so they don't run hot", "Noticing where two drives could use a little separation"],
    supportiveActions: ["focus_exercise", "journal_prompt"],
    avoidSaying: ["This aspect controls your fate", "These energies will overwhelm you"],
    synthesisTags: ["self_worth", "work_focus"],
    confidenceNotes: ["An aspect describes how two parts of you relate, not a fixed outcome.", "Aspects are clearest with an accurate birth time."],
    safetyNotes: [],
  },
  {
    id: "wa.aspect.sextile",
    system: "western_astrology",
    key: "aspect_sextile",
    title: "Sextile (Open Door)",
    plainMeaning:
      "A supportive, friendly link between two parts of you — an opportunity that opens when you take a small, willing step toward it.",
    strengths: ["Natural opportunities to grow", "Easy cooperation between strengths", "Talent that responds to effort"],
    growthEdges: ["Taking the small step so the opportunity isn't missed", "Noticing gifts that are easy to take for granted"],
    supportiveActions: ["next_step_plan", "decision_clarity"],
    avoidSaying: ["This guarantees good luck", "Success here is automatic"],
    synthesisTags: ["learning_growth", "decision_clarity"],
    confidenceNotes: ["An aspect describes how two parts of you relate, not a fixed outcome.", "Aspects are clearest with an accurate birth time."],
    safetyNotes: [],
  },
  {
    id: "wa.aspect.square",
    system: "western_astrology",
    key: "aspect_square",
    title: "Square (Creative Friction)",
    plainMeaning:
      "Two parts of you pull in different directions, creating friction — uncomfortable at times, but exactly the tension that builds real strength and growth.",
    strengths: ["Drive that comes from inner tension", "Motivation to grow and resolve", "Resilience forged through challenge"],
    growthEdges: ["Treating friction as fuel rather than a flaw", "Letting both sides have a voice instead of picking a winner"],
    supportiveActions: ["journal_prompt", "nervous_system_reset"],
    avoidSaying: ["This aspect dooms this area of life", "You'll always struggle here"],
    synthesisTags: ["change_release", "stress_regulation"],
    confidenceNotes: ["An aspect describes how two parts of you relate, not a fixed outcome.", "Hard aspects are growth edges, never punishments."],
    safetyNotes: [],
  },
  {
    id: "wa.aspect.trine",
    system: "western_astrology",
    key: "aspect_trine",
    title: "Trine (Natural Flow)",
    plainMeaning:
      "Two parts of you work together with natural ease — a gift that flows so smoothly you might overlook it, and that grows brighter when you use it on purpose.",
    strengths: ["Effortless, natural talent", "Ease and flow in this area", "A reliable source of confidence"],
    growthEdges: ["Using an easy gift rather than coasting on it", "Noticing and appreciating what comes naturally"],
    supportiveActions: ["gratitude_reframe", "next_step_plan"],
    avoidSaying: ["This guarantees everything will be easy", "You don't need to try here at all"],
    synthesisTags: ["creativity", "self_worth"],
    confidenceNotes: ["An aspect describes how two parts of you relate, not a fixed outcome.", "Aspects are clearest with an accurate birth time."],
    safetyNotes: [],
  },
  {
    id: "wa.aspect.opposition",
    system: "western_astrology",
    key: "aspect_opposition",
    title: "Opposition (Balancing Act)",
    plainMeaning:
      "Two needs sit at opposite ends and ask to be balanced — often mirrored back through relationships, inviting you to hold both rather than choose one.",
    strengths: ["Awareness of two sides", "Capacity to find balance", "Growth through relationship and mirroring"],
    growthEdges: ["Integrating both needs instead of swinging between them", "Owning your half of what relationships reflect"],
    supportiveActions: ["decision_clarity", "relationship_repair"],
    avoidSaying: ["You're forever torn and can't win", "Other people are the problem here"],
    synthesisTags: ["connection_love", "decision_clarity"],
    confidenceNotes: ["An aspect describes how two parts of you relate, not a fixed outcome.", "Aspects are clearest with an accurate birth time."],
    safetyNotes: [],
  },
];
