import type { KnowledgeCard } from "./types.ts";

export const westernAstrologyCards: KnowledgeCard[] = [
  {
    id: "wa.sun.aries",
    system: "western_astrology",
    key: "sun_aries",
    title: "Aries Sun",
    plainMeaning:
      "A spark-first temperament that comes alive at the start of things and tends to lead by moving first.",
    strengths: ["Courageous and direct", "Quick to start", "Naturally energizing to others"],
    growthEdges: [
      "Practicing patience with slower-moving moments",
      "Letting follow-through matter as much as the launch",
    ],
    supportiveActions: ["next_step_plan", "nervous_system_reset"],
    avoidSaying: ["You're too aggressive", "You always rush and ruin things"],
    synthesisTags: ["action_initiative", "leadership"],
    confidenceNotes: ["Sun sign is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.sun.taurus",
    system: "western_astrology",
    key: "sun_taurus",
    title: "Taurus Sun",
    plainMeaning:
      "A steady, sensory temperament that builds slowly and values comfort, reliability, and things that last.",
    strengths: ["Grounded and dependable", "Patient", "Deeply appreciates simple pleasures"],
    growthEdges: [
      "Staying open when change is the kinder option",
      "Noticing when comfort becomes avoidance",
    ],
    supportiveActions: ["values_check", "next_step_plan"],
    avoidSaying: ["You're stubborn and lazy", "You never change"],
    synthesisTags: ["planning_structure", "rest_recovery"],
    confidenceNotes: ["Sun sign is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.sun.gemini",
    system: "western_astrology",
    key: "sun_gemini",
    title: "Gemini Sun",
    plainMeaning:
      "A curious, quick-witted temperament that thinks out loud and is energized by ideas, words, and variety.",
    strengths: ["Adaptable and curious", "Great communicator", "Sees many sides of a thing"],
    growthEdges: [
      "Letting some choices stay settled",
      "Following one thread long enough to finish it",
    ],
    supportiveActions: ["decision_clarity", "focus_exercise"],
    avoidSaying: ["You're flaky and two-faced", "You can't commit to anything"],
    synthesisTags: ["communication", "learning_growth"],
    confidenceNotes: ["Sun sign is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.sun.cancer",
    system: "western_astrology",
    key: "sun_cancer",
    title: "Cancer Sun",
    plainMeaning:
      "A caring, feeling-led temperament that bonds deeply and reads the emotional tone of a room before words are spoken.",
    strengths: ["Nurturing and loyal", "Emotionally intuitive", "Creates a sense of home"],
    growthEdges: [
      "Tending your own needs as well as everyone else's",
      "Letting a closed shell open when it's safe",
    ],
    supportiveActions: ["nervous_system_reset", "boundary_script"],
    avoidSaying: ["You're too sensitive", "You're clingy"],
    synthesisTags: ["nurture_care", "connection_love", "rest_recovery"],
    confidenceNotes: ["Sun sign is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.sun.leo",
    system: "western_astrology",
    key: "sun_leo",
    title: "Leo Sun",
    plainMeaning:
      "A warm, expressive temperament that shines when seen and tends to lead with heart, generosity, and play.",
    strengths: ["Generous and warm", "Naturally encouraging", "Brings creative spark"],
    growthEdges: [
      "Knowing your worth without an audience",
      "Sharing the spotlight when it matters",
    ],
    supportiveActions: ["gratitude_reframe", "values_check"],
    avoidSaying: ["You're an attention-seeker", "It's all about you"],
    synthesisTags: ["creativity", "leadership", "self_worth"],
    confidenceNotes: ["Sun sign is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.sun.virgo",
    system: "western_astrology",
    key: "sun_virgo",
    title: "Virgo Sun",
    plainMeaning:
      "A precise, helpful temperament that notices details others miss and shows care through being useful.",
    strengths: ["Thoughtful and thorough", "Practical problem-solver", "Quietly devoted"],
    growthEdges: [
      "Letting good-enough be enough",
      "Softening the inner critic into an inner mentor",
    ],
    supportiveActions: ["gratitude_reframe", "focus_exercise"],
    avoidSaying: ["You're a nitpicky perfectionist", "Nothing is ever good enough for you"],
    synthesisTags: ["work_focus", "planning_structure"],
    confidenceNotes: ["Sun sign is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.sun.libra",
    system: "western_astrology",
    key: "sun_libra",
    title: "Libra Sun",
    plainMeaning:
      "A relational, harmony-seeking temperament that weighs perspectives and is energized by connection, beauty, and fairness.",
    strengths: ["Diplomatic and fair", "Warm in relationship", "Sees the balance in things"],
    growthEdges: [
      "Trusting your own preference before the group's",
      "Letting some decisions be made without everyone's approval",
    ],
    supportiveActions: ["decision_clarity", "boundary_script"],
    avoidSaying: ["You're a people-pleaser who can't decide", "You're so indecisive"],
    synthesisTags: ["connection_love", "decision_clarity", "communication"],
    confidenceNotes: ["Sun sign is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.sun.scorpio",
    system: "western_astrology",
    key: "sun_scorpio",
    title: "Scorpio Sun",
    plainMeaning:
      "An intense, depth-seeking temperament that feels things fully and is drawn to truth, transformation, and real intimacy.",
    strengths: ["Emotionally brave", "Loyal and perceptive", "Comfortable with depth"],
    growthEdges: [
      "Letting trust build instead of testing it",
      "Releasing what's ready to be released",
    ],
    supportiveActions: ["journal_prompt", "relationship_repair"],
    avoidSaying: ["You're secretive and vengeful", "You're too much"],
    synthesisTags: ["change_release", "connection_love"],
    confidenceNotes: ["Sun sign is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.sun.sagittarius",
    system: "western_astrology",
    key: "sun_sagittarius",
    title: "Sagittarius Sun",
    plainMeaning:
      "An adventurous, meaning-seeking temperament that craves freedom, honesty, and a wider view of life.",
    strengths: ["Optimistic and open", "Honest and direct", "Hungry to learn and explore"],
    growthEdges: [
      "Staying present when the next horizon calls",
      "Pairing big-picture vision with the small steps",
    ],
    supportiveActions: ["next_step_plan", "values_check"],
    avoidSaying: ["You're a tactless flake", "You never stick around"],
    synthesisTags: ["freedom_independence", "learning_growth"],
    confidenceNotes: ["Sun sign is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.sun.capricorn",
    system: "western_astrology",
    key: "sun_capricorn",
    title: "Capricorn Sun",
    plainMeaning:
      "A disciplined, long-game temperament that builds steadily toward goals and takes quiet pride in earned results.",
    strengths: ["Responsible and resilient", "Strong work ethic", "Patient with the long climb"],
    growthEdges: [
      "Letting rest count as productive too",
      "Measuring worth by more than achievement",
    ],
    supportiveActions: ["values_check", "next_step_plan", "nervous_system_reset"],
    avoidSaying: ["You're cold and all work", "You only care about status"],
    synthesisTags: ["planning_structure", "work_focus"],
    confidenceNotes: ["Sun sign is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.sun.aquarius",
    system: "western_astrology",
    key: "sun_aquarius",
    title: "Aquarius Sun",
    plainMeaning:
      "An independent, future-minded temperament that thinks in systems and cares about fairness and the bigger collective.",
    strengths: ["Original and principled", "Independent thinker", "Cares about the whole"],
    growthEdges: [
      "Letting people close, not just ideas",
      "Honoring feelings alongside logic",
    ],
    supportiveActions: ["journal_prompt", "values_check"],
    avoidSaying: ["You're detached and weird", "You think you're better than everyone"],
    synthesisTags: ["freedom_independence", "learning_growth"],
    confidenceNotes: ["Sun sign is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.sun.pisces",
    system: "western_astrology",
    key: "sun_pisces",
    title: "Pisces Sun",
    plainMeaning:
      "A dreamy, compassionate temperament that feels the world deeply and moves through life by intuition and imagination.",
    strengths: ["Empathetic and creative", "Gentle and accepting", "Richly imaginative"],
    growthEdges: [
      "Building boundaries that protect your softness",
      "Staying grounded when feelings flood in",
    ],
    supportiveActions: ["boundary_script", "nervous_system_reset"],
    avoidSaying: ["You're a spaced-out escapist", "You're too emotional to function"],
    synthesisTags: ["creativity", "grief_processing", "nurture_care"],
    confidenceNotes: ["Sun sign is one thread of a whole chart; hold it lightly."],
    safetyNotes: [],
  },
  {
    id: "wa.moon.core",
    system: "western_astrology",
    key: "moon_core",
    title: "The Moon (Emotional Self)",
    plainMeaning:
      "In astrology the Moon represents your inner emotional world — how you feel, soothe yourself, and what makes you feel safe and at home.",
    strengths: ["Points to what genuinely comforts you", "Names your emotional needs", "Honors your inner life"],
    growthEdges: [
      "Letting your emotional needs be valid, not inconvenient",
      "Tending feelings before they overflow",
    ],
    supportiveActions: ["journal_prompt", "nervous_system_reset"],
    avoidSaying: ["Your feelings are irrational", "You should just get over it"],
    synthesisTags: ["nurture_care", "stress_regulation", "rest_recovery"],
    confidenceNotes: ["The Moon is one layer of many; treat it as a gentle mirror, not a rulebook."],
    safetyNotes: [],
  },
  {
    id: "wa.moon.fire",
    system: "western_astrology",
    key: "moon_fire",
    title: "Fire Moon (Emotional Style)",
    plainMeaning:
      "An emotional style that runs warm and quick — feelings arrive with energy and are often best moved through action or expression.",
    strengths: ["Passionate and honest", "Bounces back quickly", "Brings warmth to others"],
    growthEdges: ["Pausing before reacting in the heat", "Letting some feelings simmer rather than flare"],
    supportiveActions: ["nervous_system_reset", "journal_prompt"],
    avoidSaying: ["You're dramatic", "You overreact to everything"],
    synthesisTags: ["stress_regulation", "action_initiative"],
    confidenceNotes: ["Element groupings are broad strokes; your full Moon placement adds nuance."],
    safetyNotes: [],
  },
  {
    id: "wa.moon.earth",
    system: "western_astrology",
    key: "moon_earth",
    title: "Earth Moon (Emotional Style)",
    plainMeaning:
      "An emotional style that finds safety in the tangible — feelings settle through routine, comfort, and steady, practical care.",
    strengths: ["Calm and steadying", "Reliable in feeling", "Soothed by simple rituals"],
    growthEdges: ["Naming feelings even when they're hard to articulate", "Letting comfort flex when life shifts"],
    supportiveActions: ["nervous_system_reset", "values_check"],
    avoidSaying: ["You're emotionally shut down", "You bottle everything up"],
    synthesisTags: ["rest_recovery", "planning_structure"],
    confidenceNotes: ["Element groupings are broad strokes; your full Moon placement adds nuance."],
    safetyNotes: [],
  },
  {
    id: "wa.moon.air",
    system: "western_astrology",
    key: "moon_air",
    title: "Air Moon (Emotional Style)",
    plainMeaning:
      "An emotional style that processes feeling through thought and words — talking it out and understanding why often brings relief.",
    strengths: ["Articulate about feelings", "Seeks perspective", "Soothed by connection and conversation"],
    growthEdges: ["Letting feelings be felt, not just analyzed", "Sitting with emotion before explaining it away"],
    supportiveActions: ["journal_prompt", "relationship_repair"],
    avoidSaying: ["You're cold and over-rational", "You avoid your real feelings"],
    synthesisTags: ["communication", "stress_regulation"],
    confidenceNotes: ["Element groupings are broad strokes; your full Moon placement adds nuance."],
    safetyNotes: [],
  },
  {
    id: "wa.moon.water",
    system: "western_astrology",
    key: "moon_water",
    title: "Water Moon (Emotional Style)",
    plainMeaning:
      "An emotional style that feels deeply and absorbs the moods around it — intuition runs strong and emotions move in tides.",
    strengths: ["Deeply empathetic", "Intuitive and tender", "Emotionally attuned to others"],
    growthEdges: ["Telling your feelings apart from everyone else's", "Building gentle boundaries to avoid flooding"],
    supportiveActions: ["boundary_script", "nervous_system_reset"],
    avoidSaying: ["You're too sensitive", "You make everything about emotion"],
    synthesisTags: ["nurture_care", "grief_processing", "stress_regulation"],
    confidenceNotes: ["Element groupings are broad strokes; your full Moon placement adds nuance."],
    safetyNotes: [],
  },
  {
    id: "wa.element.fire",
    system: "western_astrology",
    key: "element_fire",
    title: "Fire Element",
    plainMeaning:
      "Fire signs (Aries, Leo, Sagittarius) carry an energy of spark, action, and inspiration — they tend to initiate and enliven.",
    strengths: ["Energizing and bold", "Inspiring to others", "Action-oriented"],
    growthEdges: ["Pacing energy so it lasts", "Tending the slow-burning parts of a goal"],
    supportiveActions: ["next_step_plan", "nervous_system_reset"],
    avoidSaying: ["You're reckless and impatient", "You burn everyone out"],
    synthesisTags: ["action_initiative", "creativity"],
    confidenceNotes: ["Element is a broad temperament lens, not a full description of a person."],
    safetyNotes: [],
  },
  {
    id: "wa.element.earth",
    system: "western_astrology",
    key: "element_earth",
    title: "Earth Element",
    plainMeaning:
      "Earth signs (Taurus, Virgo, Capricorn) carry an energy of grounding and building — they tend to make things real, steady, and lasting.",
    strengths: ["Practical and dependable", "Patient builders", "Grounded under pressure"],
    growthEdges: ["Staying flexible when plans change", "Letting in play alongside productivity"],
    supportiveActions: ["next_step_plan", "values_check"],
    avoidSaying: ["You're rigid and stuck", "You never take risks"],
    synthesisTags: ["planning_structure", "work_focus"],
    confidenceNotes: ["Element is a broad temperament lens, not a full description of a person."],
    safetyNotes: [],
  },
  {
    id: "wa.element.air",
    system: "western_astrology",
    key: "element_air",
    title: "Air Element",
    plainMeaning:
      "Air signs (Gemini, Libra, Aquarius) carry an energy of thought and connection — they tend to communicate, link ideas, and see perspectives.",
    strengths: ["Clear thinkers", "Socially connective", "Open to new ideas"],
    growthEdges: ["Grounding ideas into action", "Coming back into the body and feelings"],
    supportiveActions: ["decision_clarity", "focus_exercise"],
    avoidSaying: ["You're all talk", "You live in your head and avoid feeling"],
    synthesisTags: ["communication", "learning_growth"],
    confidenceNotes: ["Element is a broad temperament lens, not a full description of a person."],
    safetyNotes: [],
  },
  {
    id: "wa.element.water",
    system: "western_astrology",
    key: "element_water",
    title: "Water Element",
    plainMeaning:
      "Water signs (Cancer, Scorpio, Pisces) carry an energy of feeling and intuition — they tend to sense deeply and connect through emotion.",
    strengths: ["Empathetic and intuitive", "Emotionally attuned", "Deeply caring"],
    growthEdges: ["Holding boundaries amid others' feelings", "Letting feelings move without drowning in them"],
    supportiveActions: ["boundary_script", "nervous_system_reset"],
    avoidSaying: ["You're moody and oversensitive", "You're ruled by emotion"],
    synthesisTags: ["nurture_care", "grief_processing"],
    confidenceNotes: ["Element is a broad temperament lens, not a full description of a person."],
    safetyNotes: [],
  },
  {
    id: "wa.modality.cardinal",
    system: "western_astrology",
    key: "modality_cardinal",
    title: "Cardinal Modality",
    plainMeaning:
      "Cardinal signs (Aries, Cancer, Libra, Capricorn) carry starter energy — they're good at beginning things and setting things in motion.",
    strengths: ["Great initiators", "Natural leaders", "Comfortable making the first move"],
    growthEdges: ["Sustaining momentum past the launch", "Letting others lead sometimes too"],
    supportiveActions: ["next_step_plan", "decision_clarity"],
    avoidSaying: ["You start things you never finish", "You're too pushy"],
    synthesisTags: ["action_initiative", "leadership"],
    confidenceNotes: ["Modality describes a tendency in energy, not a fixed rule for behavior."],
    safetyNotes: [],
  },
  {
    id: "wa.modality.fixed",
    system: "western_astrology",
    key: "modality_fixed",
    title: "Fixed Modality",
    plainMeaning:
      "Fixed signs (Taurus, Leo, Scorpio, Aquarius) carry sustaining energy — they're good at holding steady, deepening, and seeing things through.",
    strengths: ["Loyal and persistent", "Steady under pressure", "Sees commitments through"],
    growthEdges: ["Loosening grip when change is wiser", "Letting in new perspectives"],
    supportiveActions: ["values_check", "journal_prompt"],
    avoidSaying: ["You're stubborn and inflexible", "You never let anything go"],
    synthesisTags: ["planning_structure", "work_focus"],
    confidenceNotes: ["Modality describes a tendency in energy, not a fixed rule for behavior."],
    safetyNotes: [],
  },
  {
    id: "wa.modality.mutable",
    system: "western_astrology",
    key: "modality_mutable",
    title: "Mutable Modality",
    plainMeaning:
      "Mutable signs (Gemini, Virgo, Sagittarius, Pisces) carry adaptable energy — they're good at adjusting, transitioning, and going with the flow.",
    strengths: ["Flexible and versatile", "Eases transitions", "Reads changing situations well"],
    growthEdges: ["Holding a direction long enough to arrive", "Finding steadiness amid change"],
    supportiveActions: ["focus_exercise", "decision_clarity"],
    avoidSaying: ["You're scattered and unreliable", "You can't commit"],
    synthesisTags: ["change_release", "learning_growth"],
    confidenceNotes: ["Modality describes a tendency in energy, not a fixed rule for behavior."],
    safetyNotes: [],
  },
  {
    id: "wa.planet.mercury",
    system: "western_astrology",
    key: "planet_mercury",
    title: "Mercury (Mind & Communication)",
    plainMeaning:
      "Mercury represents how you think, learn, and communicate — your style of taking in information and putting it into words.",
    strengths: ["Names your thinking style", "Honors how you learn best", "Points to your voice"],
    growthEdges: ["Listening as much as expressing", "Letting understanding come before judgment"],
    supportiveActions: ["journal_prompt", "decision_clarity"],
    avoidSaying: ["You communicate wrong", "You're not smart enough"],
    synthesisTags: ["communication", "learning_growth", "decision_clarity"],
    confidenceNotes: ["Planetary placements are reflective lenses, not fixed personality verdicts."],
    safetyNotes: [],
  },
  {
    id: "wa.planet.venus",
    system: "western_astrology",
    key: "planet_venus",
    title: "Venus (Love & Values)",
    plainMeaning:
      "Venus represents how you love, what you find beautiful, and what you value — your style of connection, pleasure, and worth.",
    strengths: ["Names what you cherish", "Honors your way of loving", "Points to what brings you joy"],
    growthEdges: ["Valuing yourself as much as you value others", "Letting love be received, not only given"],
    supportiveActions: ["values_check", "relationship_repair"],
    avoidSaying: ["You love the wrong way", "You're too needy in relationships"],
    synthesisTags: ["connection_love", "self_worth", "creativity"],
    confidenceNotes: ["Planetary placements are reflective lenses, not fixed personality verdicts."],
    safetyNotes: [],
  },
  {
    id: "wa.planet.mars",
    system: "western_astrology",
    key: "planet_mars",
    title: "Mars (Drive & Action)",
    plainMeaning:
      "Mars represents your drive, energy, and how you assert yourself — the way you pursue what you want and meet conflict.",
    strengths: ["Names your motivation style", "Honors healthy assertiveness", "Points to your courage"],
    growthEdges: ["Channeling frustration into purpose", "Asserting needs without steamrolling"],
    supportiveActions: ["boundary_script", "next_step_plan"],
    avoidSaying: ["You're too angry", "Your drive makes you difficult"],
    synthesisTags: ["action_initiative", "boundaries"],
    confidenceNotes: ["Planetary placements are reflective lenses, not fixed personality verdicts."],
    safetyNotes: [],
  },
  {
    id: "wa.planet.saturn",
    system: "western_astrology",
    key: "planet_saturn",
    title: "Saturn (Structure & Limits)",
    plainMeaning:
      "Saturn represents structure, responsibility, and limits — the areas where patience, discipline, and maturity are quietly built over time.",
    strengths: ["Builds lasting foundations", "Teaches patience", "Rewards steady effort"],
    growthEdges: ["Softening harsh inner rules into kind ones", "Trusting that limits can be teachers, not punishments"],
    supportiveActions: ["next_step_plan", "values_check"],
    avoidSaying: ["You're doomed to struggle here", "This is a curse you can't escape"],
    synthesisTags: ["planning_structure", "boundaries", "timing_patience"],
    confidenceNotes: ["Saturn's themes are framed as growth over time, never as fixed punishment."],
    safetyNotes: [],
  },
  {
    id: "wa.planet.jupiter",
    system: "western_astrology",
    key: "planet_jupiter",
    title: "Jupiter (Growth & Expansion)",
    plainMeaning:
      "Jupiter represents growth, optimism, and expansion — the areas where life tends to open up, teach, and invite a bigger view.",
    strengths: ["Brings optimism and faith", "Points to natural growth areas", "Encourages generosity"],
    growthEdges: ["Pairing big visions with grounded steps", "Knowing when enough is enough"],
    supportiveActions: ["gratitude_reframe", "next_step_plan"],
    avoidSaying: ["This guarantees good luck", "You can't fail here"],
    synthesisTags: ["learning_growth", "freedom_independence"],
    confidenceNotes: ["Jupiter points to opportunity, not guaranteed outcomes."],
    safetyNotes: [],
  },
  {
    id: "wa.rising.core",
    system: "western_astrology",
    key: "rising_core",
    title: "Rising Sign (Ascendant)",
    plainMeaning:
      "Your Rising sign is the impression you give arriving in a room — your first-meeting style and how you tend to approach new situations.",
    strengths: ["Names your natural first impression", "Honors how you meet the world", "Points to your instinctive approach"],
    growthEdges: ["Letting the inner self show, not just the surface", "Trusting people with what's underneath the mask"],
    supportiveActions: ["journal_prompt", "values_check"],
    avoidSaying: ["This is your true self and nothing else", "Your Rising is fake or just a front"],
    synthesisTags: ["self_worth", "communication"],
    confidenceNotes: ["Rising depends on an accurate birth time; without it, hold this loosely."],
    safetyNotes: [],
  },
  {
    id: "wa.transit.mercury_retrograde",
    system: "western_astrology",
    key: "mercury_retrograde",
    title: "Mercury Retrograde",
    plainMeaning:
      "A few-week stretch often felt as a slow-down in communication and plans — best used as an invitation to review, revise, and reflect rather than rush.",
    strengths: ["A natural cue to slow down", "Good for revisiting and editing", "Invites reflection over reaction"],
    growthEdges: ["Double-checking details with patience", "Letting plans breathe instead of forcing them"],
    supportiveActions: ["journal_prompt", "nervous_system_reset"],
    avoidSaying: ["Everything will go wrong now", "Don't make any decisions or it's doomed"],
    synthesisTags: ["communication", "rest_recovery", "timing_patience"],
    confidenceNotes: [
      "Retrogrades are an apparent motion, not a cause of disaster.",
      "Any slow-down is an invitation to reflect, not a prediction of misfortune.",
    ],
    safetyNotes: [],
  },
  {
    id: "wa.phase.new_moon",
    system: "western_astrology",
    key: "new_moon",
    title: "New Moon (Beginnings)",
    plainMeaning:
      "The dark, quiet point of the lunar cycle — often used as a gentle marker for setting intentions and planting seeds for what's next.",
    strengths: ["A natural fresh-start marker", "Good for intention-setting", "Invites quiet and rest"],
    growthEdges: ["Letting beginnings stay small and tender", "Resting before rushing to act"],
    supportiveActions: ["journal_prompt", "next_step_plan"],
    avoidSaying: ["You must launch everything now", "Miss this window and you've failed"],
    synthesisTags: ["change_release", "rest_recovery", "planning_structure"],
    confidenceNotes: ["Moon phases are symbolic rhythms to work with, not deadlines imposed on you."],
    safetyNotes: [],
  },
  {
    id: "wa.phase.full_moon",
    system: "western_astrology",
    key: "full_moon",
    title: "Full Moon (Culmination & Release)",
    plainMeaning:
      "The bright peak of the lunar cycle — often felt as a time of culmination, heightened feeling, and a chance to celebrate or let go.",
    strengths: ["A natural marker for culmination", "Good for releasing what's done", "Invites honest emotional reflection"],
    growthEdges: ["Letting feelings crest without acting on every wave", "Releasing gently rather than forcing closure"],
    supportiveActions: ["gratitude_reframe", "nervous_system_reset"],
    avoidSaying: ["The full moon makes you crazy", "You must cut everything off tonight"],
    synthesisTags: ["change_release", "grief_processing", "stress_regulation"],
    confidenceNotes: ["Moon phases are symbolic rhythms to work with, not forces controlling your mood."],
    safetyNotes: [],
  },
  {
    id: "wa.transit.core",
    system: "western_astrology",
    key: "transits_core",
    title: "Transits (Sky Weather)",
    plainMeaning:
      "Transits are the moving planets' relationship to your birth chart — think of them as weather, a changing climate you can dress for, not a fixed fate.",
    strengths: ["Offers timing cues to work with", "Normalizes ups and downs", "Invites gentle preparation"],
    growthEdges: ["Holding forecasts lightly", "Acting from values, not from fear of the sky"],
    supportiveActions: ["journal_prompt", "values_check"],
    avoidSaying: ["The transit will make this happen to you", "You have no choice during this period"],
    synthesisTags: ["timing_patience", "change_release"],
    confidenceNotes: [
      "Transits describe themes and timing, never guaranteed events.",
      "You always keep your agency; the sky is weather, not a script.",
    ],
    safetyNotes: [],
  },
];
